//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: task_manager.proto

package task_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessListRequest_Flags int32

const (
	ProcessListRequest_NONE        ProcessListRequest_Flags = 0
	ProcessListRequest_RESET_CACHE ProcessListRequest_Flags = 1
)

// Enum value maps for ProcessListRequest_Flags.
var (
	ProcessListRequest_Flags_name = map[int32]string{
		0: "NONE",
		1: "RESET_CACHE",
	}
	ProcessListRequest_Flags_value = map[string]int32{
		"NONE":        0,
		"RESET_CACHE": 1,
	}
)

func (x ProcessListRequest_Flags) Enum() *ProcessListRequest_Flags {
	p := new(ProcessListRequest_Flags)
	*p = x
	return p
}

func (x ProcessListRequest_Flags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessListRequest_Flags) Descriptor() protoreflect.EnumDescriptor {
	return file_task_manager_proto_enumTypes[0].Descriptor()
}

func (ProcessListRequest_Flags) Type() protoreflect.EnumType {
	return &file_task_manager_proto_enumTypes[0]
}

func (x ProcessListRequest_Flags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessListRequest_Flags.Descriptor instead.
func (ProcessListRequest_Flags) EnumDescriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{2, 0}
}

type Service_Status int32

const (
	Service_STATUS_UNKNOWN          Service_Status = 0
	Service_STATUS_CONTINUE_PENDING Service_Status = 1
	Service_STATUS_PAUSE_PENDING    Service_Status = 2
	Service_STATUS_PAUSED           Service_Status = 3
	Service_STATUS_RUNNING          Service_Status = 4
	Service_STATUS_START_PENDING    Service_Status = 5
	Service_STATUS_STOP_PENDING     Service_Status = 6
	Service_STATUS_STOPPED          Service_Status = 7
)

// Enum value maps for Service_Status.
var (
	Service_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_CONTINUE_PENDING",
		2: "STATUS_PAUSE_PENDING",
		3: "STATUS_PAUSED",
		4: "STATUS_RUNNING",
		5: "STATUS_START_PENDING",
		6: "STATUS_STOP_PENDING",
		7: "STATUS_STOPPED",
	}
	Service_Status_value = map[string]int32{
		"STATUS_UNKNOWN":          0,
		"STATUS_CONTINUE_PENDING": 1,
		"STATUS_PAUSE_PENDING":    2,
		"STATUS_PAUSED":           3,
		"STATUS_RUNNING":          4,
		"STATUS_START_PENDING":    5,
		"STATUS_STOP_PENDING":     6,
		"STATUS_STOPPED":          7,
	}
)

func (x Service_Status) Enum() *Service_Status {
	p := new(Service_Status)
	*p = x
	return p
}

func (x Service_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_task_manager_proto_enumTypes[1].Descriptor()
}

func (Service_Status) Type() protoreflect.EnumType {
	return &file_task_manager_proto_enumTypes[1]
}

func (x Service_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service_Status.Descriptor instead.
func (Service_Status) EnumDescriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{4, 0}
}

type Service_StartupType int32

const (
	Service_STARTUP_TYPE_UNKNOWN      Service_StartupType = 0
	Service_STARTUP_TYPE_AUTO_START   Service_StartupType = 1
	Service_STARTUP_TYPE_DEMAND_START Service_StartupType = 2
	Service_STARTUP_TYPE_DISABLED     Service_StartupType = 3
	Service_STARTUP_TYPE_BOOT_START   Service_StartupType = 4
	Service_STARTUP_TYPE_SYSTEM_START Service_StartupType = 5
)

// Enum value maps for Service_StartupType.
var (
	Service_StartupType_name = map[int32]string{
		0: "STARTUP_TYPE_UNKNOWN",
		1: "STARTUP_TYPE_AUTO_START",
		2: "STARTUP_TYPE_DEMAND_START",
		3: "STARTUP_TYPE_DISABLED",
		4: "STARTUP_TYPE_BOOT_START",
		5: "STARTUP_TYPE_SYSTEM_START",
	}
	Service_StartupType_value = map[string]int32{
		"STARTUP_TYPE_UNKNOWN":      0,
		"STARTUP_TYPE_AUTO_START":   1,
		"STARTUP_TYPE_DEMAND_START": 2,
		"STARTUP_TYPE_DISABLED":     3,
		"STARTUP_TYPE_BOOT_START":   4,
		"STARTUP_TYPE_SYSTEM_START": 5,
	}
)

func (x Service_StartupType) Enum() *Service_StartupType {
	p := new(Service_StartupType)
	*p = x
	return p
}

func (x Service_StartupType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service_StartupType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_manager_proto_enumTypes[2].Descriptor()
}

func (Service_StartupType) Type() protoreflect.EnumType {
	return &file_task_manager_proto_enumTypes[2]
}

func (x Service_StartupType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service_StartupType.Descriptor instead.
func (Service_StartupType) EnumDescriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{4, 1}
}

type ServiceRequest_Command int32

const (
	ServiceRequest_COMMAND_UNKNOWN ServiceRequest_Command = 0
	ServiceRequest_COMMAND_START   ServiceRequest_Command = 1
	ServiceRequest_COMMAND_STOP    ServiceRequest_Command = 2
)

// Enum value maps for ServiceRequest_Command.
var (
	ServiceRequest_Command_name = map[int32]string{
		0: "COMMAND_UNKNOWN",
		1: "COMMAND_START",
		2: "COMMAND_STOP",
	}
	ServiceRequest_Command_value = map[string]int32{
		"COMMAND_UNKNOWN": 0,
		"COMMAND_START":   1,
		"COMMAND_STOP":    2,
	}
)

func (x ServiceRequest_Command) Enum() *ServiceRequest_Command {
	p := new(ServiceRequest_Command)
	*p = x
	return p
}

func (x ServiceRequest_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceRequest_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_task_manager_proto_enumTypes[3].Descriptor()
}

func (ServiceRequest_Command) Type() protoreflect.EnumType {
	return &file_task_manager_proto_enumTypes[3]
}

func (x ServiceRequest_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceRequest_Command.Descriptor instead.
func (ServiceRequest_Command) EnumDescriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{7, 0}
}

type User_ConnectState int32

const (
	User_CONNECT_STATE_UNKNOWN       User_ConnectState = 0
	User_CONNECT_STATE_ACTIVE        User_ConnectState = 1
	User_CONNECT_STATE_CONNECTED     User_ConnectState = 2
	User_CONNECT_STATE_CONNECT_QUERY User_ConnectState = 3
	User_CONNECT_STATE_SHADOW        User_ConnectState = 4
	User_CONNECT_STATE_DISCONNECTED  User_ConnectState = 5
	User_CONNECT_STATE_IDLE          User_ConnectState = 6
	User_CONNECT_STATE_LISTEN        User_ConnectState = 7
	User_CONNECT_STATE_RESET         User_ConnectState = 8
	User_CONNECT_STATE_DOWN          User_ConnectState = 9
	User_CONNECT_STATE_INIT          User_ConnectState = 10
)

// Enum value maps for User_ConnectState.
var (
	User_ConnectState_name = map[int32]string{
		0:  "CONNECT_STATE_UNKNOWN",
		1:  "CONNECT_STATE_ACTIVE",
		2:  "CONNECT_STATE_CONNECTED",
		3:  "CONNECT_STATE_CONNECT_QUERY",
		4:  "CONNECT_STATE_SHADOW",
		5:  "CONNECT_STATE_DISCONNECTED",
		6:  "CONNECT_STATE_IDLE",
		7:  "CONNECT_STATE_LISTEN",
		8:  "CONNECT_STATE_RESET",
		9:  "CONNECT_STATE_DOWN",
		10: "CONNECT_STATE_INIT",
	}
	User_ConnectState_value = map[string]int32{
		"CONNECT_STATE_UNKNOWN":       0,
		"CONNECT_STATE_ACTIVE":        1,
		"CONNECT_STATE_CONNECTED":     2,
		"CONNECT_STATE_CONNECT_QUERY": 3,
		"CONNECT_STATE_SHADOW":        4,
		"CONNECT_STATE_DISCONNECTED":  5,
		"CONNECT_STATE_IDLE":          6,
		"CONNECT_STATE_LISTEN":        7,
		"CONNECT_STATE_RESET":         8,
		"CONNECT_STATE_DOWN":          9,
		"CONNECT_STATE_INIT":          10,
	}
)

func (x User_ConnectState) Enum() *User_ConnectState {
	p := new(User_ConnectState)
	*p = x
	return p
}

func (x User_ConnectState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_ConnectState) Descriptor() protoreflect.EnumDescriptor {
	return file_task_manager_proto_enumTypes[4].Descriptor()
}

func (User_ConnectState) Type() protoreflect.EnumType {
	return &file_task_manager_proto_enumTypes[4]
}

func (x User_ConnectState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_ConnectState.Descriptor instead.
func (User_ConnectState) EnumDescriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{8, 0}
}

type UserRequest_Command int32

const (
	UserRequest_COMMAND_UNKNOWN    UserRequest_Command = 0
	UserRequest_COMMAND_DISCONNECT UserRequest_Command = 1
	UserRequest_COMMAND_LOGOFF     UserRequest_Command = 2
)

// Enum value maps for UserRequest_Command.
var (
	UserRequest_Command_name = map[int32]string{
		0: "COMMAND_UNKNOWN",
		1: "COMMAND_DISCONNECT",
		2: "COMMAND_LOGOFF",
	}
	UserRequest_Command_value = map[string]int32{
		"COMMAND_UNKNOWN":    0,
		"COMMAND_DISCONNECT": 1,
		"COMMAND_LOGOFF":     2,
	}
)

func (x UserRequest_Command) Enum() *UserRequest_Command {
	p := new(UserRequest_Command)
	*p = x
	return p
}

func (x UserRequest_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRequest_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_task_manager_proto_enumTypes[5].Descriptor()
}

func (UserRequest_Command) Type() protoreflect.EnumType {
	return &file_task_manager_proto_enumTypes[5]
}

func (x UserRequest_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRequest_Command.Descriptor instead.
func (UserRequest_Command) EnumDescriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{11, 0}
}

type Process struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProcessId            uint64                 `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	SessionId            uint64                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProcessName          string                 `protobuf:"bytes,3,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	UserName             string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FilePath             string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	CpuUsage             int32                  `protobuf:"varint,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemWorkingSet        int64                  `protobuf:"varint,7,opt,name=mem_working_set,json=memWorkingSet,proto3" json:"mem_working_set,omitempty"`
	MemPeakWorkingSet    int64                  `protobuf:"varint,8,opt,name=mem_peak_working_set,json=memPeakWorkingSet,proto3" json:"mem_peak_working_set,omitempty"`
	MemWorkingSetDelta   int64                  `protobuf:"varint,9,opt,name=mem_working_set_delta,json=memWorkingSetDelta,proto3" json:"mem_working_set_delta,omitempty"`
	MemPrivateWorkingSet int64                  `protobuf:"varint,10,opt,name=mem_private_working_set,json=memPrivateWorkingSet,proto3" json:"mem_private_working_set,omitempty"`
	ThreadCount          uint32                 `protobuf:"varint,11,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_task_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{0}
}

func (x *Process) GetProcessId() uint64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *Process) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Process) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Process) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Process) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Process) GetCpuUsage() int32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Process) GetMemWorkingSet() int64 {
	if x != nil {
		return x.MemWorkingSet
	}
	return 0
}

func (x *Process) GetMemPeakWorkingSet() int64 {
	if x != nil {
		return x.MemPeakWorkingSet
	}
	return 0
}

func (x *Process) GetMemWorkingSetDelta() int64 {
	if x != nil {
		return x.MemWorkingSetDelta
	}
	return 0
}

func (x *Process) GetMemPrivateWorkingSet() int64 {
	if x != nil {
		return x.MemPrivateWorkingSet
	}
	return 0
}

func (x *Process) GetThreadCount() uint32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

type ProcessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       []*Process             `protobuf:"bytes,1,rep,name=process,proto3" json:"process,omitempty"`
	CpuUsage      int32                  `protobuf:"varint,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   int32                  `protobuf:"varint,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessList) Reset() {
	*x = ProcessList{}
	mi := &file_task_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessList) ProtoMessage() {}

func (x *ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessList.ProtoReflect.Descriptor instead.
func (*ProcessList) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessList) GetProcess() []*Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *ProcessList) GetCpuUsage() int32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ProcessList) GetMemoryUsage() int32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type ProcessListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessListRequest) Reset() {
	*x = ProcessListRequest{}
	mi := &file_task_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessListRequest) ProtoMessage() {}

func (x *ProcessListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessListRequest.ProtoReflect.Descriptor instead.
func (*ProcessListRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessListRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type EndProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint64                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndProcessRequest) Reset() {
	*x = EndProcessRequest{}
	mi := &file_task_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndProcessRequest) ProtoMessage() {}

func (x *EndProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndProcessRequest.ProtoReflect.Descriptor instead.
func (*EndProcessRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{3}
}

func (x *EndProcessRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        Service_Status         `protobuf:"varint,4,opt,name=status,proto3,enum=proto.task_manager.Service_Status" json:"status,omitempty"`
	StartupType   Service_StartupType    `protobuf:"varint,5,opt,name=startup_type,json=startupType,proto3,enum=proto.task_manager.Service_StartupType" json:"startup_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_task_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{4}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetStatus() Service_Status {
	if x != nil {
		return x.Status
	}
	return Service_STATUS_UNKNOWN
}

func (x *Service) GetStartupType() Service_StartupType {
	if x != nil {
		return x.StartupType
	}
	return Service_STARTUP_TYPE_UNKNOWN
}

type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       []*Service             `protobuf:"bytes,1,rep,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_task_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceList) GetService() []*Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type ServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         uint32                 `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceListRequest) Reset() {
	*x = ServiceListRequest{}
	mi := &file_task_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListRequest) ProtoMessage() {}

func (x *ServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListRequest.ProtoReflect.Descriptor instead.
func (*ServiceListRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceListRequest) GetDummy() uint32 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

type ServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       ServiceRequest_Command `protobuf:"varint,2,opt,name=command,proto3,enum=proto.task_manager.ServiceRequest_Command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	mi := &file_task_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceRequest) GetCommand() ServiceRequest_Command {
	if x != nil {
		return x.Command
	}
	return ServiceRequest_COMMAND_UNKNOWN
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	SessionName   string                 `protobuf:"bytes,4,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	ConnectState  User_ConnectState      `protobuf:"varint,5,opt,name=connect_state,json=connectState,proto3,enum=proto.task_manager.User_ConnectState" json:"connect_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_task_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{8}
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *User) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *User) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *User) GetConnectState() User_ConnectState {
	if x != nil {
		return x.ConnectState
	}
	return User_CONNECT_STATE_UNKNOWN
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_task_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{9}
}

func (x *UserList) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         uint32                 `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_task_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{10}
}

func (x *UserListRequest) GetDummy() uint32 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       UserRequest_Command    `protobuf:"varint,2,opt,name=command,proto3,enum=proto.task_manager.UserRequest_Command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_task_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{11}
}

func (x *UserRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *UserRequest) GetCommand() UserRequest_Command {
	if x != nil {
		return x.Command
	}
	return UserRequest_COMMAND_UNKNOWN
}

type ClientToHost struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProcessListRequest *ProcessListRequest    `protobuf:"bytes,1,opt,name=process_list_request,json=processListRequest,proto3" json:"process_list_request,omitempty"`
	EndProcessRequest  *EndProcessRequest     `protobuf:"bytes,2,opt,name=end_process_request,json=endProcessRequest,proto3" json:"end_process_request,omitempty"`
	ServiceListRequest *ServiceListRequest    `protobuf:"bytes,3,opt,name=service_list_request,json=serviceListRequest,proto3" json:"service_list_request,omitempty"`
	ServiceRequest     *ServiceRequest        `protobuf:"bytes,4,opt,name=service_request,json=serviceRequest,proto3" json:"service_request,omitempty"`
	UserListRequest    *UserListRequest       `protobuf:"bytes,5,opt,name=user_list_request,json=userListRequest,proto3" json:"user_list_request,omitempty"`
	UserRequest        *UserRequest           `protobuf:"bytes,6,opt,name=user_request,json=userRequest,proto3" json:"user_request,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientToHost) Reset() {
	*x = ClientToHost{}
	mi := &file_task_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToHost) ProtoMessage() {}

func (x *ClientToHost) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToHost.ProtoReflect.Descriptor instead.
func (*ClientToHost) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{12}
}

func (x *ClientToHost) GetProcessListRequest() *ProcessListRequest {
	if x != nil {
		return x.ProcessListRequest
	}
	return nil
}

func (x *ClientToHost) GetEndProcessRequest() *EndProcessRequest {
	if x != nil {
		return x.EndProcessRequest
	}
	return nil
}

func (x *ClientToHost) GetServiceListRequest() *ServiceListRequest {
	if x != nil {
		return x.ServiceListRequest
	}
	return nil
}

func (x *ClientToHost) GetServiceRequest() *ServiceRequest {
	if x != nil {
		return x.ServiceRequest
	}
	return nil
}

func (x *ClientToHost) GetUserListRequest() *UserListRequest {
	if x != nil {
		return x.UserListRequest
	}
	return nil
}

func (x *ClientToHost) GetUserRequest() *UserRequest {
	if x != nil {
		return x.UserRequest
	}
	return nil
}

type HostToClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessList   *ProcessList           `protobuf:"bytes,1,opt,name=process_list,json=processList,proto3" json:"process_list,omitempty"`
	ServiceList   *ServiceList           `protobuf:"bytes,2,opt,name=service_list,json=serviceList,proto3" json:"service_list,omitempty"`
	UserList      *UserList              `protobuf:"bytes,3,opt,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostToClient) Reset() {
	*x = HostToClient{}
	mi := &file_task_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostToClient) ProtoMessage() {}

func (x *HostToClient) ProtoReflect() protoreflect.Message {
	mi := &file_task_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostToClient.ProtoReflect.Descriptor instead.
func (*HostToClient) Descriptor() ([]byte, []int) {
	return file_task_manager_proto_rawDescGZIP(), []int{13}
}

func (x *HostToClient) GetProcessList() *ProcessList {
	if x != nil {
		return x.ProcessList
	}
	return nil
}

func (x *HostToClient) GetServiceList() *ServiceList {
	if x != nil {
		return x.ServiceList
	}
	return nil
}

func (x *HostToClient) GetUserList() *UserList {
	if x != nil {
		return x.UserList
	}
	return nil
}

var File_task_manager_proto protoreflect.FileDescriptor

const file_task_manager_proto_rawDesc = "" +
	"\n" +
	"\x12task_manager.proto\x12\x12proto.task_manager\"\xa7\x03\n" +
	"\aProcess\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x04R\tprocessId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x04R\tsessionId\x12!\n" +
	"\fprocess_name\x18\x03 \x01(\tR\vprocessName\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x05R\bcpuUsage\x12&\n" +
	"\x0fmem_working_set\x18\a \x01(\x03R\rmemWorkingSet\x12/\n" +
	"\x14mem_peak_working_set\x18\b \x01(\x03R\x11memPeakWorkingSet\x121\n" +
	"\x15mem_working_set_delta\x18\t \x01(\x03R\x12memWorkingSetDelta\x125\n" +
	"\x17mem_private_working_set\x18\n" +
	" \x01(\x03R\x14memPrivateWorkingSet\x12!\n" +
	"\fthread_count\x18\v \x01(\rR\vthreadCount\"\x84\x01\n" +
	"\vProcessList\x125\n" +
	"\aprocess\x18\x01 \x03(\v2\x1b.proto.task_manager.ProcessR\aprocess\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x05R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x05R\vmemoryUsage\"N\n" +
	"\x12ProcessListRequest\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\"\"\n" +
	"\x05Flags\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vRESET_CACHE\x10\x01\"%\n" +
	"\x11EndProcessRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x04R\x03pid\"\xeb\x04\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".proto.task_manager.Service.StatusR\x06status\x12J\n" +
	"\fstartup_type\x18\x05 \x01(\x0e2'.proto.task_manager.Service.StartupTypeR\vstartupType\"\xc1\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17STATUS_CONTINUE_PENDING\x10\x01\x12\x18\n" +
	"\x14STATUS_PAUSE_PENDING\x10\x02\x12\x11\n" +
	"\rSTATUS_PAUSED\x10\x03\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x04\x12\x18\n" +
	"\x14STATUS_START_PENDING\x10\x05\x12\x17\n" +
	"\x13STATUS_STOP_PENDING\x10\x06\x12\x12\n" +
	"\x0eSTATUS_STOPPED\x10\a\"\xba\x01\n" +
	"\vStartupType\x12\x18\n" +
	"\x14STARTUP_TYPE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17STARTUP_TYPE_AUTO_START\x10\x01\x12\x1d\n" +
	"\x19STARTUP_TYPE_DEMAND_START\x10\x02\x12\x19\n" +
	"\x15STARTUP_TYPE_DISABLED\x10\x03\x12\x1b\n" +
	"\x17STARTUP_TYPE_BOOT_START\x10\x04\x12\x1d\n" +
	"\x19STARTUP_TYPE_SYSTEM_START\x10\x05\"D\n" +
	"\vServiceList\x125\n" +
	"\aservice\x18\x01 \x03(\v2\x1b.proto.task_manager.ServiceR\aservice\"*\n" +
	"\x12ServiceListRequest\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\rR\x05dummy\"\xaf\x01\n" +
	"\x0eServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\acommand\x18\x02 \x01(\x0e2*.proto.task_manager.ServiceRequest.CommandR\acommand\"C\n" +
	"\aCommand\x12\x13\n" +
	"\x0fCOMMAND_UNKNOWN\x10\x00\x12\x11\n" +
	"\rCOMMAND_START\x10\x01\x12\x10\n" +
	"\fCOMMAND_STOP\x10\x02\"\x8b\x04\n" +
	"\x04User\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\x12!\n" +
	"\fsession_name\x18\x04 \x01(\tR\vsessionName\x12J\n" +
	"\rconnect_state\x18\x05 \x01(\x0e2%.proto.task_manager.User.ConnectStateR\fconnectState\"\xb6\x02\n" +
	"\fConnectState\x12\x19\n" +
	"\x15CONNECT_STATE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14CONNECT_STATE_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17CONNECT_STATE_CONNECTED\x10\x02\x12\x1f\n" +
	"\x1bCONNECT_STATE_CONNECT_QUERY\x10\x03\x12\x18\n" +
	"\x14CONNECT_STATE_SHADOW\x10\x04\x12\x1e\n" +
	"\x1aCONNECT_STATE_DISCONNECTED\x10\x05\x12\x16\n" +
	"\x12CONNECT_STATE_IDLE\x10\x06\x12\x18\n" +
	"\x14CONNECT_STATE_LISTEN\x10\a\x12\x17\n" +
	"\x13CONNECT_STATE_RESET\x10\b\x12\x16\n" +
	"\x12CONNECT_STATE_DOWN\x10\t\x12\x16\n" +
	"\x12CONNECT_STATE_INIT\x10\n" +
	"\"8\n" +
	"\bUserList\x12,\n" +
	"\x04user\x18\x01 \x03(\v2\x18.proto.task_manager.UserR\x04user\"'\n" +
	"\x0fUserListRequest\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\rR\x05dummy\"\xbb\x01\n" +
	"\vUserRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12A\n" +
	"\acommand\x18\x02 \x01(\x0e2'.proto.task_manager.UserRequest.CommandR\acommand\"J\n" +
	"\aCommand\x12\x13\n" +
	"\x0fCOMMAND_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12COMMAND_DISCONNECT\x10\x01\x12\x12\n" +
	"\x0eCOMMAND_LOGOFF\x10\x02\"\xfb\x03\n" +
	"\fClientToHost\x12X\n" +
	"\x14process_list_request\x18\x01 \x01(\v2&.proto.task_manager.ProcessListRequestR\x12processListRequest\x12U\n" +
	"\x13end_process_request\x18\x02 \x01(\v2%.proto.task_manager.EndProcessRequestR\x11endProcessRequest\x12X\n" +
	"\x14service_list_request\x18\x03 \x01(\v2&.proto.task_manager.ServiceListRequestR\x12serviceListRequest\x12K\n" +
	"\x0fservice_request\x18\x04 \x01(\v2\".proto.task_manager.ServiceRequestR\x0eserviceRequest\x12O\n" +
	"\x11user_list_request\x18\x05 \x01(\v2#.proto.task_manager.UserListRequestR\x0fuserListRequest\x12B\n" +
	"\fuser_request\x18\x06 \x01(\v2\x1f.proto.task_manager.UserRequestR\vuserRequest\"\xd1\x01\n" +
	"\fHostToClient\x12B\n" +
	"\fprocess_list\x18\x01 \x01(\v2\x1f.proto.task_manager.ProcessListR\vprocessList\x12B\n" +
	"\fservice_list\x18\x02 \x01(\v2\x1f.proto.task_manager.ServiceListR\vserviceList\x129\n" +
	"\tuser_list\x18\x03 \x01(\v2\x1c.proto.task_manager.UserListR\buserListB%H\x03Z!aspia_rest_api/proto/task_managerb\x06proto3"

var (
	file_task_manager_proto_rawDescOnce sync.Once
	file_task_manager_proto_rawDescData []byte
)

func file_task_manager_proto_rawDescGZIP() []byte {
	file_task_manager_proto_rawDescOnce.Do(func() {
		file_task_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_manager_proto_rawDesc), len(file_task_manager_proto_rawDesc)))
	})
	return file_task_manager_proto_rawDescData
}

var file_task_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_task_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_task_manager_proto_goTypes = []any{
	(ProcessListRequest_Flags)(0), // 0: proto.task_manager.ProcessListRequest.Flags
	(Service_Status)(0),           // 1: proto.task_manager.Service.Status
	(Service_StartupType)(0),      // 2: proto.task_manager.Service.StartupType
	(ServiceRequest_Command)(0),   // 3: proto.task_manager.ServiceRequest.Command
	(User_ConnectState)(0),        // 4: proto.task_manager.User.ConnectState
	(UserRequest_Command)(0),      // 5: proto.task_manager.UserRequest.Command
	(*Process)(nil),               // 6: proto.task_manager.Process
	(*ProcessList)(nil),           // 7: proto.task_manager.ProcessList
	(*ProcessListRequest)(nil),    // 8: proto.task_manager.ProcessListRequest
	(*EndProcessRequest)(nil),     // 9: proto.task_manager.EndProcessRequest
	(*Service)(nil),               // 10: proto.task_manager.Service
	(*ServiceList)(nil),           // 11: proto.task_manager.ServiceList
	(*ServiceListRequest)(nil),    // 12: proto.task_manager.ServiceListRequest
	(*ServiceRequest)(nil),        // 13: proto.task_manager.ServiceRequest
	(*User)(nil),                  // 14: proto.task_manager.User
	(*UserList)(nil),              // 15: proto.task_manager.UserList
	(*UserListRequest)(nil),       // 16: proto.task_manager.UserListRequest
	(*UserRequest)(nil),           // 17: proto.task_manager.UserRequest
	(*ClientToHost)(nil),          // 18: proto.task_manager.ClientToHost
	(*HostToClient)(nil),          // 19: proto.task_manager.HostToClient
}
var file_task_manager_proto_depIdxs = []int32{
	6,  // 0: proto.task_manager.ProcessList.process:type_name -> proto.task_manager.Process
	1,  // 1: proto.task_manager.Service.status:type_name -> proto.task_manager.Service.Status
	2,  // 2: proto.task_manager.Service.startup_type:type_name -> proto.task_manager.Service.StartupType
	10, // 3: proto.task_manager.ServiceList.service:type_name -> proto.task_manager.Service
	3,  // 4: proto.task_manager.ServiceRequest.command:type_name -> proto.task_manager.ServiceRequest.Command
	4,  // 5: proto.task_manager.User.connect_state:type_name -> proto.task_manager.User.ConnectState
	14, // 6: proto.task_manager.UserList.user:type_name -> proto.task_manager.User
	5,  // 7: proto.task_manager.UserRequest.command:type_name -> proto.task_manager.UserRequest.Command
	8,  // 8: proto.task_manager.ClientToHost.process_list_request:type_name -> proto.task_manager.ProcessListRequest
	9,  // 9: proto.task_manager.ClientToHost.end_process_request:type_name -> proto.task_manager.EndProcessRequest
	12, // 10: proto.task_manager.ClientToHost.service_list_request:type_name -> proto.task_manager.ServiceListRequest
	13, // 11: proto.task_manager.ClientToHost.service_request:type_name -> proto.task_manager.ServiceRequest
	16, // 12: proto.task_manager.ClientToHost.user_list_request:type_name -> proto.task_manager.UserListRequest
	17, // 13: proto.task_manager.ClientToHost.user_request:type_name -> proto.task_manager.UserRequest
	7,  // 14: proto.task_manager.HostToClient.process_list:type_name -> proto.task_manager.ProcessList
	11, // 15: proto.task_manager.HostToClient.service_list:type_name -> proto.task_manager.ServiceList
	15, // 16: proto.task_manager.HostToClient.user_list:type_name -> proto.task_manager.UserList
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_task_manager_proto_init() }
func file_task_manager_proto_init() {
	if File_task_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_manager_proto_rawDesc), len(file_task_manager_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_manager_proto_goTypes,
		DependencyIndexes: file_task_manager_proto_depIdxs,
		EnumInfos:         file_task_manager_proto_enumTypes,
		MessageInfos:      file_task_manager_proto_msgTypes,
	}.Build()
	File_task_manager_proto = out.File
	file_task_manager_proto_goTypes = nil
	file_task_manager_proto_depIdxs = nil
}
