//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: router_admin.proto

package router_admin

import (
	peer "aspia_rest_api/proto/peer"
	router "aspia_rest_api/proto/router"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionRequestType int32

const (
	SessionRequestType_SESSION_REQUEST_UNKNOWN    SessionRequestType = 0
	SessionRequestType_SESSION_REQUEST_DISCONNECT SessionRequestType = 1
)

// Enum value maps for SessionRequestType.
var (
	SessionRequestType_name = map[int32]string{
		0: "SESSION_REQUEST_UNKNOWN",
		1: "SESSION_REQUEST_DISCONNECT",
	}
	SessionRequestType_value = map[string]int32{
		"SESSION_REQUEST_UNKNOWN":    0,
		"SESSION_REQUEST_DISCONNECT": 1,
	}
)

func (x SessionRequestType) Enum() *SessionRequestType {
	p := new(SessionRequestType)
	*p = x
	return p
}

func (x SessionRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_router_admin_proto_enumTypes[0].Descriptor()
}

func (SessionRequestType) Type() protoreflect.EnumType {
	return &file_router_admin_proto_enumTypes[0]
}

func (x SessionRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionRequestType.Descriptor instead.
func (SessionRequestType) EnumDescriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{0}
}

type UserRequestType int32

const (
	UserRequestType_USER_REQUEST_UNKNOWN UserRequestType = 0
	UserRequestType_USER_REQUEST_ADD     UserRequestType = 1
	UserRequestType_USER_REQUEST_MODIFY  UserRequestType = 2
	UserRequestType_USER_REQUEST_DELETE  UserRequestType = 3
)

// Enum value maps for UserRequestType.
var (
	UserRequestType_name = map[int32]string{
		0: "USER_REQUEST_UNKNOWN",
		1: "USER_REQUEST_ADD",
		2: "USER_REQUEST_MODIFY",
		3: "USER_REQUEST_DELETE",
	}
	UserRequestType_value = map[string]int32{
		"USER_REQUEST_UNKNOWN": 0,
		"USER_REQUEST_ADD":     1,
		"USER_REQUEST_MODIFY":  2,
		"USER_REQUEST_DELETE":  3,
	}
)

func (x UserRequestType) Enum() *UserRequestType {
	p := new(UserRequestType)
	*p = x
	return p
}

func (x UserRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_router_admin_proto_enumTypes[1].Descriptor()
}

func (UserRequestType) Type() protoreflect.EnumType {
	return &file_router_admin_proto_enumTypes[1]
}

func (x UserRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRequestType.Descriptor instead.
func (UserRequestType) EnumDescriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{1}
}

type SessionResult_ErrorCode int32

const (
	SessionResult_SUCCESS            SessionResult_ErrorCode = 0
	SessionResult_INVALID_REQUEST    SessionResult_ErrorCode = 1
	SessionResult_INTERNAL_ERROR     SessionResult_ErrorCode = 2
	SessionResult_INVALID_SESSION_ID SessionResult_ErrorCode = 3
)

// Enum value maps for SessionResult_ErrorCode.
var (
	SessionResult_ErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "INVALID_REQUEST",
		2: "INTERNAL_ERROR",
		3: "INVALID_SESSION_ID",
	}
	SessionResult_ErrorCode_value = map[string]int32{
		"SUCCESS":            0,
		"INVALID_REQUEST":    1,
		"INTERNAL_ERROR":     2,
		"INVALID_SESSION_ID": 3,
	}
)

func (x SessionResult_ErrorCode) Enum() *SessionResult_ErrorCode {
	p := new(SessionResult_ErrorCode)
	*p = x
	return p
}

func (x SessionResult_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionResult_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_router_admin_proto_enumTypes[2].Descriptor()
}

func (SessionResult_ErrorCode) Type() protoreflect.EnumType {
	return &file_router_admin_proto_enumTypes[2]
}

func (x SessionResult_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionResult_ErrorCode.Descriptor instead.
func (SessionResult_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{2, 0}
}

type SessionList_ErrorCode int32

const (
	SessionList_SUCCESS       SessionList_ErrorCode = 0
	SessionList_UNKNOWN_ERROR SessionList_ErrorCode = 1
)

// Enum value maps for SessionList_ErrorCode.
var (
	SessionList_ErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "UNKNOWN_ERROR",
	}
	SessionList_ErrorCode_value = map[string]int32{
		"SUCCESS":       0,
		"UNKNOWN_ERROR": 1,
	}
)

func (x SessionList_ErrorCode) Enum() *SessionList_ErrorCode {
	p := new(SessionList_ErrorCode)
	*p = x
	return p
}

func (x SessionList_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionList_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_router_admin_proto_enumTypes[3].Descriptor()
}

func (SessionList_ErrorCode) Type() protoreflect.EnumType {
	return &file_router_admin_proto_enumTypes[3]
}

func (x SessionList_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionList_ErrorCode.Descriptor instead.
func (SessionList_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{4, 0}
}

type UserList_ErrorCode int32

const (
	UserList_SUCCESS       UserList_ErrorCode = 0
	UserList_UNKNOWN_ERROR UserList_ErrorCode = 1
)

// Enum value maps for UserList_ErrorCode.
var (
	UserList_ErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "UNKNOWN_ERROR",
	}
	UserList_ErrorCode_value = map[string]int32{
		"SUCCESS":       0,
		"UNKNOWN_ERROR": 1,
	}
)

func (x UserList_ErrorCode) Enum() *UserList_ErrorCode {
	p := new(UserList_ErrorCode)
	*p = x
	return p
}

func (x UserList_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserList_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_router_admin_proto_enumTypes[4].Descriptor()
}

func (UserList_ErrorCode) Type() protoreflect.EnumType {
	return &file_router_admin_proto_enumTypes[4]
}

func (x UserList_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserList_ErrorCode.Descriptor instead.
func (UserList_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{9, 0}
}

type UserResult_ErrorCode int32

const (
	UserResult_SUCCESS        UserResult_ErrorCode = 0
	UserResult_INTERNAL_ERROR UserResult_ErrorCode = 1
	UserResult_INVALID_DATA   UserResult_ErrorCode = 2
	UserResult_ALREADY_EXISTS UserResult_ErrorCode = 3
)

// Enum value maps for UserResult_ErrorCode.
var (
	UserResult_ErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "INTERNAL_ERROR",
		2: "INVALID_DATA",
		3: "ALREADY_EXISTS",
	}
	UserResult_ErrorCode_value = map[string]int32{
		"SUCCESS":        0,
		"INTERNAL_ERROR": 1,
		"INVALID_DATA":   2,
		"ALREADY_EXISTS": 3,
	}
)

func (x UserResult_ErrorCode) Enum() *UserResult_ErrorCode {
	p := new(UserResult_ErrorCode)
	*p = x
	return p
}

func (x UserResult_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserResult_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_router_admin_proto_enumTypes[5].Descriptor()
}

func (UserResult_ErrorCode) Type() protoreflect.EnumType {
	return &file_router_admin_proto_enumTypes[5]
}

func (x UserResult_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserResult_ErrorCode.Descriptor instead.
func (UserResult_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{11, 0}
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionType   router.SessionType     `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=proto.router.SessionType" json:"session_type,omitempty"`
	SessionData   []byte                 `protobuf:"bytes,3,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`
	Timepoint     uint64                 `protobuf:"fixed64,4,opt,name=timepoint,proto3" json:"timepoint,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Version       *peer.Version          `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	OsName        string                 `protobuf:"bytes,7,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	ComputerName  string                 `protobuf:"bytes,8,opt,name=computer_name,json=computerName,proto3" json:"computer_name,omitempty"`
	Architecture  string                 `protobuf:"bytes,9,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_router_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Session) GetSessionType() router.SessionType {
	if x != nil {
		return x.SessionType
	}
	return router.SessionType(0)
}

func (x *Session) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

func (x *Session) GetTimepoint() uint64 {
	if x != nil {
		return x.Timepoint
	}
	return 0
}

func (x *Session) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Session) GetVersion() *peer.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Session) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *Session) GetComputerName() string {
	if x != nil {
		return x.ComputerName
	}
	return ""
}

func (x *Session) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SessionRequestType     `protobuf:"varint,1,opt,name=type,proto3,enum=proto.router.SessionRequestType" json:"type,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_router_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{1}
}

func (x *SessionRequest) GetType() SessionRequestType {
	if x != nil {
		return x.Type
	}
	return SessionRequestType_SESSION_REQUEST_UNKNOWN
}

func (x *SessionRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type SessionResult struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          SessionRequestType      `protobuf:"varint,1,opt,name=type,proto3,enum=proto.router.SessionRequestType" json:"type,omitempty"`
	ErrorCode     SessionResult_ErrorCode `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=proto.router.SessionResult_ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResult) Reset() {
	*x = SessionResult{}
	mi := &file_router_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResult) ProtoMessage() {}

func (x *SessionResult) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResult.ProtoReflect.Descriptor instead.
func (*SessionResult) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{2}
}

func (x *SessionResult) GetType() SessionRequestType {
	if x != nil {
		return x.Type
	}
	return SessionRequestType_SESSION_REQUEST_UNKNOWN
}

func (x *SessionResult) GetErrorCode() SessionResult_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return SessionResult_SUCCESS
}

type SessionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         int64                  `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionListRequest) Reset() {
	*x = SessionListRequest{}
	mi := &file_router_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionListRequest) ProtoMessage() {}

func (x *SessionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionListRequest.ProtoReflect.Descriptor instead.
func (*SessionListRequest) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{3}
}

func (x *SessionListRequest) GetDummy() int64 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

type SessionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     SessionList_ErrorCode  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=proto.router.SessionList_ErrorCode" json:"error_code,omitempty"`
	Session       []*Session             `protobuf:"bytes,2,rep,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_router_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{4}
}

func (x *SessionList) GetErrorCode() SessionList_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return SessionList_SUCCESS
}

func (x *SessionList) GetSession() []*Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type HostSessionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        []uint64               `protobuf:"fixed64,1,rep,packed,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostSessionData) Reset() {
	*x = HostSessionData{}
	mi := &file_router_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSessionData) ProtoMessage() {}

func (x *HostSessionData) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSessionData.ProtoReflect.Descriptor instead.
func (*HostSessionData) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{5}
}

func (x *HostSessionData) GetHostId() []uint64 {
	if x != nil {
		return x.HostId
	}
	return nil
}

type RelaySessionData struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	PoolSize      uint64                      `protobuf:"varint,1,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	RelayStat     *RelaySessionData_RelayStat `protobuf:"bytes,2,opt,name=relay_stat,json=relayStat,proto3" json:"relay_stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaySessionData) Reset() {
	*x = RelaySessionData{}
	mi := &file_router_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaySessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaySessionData) ProtoMessage() {}

func (x *RelaySessionData) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaySessionData.ProtoReflect.Descriptor instead.
func (*RelaySessionData) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{6}
}

func (x *RelaySessionData) GetPoolSize() uint64 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *RelaySessionData) GetRelayStat() *RelaySessionData_RelayStat {
	if x != nil {
		return x.RelayStat
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       int64                  `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Salt          []byte                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Verifier      []byte                 `protobuf:"bytes,5,opt,name=verifier,proto3" json:"verifier,omitempty"`
	Sessions      uint32                 `protobuf:"varint,6,opt,name=sessions,proto3" json:"sessions,omitempty"`
	Flags         uint32                 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_router_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetEntryId() int64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *User) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *User) GetVerifier() []byte {
	if x != nil {
		return x.Verifier
	}
	return nil
}

func (x *User) GetSessions() uint32 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

func (x *User) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type UserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         uint32                 `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_router_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UserListRequest) GetDummy() uint32 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     UserList_ErrorCode     `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=proto.router.UserList_ErrorCode" json:"error_code,omitempty"`
	User          []*User                `protobuf:"bytes,2,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_router_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UserList) GetErrorCode() UserList_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return UserList_SUCCESS
}

func (x *UserList) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UserRequestType        `protobuf:"varint,1,opt,name=type,proto3,enum=proto.router.UserRequestType" json:"type,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_router_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UserRequest) GetType() UserRequestType {
	if x != nil {
		return x.Type
	}
	return UserRequestType_USER_REQUEST_UNKNOWN
}

func (x *UserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UserRequestType        `protobuf:"varint,1,opt,name=type,proto3,enum=proto.router.UserRequestType" json:"type,omitempty"`
	ErrorCode     UserResult_ErrorCode   `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=proto.router.UserResult_ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResult) Reset() {
	*x = UserResult{}
	mi := &file_router_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResult) ProtoMessage() {}

func (x *UserResult) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResult.ProtoReflect.Descriptor instead.
func (*UserResult) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{11}
}

func (x *UserResult) GetType() UserRequestType {
	if x != nil {
		return x.Type
	}
	return UserRequestType_USER_REQUEST_UNKNOWN
}

func (x *UserResult) GetErrorCode() UserResult_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return UserResult_SUCCESS
}

type RouterToAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionList   *SessionList           `protobuf:"bytes,1,opt,name=session_list,json=sessionList,proto3" json:"session_list,omitempty"`
	SessionResult *SessionResult         `protobuf:"bytes,2,opt,name=session_result,json=sessionResult,proto3" json:"session_result,omitempty"`
	UserList      *UserList              `protobuf:"bytes,3,opt,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	UserResult    *UserResult            `protobuf:"bytes,4,opt,name=user_result,json=userResult,proto3" json:"user_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterToAdmin) Reset() {
	*x = RouterToAdmin{}
	mi := &file_router_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterToAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterToAdmin) ProtoMessage() {}

func (x *RouterToAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterToAdmin.ProtoReflect.Descriptor instead.
func (*RouterToAdmin) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RouterToAdmin) GetSessionList() *SessionList {
	if x != nil {
		return x.SessionList
	}
	return nil
}

func (x *RouterToAdmin) GetSessionResult() *SessionResult {
	if x != nil {
		return x.SessionResult
	}
	return nil
}

func (x *RouterToAdmin) GetUserList() *UserList {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *RouterToAdmin) GetUserResult() *UserResult {
	if x != nil {
		return x.UserResult
	}
	return nil
}

type AdminToRouter struct {
	state                 protoimpl.MessageState        `protogen:"open.v1"`
	SessionListRequest    *SessionListRequest           `protobuf:"bytes,1,opt,name=session_list_request,json=sessionListRequest,proto3" json:"session_list_request,omitempty"`
	SessionRequest        *SessionRequest               `protobuf:"bytes,2,opt,name=session_request,json=sessionRequest,proto3" json:"session_request,omitempty"`
	UserListRequest       *UserListRequest              `protobuf:"bytes,3,opt,name=user_list_request,json=userListRequest,proto3" json:"user_list_request,omitempty"`
	UserRequest           *UserRequest                  `protobuf:"bytes,4,opt,name=user_request,json=userRequest,proto3" json:"user_request,omitempty"`
	PeerConnectionRequest *router.PeerConnectionRequest `protobuf:"bytes,5,opt,name=peer_connection_request,json=peerConnectionRequest,proto3" json:"peer_connection_request,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AdminToRouter) Reset() {
	*x = AdminToRouter{}
	mi := &file_router_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminToRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminToRouter) ProtoMessage() {}

func (x *AdminToRouter) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminToRouter.ProtoReflect.Descriptor instead.
func (*AdminToRouter) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AdminToRouter) GetSessionListRequest() *SessionListRequest {
	if x != nil {
		return x.SessionListRequest
	}
	return nil
}

func (x *AdminToRouter) GetSessionRequest() *SessionRequest {
	if x != nil {
		return x.SessionRequest
	}
	return nil
}

func (x *AdminToRouter) GetUserListRequest() *UserListRequest {
	if x != nil {
		return x.UserListRequest
	}
	return nil
}

func (x *AdminToRouter) GetUserRequest() *UserRequest {
	if x != nil {
		return x.UserRequest
	}
	return nil
}

func (x *AdminToRouter) GetPeerConnectionRequest() *router.PeerConnectionRequest {
	if x != nil {
		return x.PeerConnectionRequest
	}
	return nil
}

type RelaySessionData_RelayStat struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PeerConnection []*router.PeerConnection `protobuf:"bytes,1,rep,name=peer_connection,json=peerConnection,proto3" json:"peer_connection,omitempty"`
	Uptime         int64                    `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelaySessionData_RelayStat) Reset() {
	*x = RelaySessionData_RelayStat{}
	mi := &file_router_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaySessionData_RelayStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaySessionData_RelayStat) ProtoMessage() {}

func (x *RelaySessionData_RelayStat) ProtoReflect() protoreflect.Message {
	mi := &file_router_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaySessionData_RelayStat.ProtoReflect.Descriptor instead.
func (*RelaySessionData_RelayStat) Descriptor() ([]byte, []int) {
	return file_router_admin_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RelaySessionData_RelayStat) GetPeerConnection() []*router.PeerConnection {
	if x != nil {
		return x.PeerConnection
	}
	return nil
}

func (x *RelaySessionData_RelayStat) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

var File_router_admin_proto protoreflect.FileDescriptor

const file_router_admin_proto_rawDesc = "" +
	"\n" +
	"\x12router_admin.proto\x12\fproto.router\x1a\n" +
	"peer.proto\x1a\frouter.proto\"\xd7\x02\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12<\n" +
	"\fsession_type\x18\x02 \x01(\x0e2\x19.proto.router.SessionTypeR\vsessionType\x12!\n" +
	"\fsession_data\x18\x03 \x01(\fR\vsessionData\x12\x1c\n" +
	"\ttimepoint\x18\x04 \x01(\x06R\ttimepoint\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12-\n" +
	"\aversion\x18\x06 \x01(\v2\x13.proto.peer.VersionR\aversion\x12\x17\n" +
	"\aos_name\x18\a \x01(\tR\x06osName\x12#\n" +
	"\rcomputer_name\x18\b \x01(\tR\fcomputerName\x12\"\n" +
	"\farchitecture\x18\t \x01(\tR\farchitecture\"e\n" +
	"\x0eSessionRequest\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .proto.router.SessionRequestTypeR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\"\xe6\x01\n" +
	"\rSessionResult\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .proto.router.SessionRequestTypeR\x04type\x12D\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2%.proto.router.SessionResult.ErrorCodeR\terrorCode\"Y\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x01\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x02\x12\x16\n" +
	"\x12INVALID_SESSION_ID\x10\x03\"*\n" +
	"\x12SessionListRequest\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\x03R\x05dummy\"\xaf\x01\n" +
	"\vSessionList\x12B\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2#.proto.router.SessionList.ErrorCodeR\terrorCode\x12/\n" +
	"\asession\x18\x02 \x03(\v2\x15.proto.router.SessionR\asession\"+\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x01\"*\n" +
	"\x0fHostSessionData\x12\x17\n" +
	"\ahost_id\x18\x01 \x03(\x06R\x06hostId\"\xe4\x01\n" +
	"\x10RelaySessionData\x12\x1b\n" +
	"\tpool_size\x18\x01 \x01(\x04R\bpoolSize\x12G\n" +
	"\n" +
	"relay_stat\x18\x02 \x01(\v2(.proto.router.RelaySessionData.RelayStatR\trelayStat\x1aj\n" +
	"\tRelayStat\x12E\n" +
	"\x0fpeer_connection\x18\x01 \x03(\v2\x1c.proto.router.PeerConnectionR\x0epeerConnection\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\x03R\x06uptime\"\xad\x01\n" +
	"\x04User\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x03R\aentryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\fR\x04salt\x12\x1a\n" +
	"\bverifier\x18\x05 \x01(\fR\bverifier\x12\x1a\n" +
	"\bsessions\x18\x06 \x01(\rR\bsessions\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\"'\n" +
	"\x0fUserListRequest\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\rR\x05dummy\"\xa0\x01\n" +
	"\bUserList\x12?\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2 .proto.router.UserList.ErrorCodeR\terrorCode\x12&\n" +
	"\x04user\x18\x02 \x03(\v2\x12.proto.router.UserR\x04user\"+\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x01\"h\n" +
	"\vUserRequest\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.proto.router.UserRequestTypeR\x04type\x12&\n" +
	"\x04user\x18\x02 \x01(\v2\x12.proto.router.UserR\x04user\"\xd6\x01\n" +
	"\n" +
	"UserResult\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.proto.router.UserRequestTypeR\x04type\x12A\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\".proto.router.UserResult.ErrorCodeR\terrorCode\"R\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x01\x12\x10\n" +
	"\fINVALID_DATA\x10\x02\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x03\"\x81\x02\n" +
	"\rRouterToAdmin\x12<\n" +
	"\fsession_list\x18\x01 \x01(\v2\x19.proto.router.SessionListR\vsessionList\x12B\n" +
	"\x0esession_result\x18\x02 \x01(\v2\x1b.proto.router.SessionResultR\rsessionResult\x123\n" +
	"\tuser_list\x18\x03 \x01(\v2\x16.proto.router.UserListR\buserList\x129\n" +
	"\vuser_result\x18\x04 \x01(\v2\x18.proto.router.UserResultR\n" +
	"userResult\"\x90\x03\n" +
	"\rAdminToRouter\x12R\n" +
	"\x14session_list_request\x18\x01 \x01(\v2 .proto.router.SessionListRequestR\x12sessionListRequest\x12E\n" +
	"\x0fsession_request\x18\x02 \x01(\v2\x1c.proto.router.SessionRequestR\x0esessionRequest\x12I\n" +
	"\x11user_list_request\x18\x03 \x01(\v2\x1d.proto.router.UserListRequestR\x0fuserListRequest\x12<\n" +
	"\fuser_request\x18\x04 \x01(\v2\x19.proto.router.UserRequestR\vuserRequest\x12[\n" +
	"\x17peer_connection_request\x18\x05 \x01(\v2#.proto.router.PeerConnectionRequestR\x15peerConnectionRequest*Q\n" +
	"\x12SessionRequestType\x12\x1b\n" +
	"\x17SESSION_REQUEST_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aSESSION_REQUEST_DISCONNECT\x10\x01*s\n" +
	"\x0fUserRequestType\x12\x18\n" +
	"\x14USER_REQUEST_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10USER_REQUEST_ADD\x10\x01\x12\x17\n" +
	"\x13USER_REQUEST_MODIFY\x10\x02\x12\x17\n" +
	"\x13USER_REQUEST_DELETE\x10\x03B%H\x03Z!aspia_rest_api/proto/router_adminb\x06proto3"

var (
	file_router_admin_proto_rawDescOnce sync.Once
	file_router_admin_proto_rawDescData []byte
)

func file_router_admin_proto_rawDescGZIP() []byte {
	file_router_admin_proto_rawDescOnce.Do(func() {
		file_router_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_admin_proto_rawDesc), len(file_router_admin_proto_rawDesc)))
	})
	return file_router_admin_proto_rawDescData
}

var file_router_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_router_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_router_admin_proto_goTypes = []any{
	(SessionRequestType)(0),              // 0: proto.router.SessionRequestType
	(UserRequestType)(0),                 // 1: proto.router.UserRequestType
	(SessionResult_ErrorCode)(0),         // 2: proto.router.SessionResult.ErrorCode
	(SessionList_ErrorCode)(0),           // 3: proto.router.SessionList.ErrorCode
	(UserList_ErrorCode)(0),              // 4: proto.router.UserList.ErrorCode
	(UserResult_ErrorCode)(0),            // 5: proto.router.UserResult.ErrorCode
	(*Session)(nil),                      // 6: proto.router.Session
	(*SessionRequest)(nil),               // 7: proto.router.SessionRequest
	(*SessionResult)(nil),                // 8: proto.router.SessionResult
	(*SessionListRequest)(nil),           // 9: proto.router.SessionListRequest
	(*SessionList)(nil),                  // 10: proto.router.SessionList
	(*HostSessionData)(nil),              // 11: proto.router.HostSessionData
	(*RelaySessionData)(nil),             // 12: proto.router.RelaySessionData
	(*User)(nil),                         // 13: proto.router.User
	(*UserListRequest)(nil),              // 14: proto.router.UserListRequest
	(*UserList)(nil),                     // 15: proto.router.UserList
	(*UserRequest)(nil),                  // 16: proto.router.UserRequest
	(*UserResult)(nil),                   // 17: proto.router.UserResult
	(*RouterToAdmin)(nil),                // 18: proto.router.RouterToAdmin
	(*AdminToRouter)(nil),                // 19: proto.router.AdminToRouter
	(*RelaySessionData_RelayStat)(nil),   // 20: proto.router.RelaySessionData.RelayStat
	(router.SessionType)(0),              // 21: proto.router.SessionType
	(*peer.Version)(nil),                 // 22: proto.peer.Version
	(*router.PeerConnectionRequest)(nil), // 23: proto.router.PeerConnectionRequest
	(*router.PeerConnection)(nil),        // 24: proto.router.PeerConnection
}
var file_router_admin_proto_depIdxs = []int32{
	21, // 0: proto.router.Session.session_type:type_name -> proto.router.SessionType
	22, // 1: proto.router.Session.version:type_name -> proto.peer.Version
	0,  // 2: proto.router.SessionRequest.type:type_name -> proto.router.SessionRequestType
	0,  // 3: proto.router.SessionResult.type:type_name -> proto.router.SessionRequestType
	2,  // 4: proto.router.SessionResult.error_code:type_name -> proto.router.SessionResult.ErrorCode
	3,  // 5: proto.router.SessionList.error_code:type_name -> proto.router.SessionList.ErrorCode
	6,  // 6: proto.router.SessionList.session:type_name -> proto.router.Session
	20, // 7: proto.router.RelaySessionData.relay_stat:type_name -> proto.router.RelaySessionData.RelayStat
	4,  // 8: proto.router.UserList.error_code:type_name -> proto.router.UserList.ErrorCode
	13, // 9: proto.router.UserList.user:type_name -> proto.router.User
	1,  // 10: proto.router.UserRequest.type:type_name -> proto.router.UserRequestType
	13, // 11: proto.router.UserRequest.user:type_name -> proto.router.User
	1,  // 12: proto.router.UserResult.type:type_name -> proto.router.UserRequestType
	5,  // 13: proto.router.UserResult.error_code:type_name -> proto.router.UserResult.ErrorCode
	10, // 14: proto.router.RouterToAdmin.session_list:type_name -> proto.router.SessionList
	8,  // 15: proto.router.RouterToAdmin.session_result:type_name -> proto.router.SessionResult
	15, // 16: proto.router.RouterToAdmin.user_list:type_name -> proto.router.UserList
	17, // 17: proto.router.RouterToAdmin.user_result:type_name -> proto.router.UserResult
	9,  // 18: proto.router.AdminToRouter.session_list_request:type_name -> proto.router.SessionListRequest
	7,  // 19: proto.router.AdminToRouter.session_request:type_name -> proto.router.SessionRequest
	14, // 20: proto.router.AdminToRouter.user_list_request:type_name -> proto.router.UserListRequest
	16, // 21: proto.router.AdminToRouter.user_request:type_name -> proto.router.UserRequest
	23, // 22: proto.router.AdminToRouter.peer_connection_request:type_name -> proto.router.PeerConnectionRequest
	24, // 23: proto.router.RelaySessionData.RelayStat.peer_connection:type_name -> proto.router.PeerConnection
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_router_admin_proto_init() }
func file_router_admin_proto_init() {
	if File_router_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_admin_proto_rawDesc), len(file_router_admin_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_router_admin_proto_goTypes,
		DependencyIndexes: file_router_admin_proto_depIdxs,
		EnumInfos:         file_router_admin_proto_enumTypes,
		MessageInfos:      file_router_admin_proto_msgTypes,
	}.Build()
	File_router_admin_proto = out.File
	file_router_admin_proto_goTypes = nil
	file_router_admin_proto_depIdxs = nil
}
