//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: file_transfer.proto

package file_transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNKNOWN             ErrorCode = 0
	ErrorCode_ERROR_CODE_SUCCESS             ErrorCode = 1
	ErrorCode_ERROR_CODE_NO_LOGGED_ON_USER   ErrorCode = 2
	ErrorCode_ERROR_CODE_INVALID_REQUEST     ErrorCode = 3
	ErrorCode_ERROR_CODE_INVALID_PATH_NAME   ErrorCode = 4
	ErrorCode_ERROR_CODE_PATH_NOT_FOUND      ErrorCode = 5
	ErrorCode_ERROR_CODE_PATH_ALREADY_EXISTS ErrorCode = 6
	ErrorCode_ERROR_CODE_NO_DRIVES_FOUND     ErrorCode = 7
	ErrorCode_ERROR_CODE_DISK_FULL           ErrorCode = 8
	ErrorCode_ERROR_CODE_ACCESS_DENIED       ErrorCode = 9
	ErrorCode_ERROR_CODE_FILE_OPEN_ERROR     ErrorCode = 10
	ErrorCode_ERROR_CODE_FILE_CREATE_ERROR   ErrorCode = 11
	ErrorCode_ERROR_CODE_FILE_WRITE_ERROR    ErrorCode = 12
	ErrorCode_ERROR_CODE_FILE_READ_ERROR     ErrorCode = 13
	ErrorCode_ERROR_CODE_DISK_NOT_READY      ErrorCode = 14
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNKNOWN",
		1:  "ERROR_CODE_SUCCESS",
		2:  "ERROR_CODE_NO_LOGGED_ON_USER",
		3:  "ERROR_CODE_INVALID_REQUEST",
		4:  "ERROR_CODE_INVALID_PATH_NAME",
		5:  "ERROR_CODE_PATH_NOT_FOUND",
		6:  "ERROR_CODE_PATH_ALREADY_EXISTS",
		7:  "ERROR_CODE_NO_DRIVES_FOUND",
		8:  "ERROR_CODE_DISK_FULL",
		9:  "ERROR_CODE_ACCESS_DENIED",
		10: "ERROR_CODE_FILE_OPEN_ERROR",
		11: "ERROR_CODE_FILE_CREATE_ERROR",
		12: "ERROR_CODE_FILE_WRITE_ERROR",
		13: "ERROR_CODE_FILE_READ_ERROR",
		14: "ERROR_CODE_DISK_NOT_READY",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNKNOWN":             0,
		"ERROR_CODE_SUCCESS":             1,
		"ERROR_CODE_NO_LOGGED_ON_USER":   2,
		"ERROR_CODE_INVALID_REQUEST":     3,
		"ERROR_CODE_INVALID_PATH_NAME":   4,
		"ERROR_CODE_PATH_NOT_FOUND":      5,
		"ERROR_CODE_PATH_ALREADY_EXISTS": 6,
		"ERROR_CODE_NO_DRIVES_FOUND":     7,
		"ERROR_CODE_DISK_FULL":           8,
		"ERROR_CODE_ACCESS_DENIED":       9,
		"ERROR_CODE_FILE_OPEN_ERROR":     10,
		"ERROR_CODE_FILE_CREATE_ERROR":   11,
		"ERROR_CODE_FILE_WRITE_ERROR":    12,
		"ERROR_CODE_FILE_READ_ERROR":     13,
		"ERROR_CODE_DISK_NOT_READY":      14,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_file_transfer_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_file_transfer_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{0}
}

type DriveList_Item_Type int32

const (
	DriveList_Item_TYPE_UNKNOWN        DriveList_Item_Type = 0
	DriveList_Item_TYPE_CDROM          DriveList_Item_Type = 1
	DriveList_Item_TYPE_REMOVABLE      DriveList_Item_Type = 2
	DriveList_Item_TYPE_FIXED          DriveList_Item_Type = 3
	DriveList_Item_TYPE_REMOTE         DriveList_Item_Type = 4
	DriveList_Item_TYPE_RAM            DriveList_Item_Type = 5
	DriveList_Item_TYPE_HOME_FOLDER    DriveList_Item_Type = 6
	DriveList_Item_TYPE_DESKTOP_FOLDER DriveList_Item_Type = 7
	DriveList_Item_TYPE_ROOT_DIRECTORY DriveList_Item_Type = 8
)

// Enum value maps for DriveList_Item_Type.
var (
	DriveList_Item_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_CDROM",
		2: "TYPE_REMOVABLE",
		3: "TYPE_FIXED",
		4: "TYPE_REMOTE",
		5: "TYPE_RAM",
		6: "TYPE_HOME_FOLDER",
		7: "TYPE_DESKTOP_FOLDER",
		8: "TYPE_ROOT_DIRECTORY",
	}
	DriveList_Item_Type_value = map[string]int32{
		"TYPE_UNKNOWN":        0,
		"TYPE_CDROM":          1,
		"TYPE_REMOVABLE":      2,
		"TYPE_FIXED":          3,
		"TYPE_REMOTE":         4,
		"TYPE_RAM":            5,
		"TYPE_HOME_FOLDER":    6,
		"TYPE_DESKTOP_FOLDER": 7,
		"TYPE_ROOT_DIRECTORY": 8,
	}
)

func (x DriveList_Item_Type) Enum() *DriveList_Item_Type {
	p := new(DriveList_Item_Type)
	*p = x
	return p
}

func (x DriveList_Item_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriveList_Item_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_file_transfer_proto_enumTypes[1].Descriptor()
}

func (DriveList_Item_Type) Type() protoreflect.EnumType {
	return &file_file_transfer_proto_enumTypes[1]
}

func (x DriveList_Item_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriveList_Item_Type.Descriptor instead.
func (DriveList_Item_Type) EnumDescriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{0, 0, 0}
}

type PacketRequest_Flags int32

const (
	PacketRequest_NO_FLAGS PacketRequest_Flags = 0
	PacketRequest_CANCEL   PacketRequest_Flags = 1
)

// Enum value maps for PacketRequest_Flags.
var (
	PacketRequest_Flags_name = map[int32]string{
		0: "NO_FLAGS",
		1: "CANCEL",
	}
	PacketRequest_Flags_value = map[string]int32{
		"NO_FLAGS": 0,
		"CANCEL":   1,
	}
)

func (x PacketRequest_Flags) Enum() *PacketRequest_Flags {
	p := new(PacketRequest_Flags)
	*p = x
	return p
}

func (x PacketRequest_Flags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketRequest_Flags) Descriptor() protoreflect.EnumDescriptor {
	return file_file_transfer_proto_enumTypes[2].Descriptor()
}

func (PacketRequest_Flags) Type() protoreflect.EnumType {
	return &file_file_transfer_proto_enumTypes[2]
}

func (x PacketRequest_Flags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketRequest_Flags.Descriptor instead.
func (PacketRequest_Flags) EnumDescriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{6, 0}
}

type Packet_Flags int32

const (
	Packet_NO_FLAGS     Packet_Flags = 0
	Packet_FIRST_PACKET Packet_Flags = 1
	Packet_LAST_PACKET  Packet_Flags = 2
)

// Enum value maps for Packet_Flags.
var (
	Packet_Flags_name = map[int32]string{
		0: "NO_FLAGS",
		1: "FIRST_PACKET",
		2: "LAST_PACKET",
	}
	Packet_Flags_value = map[string]int32{
		"NO_FLAGS":     0,
		"FIRST_PACKET": 1,
		"LAST_PACKET":  2,
	}
)

func (x Packet_Flags) Enum() *Packet_Flags {
	p := new(Packet_Flags)
	*p = x
	return p
}

func (x Packet_Flags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Packet_Flags) Descriptor() protoreflect.EnumDescriptor {
	return file_file_transfer_proto_enumTypes[3].Descriptor()
}

func (Packet_Flags) Type() protoreflect.EnumType {
	return &file_file_transfer_proto_enumTypes[3]
}

func (x Packet_Flags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Packet_Flags.Descriptor instead.
func (Packet_Flags) EnumDescriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{7, 0}
}

type DriveList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*DriveList_Item      `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveList) Reset() {
	*x = DriveList{}
	mi := &file_file_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveList) ProtoMessage() {}

func (x *DriveList) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveList.ProtoReflect.Descriptor instead.
func (*DriveList) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *DriveList) GetItem() []*DriveList_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DriveListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         uint32                 `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveListRequest) Reset() {
	*x = DriveListRequest{}
	mi := &file_file_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveListRequest) ProtoMessage() {}

func (x *DriveListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveListRequest.ProtoReflect.Descriptor instead.
func (*DriveListRequest) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *DriveListRequest) GetDummy() uint32 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

type List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*List_Item           `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_file_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *List) GetItem() []*List_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_file_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Overwrite     bool                   `protobuf:"varint,2,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_file_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *UploadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_file_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketRequest) Reset() {
	*x = PacketRequest{}
	mi := &file_file_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRequest) ProtoMessage() {}

func (x *PacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRequest.ProtoReflect.Descriptor instead.
func (*PacketRequest) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *PacketRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	FileSize      uint64                 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_file_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *Packet) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Packet) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryRequest) Reset() {
	*x = CreateDirectoryRequest{}
	mi := &file_file_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryRequest) ProtoMessage() {}

func (x *CreateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *CreateDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_file_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{9}
}

func (x *RenameRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_file_transfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=proto.file_transfer.ErrorCode" json:"error_code,omitempty"`
	DriveList     *DriveList             `protobuf:"bytes,2,opt,name=drive_list,json=driveList,proto3" json:"drive_list,omitempty"`
	FileList      *List                  `protobuf:"bytes,3,opt,name=file_list,json=fileList,proto3" json:"file_list,omitempty"`
	Packet        *Packet                `protobuf:"bytes,4,opt,name=packet,proto3" json:"packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_file_transfer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{11}
}

func (x *Reply) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNKNOWN
}

func (x *Reply) GetDriveList() *DriveList {
	if x != nil {
		return x.DriveList
	}
	return nil
}

func (x *Reply) GetFileList() *List {
	if x != nil {
		return x.FileList
	}
	return nil
}

func (x *Reply) GetPacket() *Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

type Request struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	DriveListRequest       *DriveListRequest       `protobuf:"bytes,1,opt,name=drive_list_request,json=driveListRequest,proto3" json:"drive_list_request,omitempty"`
	FileListRequest        *ListRequest            `protobuf:"bytes,2,opt,name=file_list_request,json=fileListRequest,proto3" json:"file_list_request,omitempty"`
	CreateDirectoryRequest *CreateDirectoryRequest `protobuf:"bytes,3,opt,name=create_directory_request,json=createDirectoryRequest,proto3" json:"create_directory_request,omitempty"`
	RenameRequest          *RenameRequest          `protobuf:"bytes,4,opt,name=rename_request,json=renameRequest,proto3" json:"rename_request,omitempty"`
	RemoveRequest          *RemoveRequest          `protobuf:"bytes,5,opt,name=remove_request,json=removeRequest,proto3" json:"remove_request,omitempty"`
	DownloadRequest        *DownloadRequest        `protobuf:"bytes,6,opt,name=download_request,json=downloadRequest,proto3" json:"download_request,omitempty"`
	UploadRequest          *UploadRequest          `protobuf:"bytes,7,opt,name=upload_request,json=uploadRequest,proto3" json:"upload_request,omitempty"`
	PacketRequest          *PacketRequest          `protobuf:"bytes,8,opt,name=packet_request,json=packetRequest,proto3" json:"packet_request,omitempty"`
	Packet                 *Packet                 `protobuf:"bytes,9,opt,name=packet,proto3" json:"packet,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_file_transfer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{12}
}

func (x *Request) GetDriveListRequest() *DriveListRequest {
	if x != nil {
		return x.DriveListRequest
	}
	return nil
}

func (x *Request) GetFileListRequest() *ListRequest {
	if x != nil {
		return x.FileListRequest
	}
	return nil
}

func (x *Request) GetCreateDirectoryRequest() *CreateDirectoryRequest {
	if x != nil {
		return x.CreateDirectoryRequest
	}
	return nil
}

func (x *Request) GetRenameRequest() *RenameRequest {
	if x != nil {
		return x.RenameRequest
	}
	return nil
}

func (x *Request) GetRemoveRequest() *RemoveRequest {
	if x != nil {
		return x.RemoveRequest
	}
	return nil
}

func (x *Request) GetDownloadRequest() *DownloadRequest {
	if x != nil {
		return x.DownloadRequest
	}
	return nil
}

func (x *Request) GetUploadRequest() *UploadRequest {
	if x != nil {
		return x.UploadRequest
	}
	return nil
}

func (x *Request) GetPacketRequest() *PacketRequest {
	if x != nil {
		return x.PacketRequest
	}
	return nil
}

func (x *Request) GetPacket() *Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

type DriveList_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DriveList_Item_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=proto.file_transfer.DriveList_Item_Type" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // Fields 3-5 deprecated.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveList_Item) Reset() {
	*x = DriveList_Item{}
	mi := &file_file_transfer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveList_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveList_Item) ProtoMessage() {}

func (x *DriveList_Item) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveList_Item.ProtoReflect.Descriptor instead.
func (*DriveList_Item) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DriveList_Item) GetType() DriveList_Item_Type {
	if x != nil {
		return x.Type
	}
	return DriveList_Item_TYPE_UNKNOWN
}

func (x *DriveList_Item) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type List_Item struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size             uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModificationTime int64                  `protobuf:"varint,3,opt,name=modification_time,json=modificationTime,proto3" json:"modification_time,omitempty"`
	IsDirectory      bool                   `protobuf:"varint,4,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *List_Item) Reset() {
	*x = List_Item{}
	mi := &file_file_transfer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List_Item) ProtoMessage() {}

func (x *List_Item) ProtoReflect() protoreflect.Message {
	mi := &file_file_transfer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List_Item.ProtoReflect.Descriptor instead.
func (*List_Item) Descriptor() ([]byte, []int) {
	return file_file_transfer_proto_rawDescGZIP(), []int{2, 0}
}

func (x *List_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *List_Item) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *List_Item) GetModificationTime() int64 {
	if x != nil {
		return x.ModificationTime
	}
	return 0
}

func (x *List_Item) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

var File_file_transfer_proto protoreflect.FileDescriptor

const file_file_transfer_proto_rawDesc = "" +
	"\n" +
	"\x13file_transfer.proto\x12\x13proto.file_transfer\"\xd5\x02\n" +
	"\tDriveList\x127\n" +
	"\x04item\x18\x01 \x03(\v2#.proto.file_transfer.DriveList.ItemR\x04item\x1a\x8e\x02\n" +
	"\x04Item\x12<\n" +
	"\x04type\x18\x01 \x01(\x0e2(.proto.file_transfer.DriveList.Item.TypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xb3\x01\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_CDROM\x10\x01\x12\x12\n" +
	"\x0eTYPE_REMOVABLE\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_FIXED\x10\x03\x12\x0f\n" +
	"\vTYPE_REMOTE\x10\x04\x12\f\n" +
	"\bTYPE_RAM\x10\x05\x12\x14\n" +
	"\x10TYPE_HOME_FOLDER\x10\x06\x12\x17\n" +
	"\x13TYPE_DESKTOP_FOLDER\x10\a\x12\x17\n" +
	"\x13TYPE_ROOT_DIRECTORY\x10\b\"(\n" +
	"\x10DriveListRequest\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\rR\x05dummy\"\xba\x01\n" +
	"\x04List\x122\n" +
	"\x04item\x18\x01 \x03(\v2\x1e.proto.file_transfer.List.ItemR\x04item\x1a~\n" +
	"\x04Item\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12+\n" +
	"\x11modification_time\x18\x03 \x01(\x03R\x10modificationTime\x12!\n" +
	"\fis_directory\x18\x04 \x01(\bR\visDirectory\"!\n" +
	"\vListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"A\n" +
	"\rUploadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\toverwrite\x18\x02 \x01(\bR\toverwrite\"%\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"H\n" +
	"\rPacketRequest\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\"!\n" +
	"\x05Flags\x12\f\n" +
	"\bNO_FLAGS\x10\x00\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x01\"\x89\x01\n" +
	"\x06Packet\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"8\n" +
	"\x05Flags\x12\f\n" +
	"\bNO_FLAGS\x10\x00\x12\x10\n" +
	"\fFIRST_PACKET\x10\x01\x12\x0f\n" +
	"\vLAST_PACKET\x10\x02\",\n" +
	"\x16CreateDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"E\n" +
	"\rRenameRequest\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"#\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xf2\x01\n" +
	"\x05Reply\x12=\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x1e.proto.file_transfer.ErrorCodeR\terrorCode\x12=\n" +
	"\n" +
	"drive_list\x18\x02 \x01(\v2\x1e.proto.file_transfer.DriveListR\tdriveList\x126\n" +
	"\tfile_list\x18\x03 \x01(\v2\x19.proto.file_transfer.ListR\bfileList\x123\n" +
	"\x06packet\x18\x04 \x01(\v2\x1b.proto.file_transfer.PacketR\x06packet\"\xc5\x05\n" +
	"\aRequest\x12S\n" +
	"\x12drive_list_request\x18\x01 \x01(\v2%.proto.file_transfer.DriveListRequestR\x10driveListRequest\x12L\n" +
	"\x11file_list_request\x18\x02 \x01(\v2 .proto.file_transfer.ListRequestR\x0ffileListRequest\x12e\n" +
	"\x18create_directory_request\x18\x03 \x01(\v2+.proto.file_transfer.CreateDirectoryRequestR\x16createDirectoryRequest\x12I\n" +
	"\x0erename_request\x18\x04 \x01(\v2\".proto.file_transfer.RenameRequestR\rrenameRequest\x12I\n" +
	"\x0eremove_request\x18\x05 \x01(\v2\".proto.file_transfer.RemoveRequestR\rremoveRequest\x12O\n" +
	"\x10download_request\x18\x06 \x01(\v2$.proto.file_transfer.DownloadRequestR\x0fdownloadRequest\x12I\n" +
	"\x0eupload_request\x18\a \x01(\v2\".proto.file_transfer.UploadRequestR\ruploadRequest\x12I\n" +
	"\x0epacket_request\x18\b \x01(\v2\".proto.file_transfer.PacketRequestR\rpacketRequest\x123\n" +
	"\x06packet\x18\t \x01(\v2\x1b.proto.file_transfer.PacketR\x06packet*\xdc\x03\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12ERROR_CODE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12ERROR_CODE_SUCCESS\x10\x01\x12 \n" +
	"\x1cERROR_CODE_NO_LOGGED_ON_USER\x10\x02\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x03\x12 \n" +
	"\x1cERROR_CODE_INVALID_PATH_NAME\x10\x04\x12\x1d\n" +
	"\x19ERROR_CODE_PATH_NOT_FOUND\x10\x05\x12\"\n" +
	"\x1eERROR_CODE_PATH_ALREADY_EXISTS\x10\x06\x12\x1e\n" +
	"\x1aERROR_CODE_NO_DRIVES_FOUND\x10\a\x12\x18\n" +
	"\x14ERROR_CODE_DISK_FULL\x10\b\x12\x1c\n" +
	"\x18ERROR_CODE_ACCESS_DENIED\x10\t\x12\x1e\n" +
	"\x1aERROR_CODE_FILE_OPEN_ERROR\x10\n" +
	"\x12 \n" +
	"\x1cERROR_CODE_FILE_CREATE_ERROR\x10\v\x12\x1f\n" +
	"\x1bERROR_CODE_FILE_WRITE_ERROR\x10\f\x12\x1e\n" +
	"\x1aERROR_CODE_FILE_READ_ERROR\x10\r\x12\x1d\n" +
	"\x19ERROR_CODE_DISK_NOT_READY\x10\x0eB&H\x03Z\"aspia_rest_api/proto/file_transferb\x06proto3"

var (
	file_file_transfer_proto_rawDescOnce sync.Once
	file_file_transfer_proto_rawDescData []byte
)

func file_file_transfer_proto_rawDescGZIP() []byte {
	file_file_transfer_proto_rawDescOnce.Do(func() {
		file_file_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_transfer_proto_rawDesc), len(file_file_transfer_proto_rawDesc)))
	})
	return file_file_transfer_proto_rawDescData
}

var file_file_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_file_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_file_transfer_proto_goTypes = []any{
	(ErrorCode)(0),                 // 0: proto.file_transfer.ErrorCode
	(DriveList_Item_Type)(0),       // 1: proto.file_transfer.DriveList.Item.Type
	(PacketRequest_Flags)(0),       // 2: proto.file_transfer.PacketRequest.Flags
	(Packet_Flags)(0),              // 3: proto.file_transfer.Packet.Flags
	(*DriveList)(nil),              // 4: proto.file_transfer.DriveList
	(*DriveListRequest)(nil),       // 5: proto.file_transfer.DriveListRequest
	(*List)(nil),                   // 6: proto.file_transfer.List
	(*ListRequest)(nil),            // 7: proto.file_transfer.ListRequest
	(*UploadRequest)(nil),          // 8: proto.file_transfer.UploadRequest
	(*DownloadRequest)(nil),        // 9: proto.file_transfer.DownloadRequest
	(*PacketRequest)(nil),          // 10: proto.file_transfer.PacketRequest
	(*Packet)(nil),                 // 11: proto.file_transfer.Packet
	(*CreateDirectoryRequest)(nil), // 12: proto.file_transfer.CreateDirectoryRequest
	(*RenameRequest)(nil),          // 13: proto.file_transfer.RenameRequest
	(*RemoveRequest)(nil),          // 14: proto.file_transfer.RemoveRequest
	(*Reply)(nil),                  // 15: proto.file_transfer.Reply
	(*Request)(nil),                // 16: proto.file_transfer.Request
	(*DriveList_Item)(nil),         // 17: proto.file_transfer.DriveList.Item
	(*List_Item)(nil),              // 18: proto.file_transfer.List.Item
}
var file_file_transfer_proto_depIdxs = []int32{
	17, // 0: proto.file_transfer.DriveList.item:type_name -> proto.file_transfer.DriveList.Item
	18, // 1: proto.file_transfer.List.item:type_name -> proto.file_transfer.List.Item
	0,  // 2: proto.file_transfer.Reply.error_code:type_name -> proto.file_transfer.ErrorCode
	4,  // 3: proto.file_transfer.Reply.drive_list:type_name -> proto.file_transfer.DriveList
	6,  // 4: proto.file_transfer.Reply.file_list:type_name -> proto.file_transfer.List
	11, // 5: proto.file_transfer.Reply.packet:type_name -> proto.file_transfer.Packet
	5,  // 6: proto.file_transfer.Request.drive_list_request:type_name -> proto.file_transfer.DriveListRequest
	7,  // 7: proto.file_transfer.Request.file_list_request:type_name -> proto.file_transfer.ListRequest
	12, // 8: proto.file_transfer.Request.create_directory_request:type_name -> proto.file_transfer.CreateDirectoryRequest
	13, // 9: proto.file_transfer.Request.rename_request:type_name -> proto.file_transfer.RenameRequest
	14, // 10: proto.file_transfer.Request.remove_request:type_name -> proto.file_transfer.RemoveRequest
	9,  // 11: proto.file_transfer.Request.download_request:type_name -> proto.file_transfer.DownloadRequest
	8,  // 12: proto.file_transfer.Request.upload_request:type_name -> proto.file_transfer.UploadRequest
	10, // 13: proto.file_transfer.Request.packet_request:type_name -> proto.file_transfer.PacketRequest
	11, // 14: proto.file_transfer.Request.packet:type_name -> proto.file_transfer.Packet
	1,  // 15: proto.file_transfer.DriveList.Item.type:type_name -> proto.file_transfer.DriveList.Item.Type
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_file_transfer_proto_init() }
func file_file_transfer_proto_init() {
	if File_file_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_transfer_proto_rawDesc), len(file_file_transfer_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_transfer_proto_goTypes,
		DependencyIndexes: file_file_transfer_proto_depIdxs,
		EnumInfos:         file_file_transfer_proto_enumTypes,
		MessageInfos:      file_file_transfer_proto_msgTypes,
	}.Build()
	File_file_transfer_proto = out.File
	file_file_transfer_proto_goTypes = nil
	file_file_transfer_proto_depIdxs = nil
}
