//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: relay_peer.proto

package relay_peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent from peer to relay for authentication.
// If the authentication failed, then the connection should be dropped.
type PeerToRelay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique key identifier in the relay pool.
	KeyId uint32 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Public key of the peer.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Encrypted secret.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerToRelay) Reset() {
	*x = PeerToRelay{}
	mi := &file_relay_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerToRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerToRelay) ProtoMessage() {}

func (x *PeerToRelay) ProtoReflect() protoreflect.Message {
	mi := &file_relay_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerToRelay.ProtoReflect.Descriptor instead.
func (*PeerToRelay) Descriptor() ([]byte, []int) {
	return file_relay_peer_proto_rawDescGZIP(), []int{0}
}

func (x *PeerToRelay) GetKeyId() uint32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *PeerToRelay) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PeerToRelay) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PeerToRelay_Secret struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RandomData     []byte                 `protobuf:"bytes,1,opt,name=random_data,json=randomData,proto3" json:"random_data,omitempty"`
	ClientAddress  string                 `protobuf:"bytes,2,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	ClientUserName string                 `protobuf:"bytes,3,opt,name=client_user_name,json=clientUserName,proto3" json:"client_user_name,omitempty"`
	HostAddress    string                 `protobuf:"bytes,4,opt,name=host_address,json=hostAddress,proto3" json:"host_address,omitempty"`
	HostId         uint64                 `protobuf:"fixed64,5,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerToRelay_Secret) Reset() {
	*x = PeerToRelay_Secret{}
	mi := &file_relay_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerToRelay_Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerToRelay_Secret) ProtoMessage() {}

func (x *PeerToRelay_Secret) ProtoReflect() protoreflect.Message {
	mi := &file_relay_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerToRelay_Secret.ProtoReflect.Descriptor instead.
func (*PeerToRelay_Secret) Descriptor() ([]byte, []int) {
	return file_relay_peer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PeerToRelay_Secret) GetRandomData() []byte {
	if x != nil {
		return x.RandomData
	}
	return nil
}

func (x *PeerToRelay_Secret) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *PeerToRelay_Secret) GetClientUserName() string {
	if x != nil {
		return x.ClientUserName
	}
	return ""
}

func (x *PeerToRelay_Secret) GetHostAddress() string {
	if x != nil {
		return x.HostAddress
	}
	return ""
}

func (x *PeerToRelay_Secret) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

var File_relay_peer_proto protoreflect.FileDescriptor

const file_relay_peer_proto_rawDesc = "" +
	"\n" +
	"\x10relay_peer.proto\x12\vproto.relay\"\x90\x02\n" +
	"\vPeerToRelay\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\rR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x1a\xb6\x01\n" +
	"\x06Secret\x12\x1f\n" +
	"\vrandom_data\x18\x01 \x01(\fR\n" +
	"randomData\x12%\n" +
	"\x0eclient_address\x18\x02 \x01(\tR\rclientAddress\x12(\n" +
	"\x10client_user_name\x18\x03 \x01(\tR\x0eclientUserName\x12!\n" +
	"\fhost_address\x18\x04 \x01(\tR\vhostAddress\x12\x17\n" +
	"\ahost_id\x18\x05 \x01(\x06R\x06hostIdB#H\x03Z\x1faspia_rest_api/proto/relay_peerb\x06proto3"

var (
	file_relay_peer_proto_rawDescOnce sync.Once
	file_relay_peer_proto_rawDescData []byte
)

func file_relay_peer_proto_rawDescGZIP() []byte {
	file_relay_peer_proto_rawDescOnce.Do(func() {
		file_relay_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_peer_proto_rawDesc), len(file_relay_peer_proto_rawDesc)))
	})
	return file_relay_peer_proto_rawDescData
}

var file_relay_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_relay_peer_proto_goTypes = []any{
	(*PeerToRelay)(nil),        // 0: proto.relay.PeerToRelay
	(*PeerToRelay_Secret)(nil), // 1: proto.relay.PeerToRelay.Secret
}
var file_relay_peer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relay_peer_proto_init() }
func file_relay_peer_proto_init() {
	if File_relay_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_peer_proto_rawDesc), len(file_relay_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_peer_proto_goTypes,
		DependencyIndexes: file_relay_peer_proto_depIdxs,
		MessageInfos:      file_relay_peer_proto_msgTypes,
	}.Build()
	File_relay_peer_proto = out.File
	file_relay_peer_proto_goTypes = nil
	file_relay_peer_proto_depIdxs = nil
}
