//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: desktop.proto

package desktop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identifies how the image was encoded.
type VideoEncoding int32

const (
	VideoEncoding_VIDEO_ENCODING_UNKNOWN VideoEncoding = 0
	VideoEncoding_VIDEO_ENCODING_ZSTD    VideoEncoding = 1
	VideoEncoding_VIDEO_ENCODING_VP8     VideoEncoding = 2
	VideoEncoding_VIDEO_ENCODING_VP9     VideoEncoding = 4
)

// Enum value maps for VideoEncoding.
var (
	VideoEncoding_name = map[int32]string{
		0: "VIDEO_ENCODING_UNKNOWN",
		1: "VIDEO_ENCODING_ZSTD",
		2: "VIDEO_ENCODING_VP8",
		4: "VIDEO_ENCODING_VP9",
	}
	VideoEncoding_value = map[string]int32{
		"VIDEO_ENCODING_UNKNOWN": 0,
		"VIDEO_ENCODING_ZSTD":    1,
		"VIDEO_ENCODING_VP8":     2,
		"VIDEO_ENCODING_VP9":     4,
	}
)

func (x VideoEncoding) Enum() *VideoEncoding {
	p := new(VideoEncoding)
	*p = x
	return p
}

func (x VideoEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[0].Descriptor()
}

func (VideoEncoding) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[0]
}

func (x VideoEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoEncoding.Descriptor instead.
func (VideoEncoding) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{0}
}

type VideoErrorCode int32

const (
	VideoErrorCode_VIDEO_ERROR_CODE_OK        VideoErrorCode = 0
	VideoErrorCode_VIDEO_ERROR_CODE_PAUSED    VideoErrorCode = 1
	VideoErrorCode_VIDEO_ERROR_CODE_TEMPORARY VideoErrorCode = 2
	VideoErrorCode_VIDEO_ERROR_CODE_PERMANENT VideoErrorCode = 3
)

// Enum value maps for VideoErrorCode.
var (
	VideoErrorCode_name = map[int32]string{
		0: "VIDEO_ERROR_CODE_OK",
		1: "VIDEO_ERROR_CODE_PAUSED",
		2: "VIDEO_ERROR_CODE_TEMPORARY",
		3: "VIDEO_ERROR_CODE_PERMANENT",
	}
	VideoErrorCode_value = map[string]int32{
		"VIDEO_ERROR_CODE_OK":        0,
		"VIDEO_ERROR_CODE_PAUSED":    1,
		"VIDEO_ERROR_CODE_TEMPORARY": 2,
		"VIDEO_ERROR_CODE_PERMANENT": 3,
	}
)

func (x VideoErrorCode) Enum() *VideoErrorCode {
	p := new(VideoErrorCode)
	*p = x
	return p
}

func (x VideoErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[1].Descriptor()
}

func (VideoErrorCode) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[1]
}

func (x VideoErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoErrorCode.Descriptor instead.
func (VideoErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{1}
}

type AudioEncoding int32

const (
	AudioEncoding_AUDIO_ENCODING_UNKNOWN AudioEncoding = 0
	AudioEncoding_AUDIO_ENCODING_DEFAULT AudioEncoding = 1
	AudioEncoding_AUDIO_ENCODING_RAW     AudioEncoding = 2
	AudioEncoding_AUDIO_ENCODING_OPUS    AudioEncoding = 3
)

// Enum value maps for AudioEncoding.
var (
	AudioEncoding_name = map[int32]string{
		0: "AUDIO_ENCODING_UNKNOWN",
		1: "AUDIO_ENCODING_DEFAULT",
		2: "AUDIO_ENCODING_RAW",
		3: "AUDIO_ENCODING_OPUS",
	}
	AudioEncoding_value = map[string]int32{
		"AUDIO_ENCODING_UNKNOWN": 0,
		"AUDIO_ENCODING_DEFAULT": 1,
		"AUDIO_ENCODING_RAW":     2,
		"AUDIO_ENCODING_OPUS":    3,
	}
)

func (x AudioEncoding) Enum() *AudioEncoding {
	p := new(AudioEncoding)
	*p = x
	return p
}

func (x AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[2].Descriptor()
}

func (AudioEncoding) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[2]
}

func (x AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioEncoding.Descriptor instead.
func (AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{2}
}

type ConfigFlags int32

const (
	ConfigFlags_NO_FLAGS               ConfigFlags = 0
	ConfigFlags_ENABLE_CURSOR_SHAPE    ConfigFlags = 1
	ConfigFlags_ENABLE_CLIPBOARD       ConfigFlags = 2
	ConfigFlags_DISABLE_EFFECTS        ConfigFlags = 4
	ConfigFlags_DISABLE_WALLPAPER      ConfigFlags = 8
	ConfigFlags_DISABLE_FONT_SMOOTHING ConfigFlags = 16
	ConfigFlags_BLOCK_REMOTE_INPUT     ConfigFlags = 32
	ConfigFlags_LOCK_AT_DISCONNECT     ConfigFlags = 64
	ConfigFlags_CURSOR_POSITION        ConfigFlags = 128
	ConfigFlags_CLEAR_CLIPBOARD        ConfigFlags = 256
)

// Enum value maps for ConfigFlags.
var (
	ConfigFlags_name = map[int32]string{
		0:   "NO_FLAGS",
		1:   "ENABLE_CURSOR_SHAPE",
		2:   "ENABLE_CLIPBOARD",
		4:   "DISABLE_EFFECTS",
		8:   "DISABLE_WALLPAPER",
		16:  "DISABLE_FONT_SMOOTHING",
		32:  "BLOCK_REMOTE_INPUT",
		64:  "LOCK_AT_DISCONNECT",
		128: "CURSOR_POSITION",
		256: "CLEAR_CLIPBOARD",
	}
	ConfigFlags_value = map[string]int32{
		"NO_FLAGS":               0,
		"ENABLE_CURSOR_SHAPE":    1,
		"ENABLE_CLIPBOARD":       2,
		"DISABLE_EFFECTS":        4,
		"DISABLE_WALLPAPER":      8,
		"DISABLE_FONT_SMOOTHING": 16,
		"BLOCK_REMOTE_INPUT":     32,
		"LOCK_AT_DISCONNECT":     64,
		"CURSOR_POSITION":        128,
		"CLEAR_CLIPBOARD":        256,
	}
)

func (x ConfigFlags) Enum() *ConfigFlags {
	p := new(ConfigFlags)
	*p = x
	return p
}

func (x ConfigFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[3].Descriptor()
}

func (ConfigFlags) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[3]
}

func (x ConfigFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFlags.Descriptor instead.
func (ConfigFlags) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{3}
}

// The keyboard (Caps/Num) lock states.
type KeyEvent_Flags int32

const (
	KeyEvent_UNKNOWN  KeyEvent_Flags = 0
	KeyEvent_CAPSLOCK KeyEvent_Flags = 1
	KeyEvent_NUMLOCK  KeyEvent_Flags = 2
	KeyEvent_PRESSED  KeyEvent_Flags = 4
)

// Enum value maps for KeyEvent_Flags.
var (
	KeyEvent_Flags_name = map[int32]string{
		0: "UNKNOWN",
		1: "CAPSLOCK",
		2: "NUMLOCK",
		4: "PRESSED",
	}
	KeyEvent_Flags_value = map[string]int32{
		"UNKNOWN":  0,
		"CAPSLOCK": 1,
		"NUMLOCK":  2,
		"PRESSED":  4,
	}
)

func (x KeyEvent_Flags) Enum() *KeyEvent_Flags {
	p := new(KeyEvent_Flags)
	*p = x
	return p
}

func (x KeyEvent_Flags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyEvent_Flags) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[4].Descriptor()
}

func (KeyEvent_Flags) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[4]
}

func (x KeyEvent_Flags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyEvent_Flags.Descriptor instead.
func (KeyEvent_Flags) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{4, 0}
}

type MouseEvent_ButtonMask int32

const (
	MouseEvent_EMPTY          MouseEvent_ButtonMask = 0
	MouseEvent_LEFT_BUTTON    MouseEvent_ButtonMask = 1
	MouseEvent_MIDDLE_BUTTON  MouseEvent_ButtonMask = 2
	MouseEvent_RIGHT_BUTTON   MouseEvent_ButtonMask = 4
	MouseEvent_WHEEL_UP       MouseEvent_ButtonMask = 8
	MouseEvent_WHEEL_DOWN     MouseEvent_ButtonMask = 16
	MouseEvent_BACK_BUTTON    MouseEvent_ButtonMask = 32
	MouseEvent_FORWARD_BUTTON MouseEvent_ButtonMask = 64
)

// Enum value maps for MouseEvent_ButtonMask.
var (
	MouseEvent_ButtonMask_name = map[int32]string{
		0:  "EMPTY",
		1:  "LEFT_BUTTON",
		2:  "MIDDLE_BUTTON",
		4:  "RIGHT_BUTTON",
		8:  "WHEEL_UP",
		16: "WHEEL_DOWN",
		32: "BACK_BUTTON",
		64: "FORWARD_BUTTON",
	}
	MouseEvent_ButtonMask_value = map[string]int32{
		"EMPTY":          0,
		"LEFT_BUTTON":    1,
		"MIDDLE_BUTTON":  2,
		"RIGHT_BUTTON":   4,
		"WHEEL_UP":       8,
		"WHEEL_DOWN":     16,
		"BACK_BUTTON":    32,
		"FORWARD_BUTTON": 64,
	}
)

func (x MouseEvent_ButtonMask) Enum() *MouseEvent_ButtonMask {
	p := new(MouseEvent_ButtonMask)
	*p = x
	return p
}

func (x MouseEvent_ButtonMask) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MouseEvent_ButtonMask) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[5].Descriptor()
}

func (MouseEvent_ButtonMask) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[5]
}

func (x MouseEvent_ButtonMask) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MouseEvent_ButtonMask.Descriptor instead.
func (MouseEvent_ButtonMask) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{6, 0}
}

// A START event means that this event reports all the touch points that were just added, e.g. a
// finger started touching the display.
// A MOVE event means that the touch points that have been STARTed moved, e.g. multiple fingers
// on the screen moved.
// An END event means that the touch points that have been STARTed ended. e.g. a finger went off
// the screen.
// A CANCEL event means that the touch points that have been STARTed were canceled, e.g. a finger
// went off the screen.
// Cancel event is simlar to END but slighly different. For example, Android
// MotionEvent's ACTION_CANCEL documentation mentions that a cancel should be
// treated as an ACTION_UP (END) event but might not perform the exact same
// actions as a normal ACTION_UP event.
type TouchEvent_TouchEventType int32

const (
	TouchEvent_TOUCH_POINT_UNKNOWN TouchEvent_TouchEventType = 0
	TouchEvent_TOUCH_POINT_START   TouchEvent_TouchEventType = 1
	TouchEvent_TOUCH_POINT_MOVE    TouchEvent_TouchEventType = 2
	TouchEvent_TOUCH_POINT_END     TouchEvent_TouchEventType = 3
	TouchEvent_TOUCH_POINT_CANCEL  TouchEvent_TouchEventType = 4
)

// Enum value maps for TouchEvent_TouchEventType.
var (
	TouchEvent_TouchEventType_name = map[int32]string{
		0: "TOUCH_POINT_UNKNOWN",
		1: "TOUCH_POINT_START",
		2: "TOUCH_POINT_MOVE",
		3: "TOUCH_POINT_END",
		4: "TOUCH_POINT_CANCEL",
	}
	TouchEvent_TouchEventType_value = map[string]int32{
		"TOUCH_POINT_UNKNOWN": 0,
		"TOUCH_POINT_START":   1,
		"TOUCH_POINT_MOVE":    2,
		"TOUCH_POINT_END":     3,
		"TOUCH_POINT_CANCEL":  4,
	}
)

func (x TouchEvent_TouchEventType) Enum() *TouchEvent_TouchEventType {
	p := new(TouchEvent_TouchEventType)
	*p = x
	return p
}

func (x TouchEvent_TouchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TouchEvent_TouchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[6].Descriptor()
}

func (TouchEvent_TouchEventType) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[6]
}

func (x TouchEvent_TouchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TouchEvent_TouchEventType.Descriptor instead.
func (TouchEvent_TouchEventType) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{8, 0}
}

type CursorShape_Flags int32

const (
	CursorShape_UNKNOWN     CursorShape_Flags = 0
	CursorShape_RESET_CACHE CursorShape_Flags = 64
	CursorShape_CACHE       CursorShape_Flags = 128
)

// Enum value maps for CursorShape_Flags.
var (
	CursorShape_Flags_name = map[int32]string{
		0:   "UNKNOWN",
		64:  "RESET_CACHE",
		128: "CACHE",
	}
	CursorShape_Flags_value = map[string]int32{
		"UNKNOWN":     0,
		"RESET_CACHE": 64,
		"CACHE":       128,
	}
)

func (x CursorShape_Flags) Enum() *CursorShape_Flags {
	p := new(CursorShape_Flags)
	*p = x
	return p
}

func (x CursorShape_Flags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CursorShape_Flags) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[7].Descriptor()
}

func (CursorShape_Flags) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[7]
}

func (x CursorShape_Flags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CursorShape_Flags.Descriptor instead.
func (CursorShape_Flags) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{10, 0}
}

type AudioPacket_SamplingRate int32

const (
	AudioPacket_SAMPLING_RATE_INVALID AudioPacket_SamplingRate = 0
	AudioPacket_SAMPLING_RATE_44100   AudioPacket_SamplingRate = 44100
	AudioPacket_SAMPLING_RATE_48000   AudioPacket_SamplingRate = 48000
	AudioPacket_SAMPLING_RATE_96000   AudioPacket_SamplingRate = 96000
	AudioPacket_SAMPLING_RATE_192000  AudioPacket_SamplingRate = 192000
)

// Enum value maps for AudioPacket_SamplingRate.
var (
	AudioPacket_SamplingRate_name = map[int32]string{
		0:      "SAMPLING_RATE_INVALID",
		44100:  "SAMPLING_RATE_44100",
		48000:  "SAMPLING_RATE_48000",
		96000:  "SAMPLING_RATE_96000",
		192000: "SAMPLING_RATE_192000",
	}
	AudioPacket_SamplingRate_value = map[string]int32{
		"SAMPLING_RATE_INVALID": 0,
		"SAMPLING_RATE_44100":   44100,
		"SAMPLING_RATE_48000":   48000,
		"SAMPLING_RATE_96000":   96000,
		"SAMPLING_RATE_192000":  192000,
	}
)

func (x AudioPacket_SamplingRate) Enum() *AudioPacket_SamplingRate {
	p := new(AudioPacket_SamplingRate)
	*p = x
	return p
}

func (x AudioPacket_SamplingRate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioPacket_SamplingRate) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[8].Descriptor()
}

func (AudioPacket_SamplingRate) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[8]
}

func (x AudioPacket_SamplingRate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioPacket_SamplingRate.Descriptor instead.
func (AudioPacket_SamplingRate) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{14, 0}
}

type AudioPacket_BytesPerSample int32

const (
	AudioPacket_BYTES_PER_SAMPLE_INVALID AudioPacket_BytesPerSample = 0
	AudioPacket_BYTES_PER_SAMPLE_2       AudioPacket_BytesPerSample = 2
)

// Enum value maps for AudioPacket_BytesPerSample.
var (
	AudioPacket_BytesPerSample_name = map[int32]string{
		0: "BYTES_PER_SAMPLE_INVALID",
		2: "BYTES_PER_SAMPLE_2",
	}
	AudioPacket_BytesPerSample_value = map[string]int32{
		"BYTES_PER_SAMPLE_INVALID": 0,
		"BYTES_PER_SAMPLE_2":       2,
	}
)

func (x AudioPacket_BytesPerSample) Enum() *AudioPacket_BytesPerSample {
	p := new(AudioPacket_BytesPerSample)
	*p = x
	return p
}

func (x AudioPacket_BytesPerSample) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioPacket_BytesPerSample) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[9].Descriptor()
}

func (AudioPacket_BytesPerSample) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[9]
}

func (x AudioPacket_BytesPerSample) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioPacket_BytesPerSample.Descriptor instead.
func (AudioPacket_BytesPerSample) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{14, 1}
}

type AudioPacket_Channels int32

const (
	AudioPacket_CHANNELS_INVALID  AudioPacket_Channels = 0
	AudioPacket_CHANNELS_MONO     AudioPacket_Channels = 1
	AudioPacket_CHANNELS_STEREO   AudioPacket_Channels = 2
	AudioPacket_CHANNELS_SURROUND AudioPacket_Channels = 3
	AudioPacket_CHANNELS_4_0      AudioPacket_Channels = 4
	AudioPacket_CHANNELS_4_1      AudioPacket_Channels = 5
	AudioPacket_CHANNELS_5_1      AudioPacket_Channels = 6
	AudioPacket_CHANNELS_6_1      AudioPacket_Channels = 7
	AudioPacket_CHANNELS_7_1      AudioPacket_Channels = 8
)

// Enum value maps for AudioPacket_Channels.
var (
	AudioPacket_Channels_name = map[int32]string{
		0: "CHANNELS_INVALID",
		1: "CHANNELS_MONO",
		2: "CHANNELS_STEREO",
		3: "CHANNELS_SURROUND",
		4: "CHANNELS_4_0",
		5: "CHANNELS_4_1",
		6: "CHANNELS_5_1",
		7: "CHANNELS_6_1",
		8: "CHANNELS_7_1",
	}
	AudioPacket_Channels_value = map[string]int32{
		"CHANNELS_INVALID":  0,
		"CHANNELS_MONO":     1,
		"CHANNELS_STEREO":   2,
		"CHANNELS_SURROUND": 3,
		"CHANNELS_4_0":      4,
		"CHANNELS_4_1":      5,
		"CHANNELS_5_1":      6,
		"CHANNELS_6_1":      7,
		"CHANNELS_7_1":      8,
	}
)

func (x AudioPacket_Channels) Enum() *AudioPacket_Channels {
	p := new(AudioPacket_Channels)
	*p = x
	return p
}

func (x AudioPacket_Channels) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioPacket_Channels) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[10].Descriptor()
}

func (AudioPacket_Channels) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[10]
}

func (x AudioPacket_Channels) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioPacket_Channels.Descriptor instead.
func (AudioPacket_Channels) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{14, 2}
}

type PowerControl_Action int32

const (
	PowerControl_ACTION_UNKNOWN          PowerControl_Action = 0
	PowerControl_ACTION_SHUTDOWN         PowerControl_Action = 1
	PowerControl_ACTION_REBOOT           PowerControl_Action = 2
	PowerControl_ACTION_LOGOFF           PowerControl_Action = 3
	PowerControl_ACTION_LOCK             PowerControl_Action = 4
	PowerControl_ACTION_REBOOT_SAFE_MODE PowerControl_Action = 5
)

// Enum value maps for PowerControl_Action.
var (
	PowerControl_Action_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_SHUTDOWN",
		2: "ACTION_REBOOT",
		3: "ACTION_LOGOFF",
		4: "ACTION_LOCK",
		5: "ACTION_REBOOT_SAFE_MODE",
	}
	PowerControl_Action_value = map[string]int32{
		"ACTION_UNKNOWN":          0,
		"ACTION_SHUTDOWN":         1,
		"ACTION_REBOOT":           2,
		"ACTION_LOGOFF":           3,
		"ACTION_LOCK":             4,
		"ACTION_REBOOT_SAFE_MODE": 5,
	}
)

func (x PowerControl_Action) Enum() *PowerControl_Action {
	p := new(PowerControl_Action)
	*p = x
	return p
}

func (x PowerControl_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerControl_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[11].Descriptor()
}

func (PowerControl_Action) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[11]
}

func (x PowerControl_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerControl_Action.Descriptor instead.
func (PowerControl_Action) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{19, 0}
}

type VideoRecording_Action int32

const (
	VideoRecording_ACTION_UNKNOWN VideoRecording_Action = 0
	VideoRecording_ACTION_STARTED VideoRecording_Action = 1
	VideoRecording_ACTION_STOPPED VideoRecording_Action = 2
)

// Enum value maps for VideoRecording_Action.
var (
	VideoRecording_Action_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_STARTED",
		2: "ACTION_STOPPED",
	}
	VideoRecording_Action_value = map[string]int32{
		"ACTION_UNKNOWN": 0,
		"ACTION_STARTED": 1,
		"ACTION_STOPPED": 2,
	}
)

func (x VideoRecording_Action) Enum() *VideoRecording_Action {
	p := new(VideoRecording_Action)
	*p = x
	return p
}

func (x VideoRecording_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoRecording_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[12].Descriptor()
}

func (VideoRecording_Action) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[12]
}

func (x VideoRecording_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoRecording_Action.Descriptor instead.
func (VideoRecording_Action) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{20, 0}
}

type ScreenType_Type int32

const (
	ScreenType_TYPE_UNKNOWN ScreenType_Type = 0
	ScreenType_TYPE_DESKTOP ScreenType_Type = 1
	ScreenType_TYPE_LOCK    ScreenType_Type = 2
	ScreenType_TYPE_LOGIN   ScreenType_Type = 3
	ScreenType_TYPE_OTHER   ScreenType_Type = 4
)

// Enum value maps for ScreenType_Type.
var (
	ScreenType_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_DESKTOP",
		2: "TYPE_LOCK",
		3: "TYPE_LOGIN",
		4: "TYPE_OTHER",
	}
	ScreenType_Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"TYPE_DESKTOP": 1,
		"TYPE_LOCK":    2,
		"TYPE_LOGIN":   3,
		"TYPE_OTHER":   4,
	}
)

func (x ScreenType_Type) Enum() *ScreenType_Type {
	p := new(ScreenType_Type)
	*p = x
	return p
}

func (x ScreenType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScreenType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[13].Descriptor()
}

func (ScreenType_Type) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[13]
}

func (x ScreenType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScreenType_Type.Descriptor instead.
func (ScreenType_Type) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{21, 0}
}

type Capabilities_OsType int32

const (
	Capabilities_OS_TYPE_WINDOWS Capabilities_OsType = 0
	Capabilities_OS_TYPE_LINUX   Capabilities_OsType = 1
	Capabilities_OS_TYPE_MACOSX  Capabilities_OsType = 2
)

// Enum value maps for Capabilities_OsType.
var (
	Capabilities_OsType_name = map[int32]string{
		0: "OS_TYPE_WINDOWS",
		1: "OS_TYPE_LINUX",
		2: "OS_TYPE_MACOSX",
	}
	Capabilities_OsType_value = map[string]int32{
		"OS_TYPE_WINDOWS": 0,
		"OS_TYPE_LINUX":   1,
		"OS_TYPE_MACOSX":  2,
	}
)

func (x Capabilities_OsType) Enum() *Capabilities_OsType {
	p := new(Capabilities_OsType)
	*p = x
	return p
}

func (x Capabilities_OsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capabilities_OsType) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_proto_enumTypes[14].Descriptor()
}

func (Capabilities_OsType) Type() protoreflect.EnumType {
	return &file_desktop_proto_enumTypes[14]
}

func (x Capabilities_OsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capabilities_OsType.Descriptor instead.
func (Capabilities_OsType) EnumDescriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{22, 0}
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_desktop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_desktop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{1}
}

func (x *Size) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Size) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_desktop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{2}
}

func (x *Rect) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rect) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rect) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rect) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type PixelFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BitsPerPixel  uint32                 `protobuf:"varint,1,opt,name=bits_per_pixel,json=bitsPerPixel,proto3" json:"bits_per_pixel,omitempty"`
	RedMax        uint32                 `protobuf:"varint,2,opt,name=red_max,json=redMax,proto3" json:"red_max,omitempty"`
	GreenMax      uint32                 `protobuf:"varint,3,opt,name=green_max,json=greenMax,proto3" json:"green_max,omitempty"`
	BlueMax       uint32                 `protobuf:"varint,4,opt,name=blue_max,json=blueMax,proto3" json:"blue_max,omitempty"`
	RedShift      uint32                 `protobuf:"varint,5,opt,name=red_shift,json=redShift,proto3" json:"red_shift,omitempty"`
	GreenShift    uint32                 `protobuf:"varint,6,opt,name=green_shift,json=greenShift,proto3" json:"green_shift,omitempty"`
	BlueShift     uint32                 `protobuf:"varint,7,opt,name=blue_shift,json=blueShift,proto3" json:"blue_shift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixelFormat) Reset() {
	*x = PixelFormat{}
	mi := &file_desktop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixelFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelFormat) ProtoMessage() {}

func (x *PixelFormat) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixelFormat.ProtoReflect.Descriptor instead.
func (*PixelFormat) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{3}
}

func (x *PixelFormat) GetBitsPerPixel() uint32 {
	if x != nil {
		return x.BitsPerPixel
	}
	return 0
}

func (x *PixelFormat) GetRedMax() uint32 {
	if x != nil {
		return x.RedMax
	}
	return 0
}

func (x *PixelFormat) GetGreenMax() uint32 {
	if x != nil {
		return x.GreenMax
	}
	return 0
}

func (x *PixelFormat) GetBlueMax() uint32 {
	if x != nil {
		return x.BlueMax
	}
	return 0
}

func (x *PixelFormat) GetRedShift() uint32 {
	if x != nil {
		return x.RedShift
	}
	return 0
}

func (x *PixelFormat) GetGreenShift() uint32 {
	if x != nil {
		return x.GreenShift
	}
	return 0
}

func (x *PixelFormat) GetBlueShift() uint32 {
	if x != nil {
		return x.BlueShift
	}
	return 0
}

type KeyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsbKeycode    uint32                 `protobuf:"varint,1,opt,name=usb_keycode,json=usbKeycode,proto3" json:"usb_keycode,omitempty"`
	Flags         uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEvent) Reset() {
	*x = KeyEvent{}
	mi := &file_desktop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEvent) ProtoMessage() {}

func (x *KeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEvent.ProtoReflect.Descriptor instead.
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{4}
}

func (x *KeyEvent) GetUsbKeycode() uint32 {
	if x != nil {
		return x.UsbKeycode
	}
	return 0
}

func (x *KeyEvent) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type TextEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEvent) Reset() {
	*x = TextEvent{}
	mi := &file_desktop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEvent) ProtoMessage() {}

func (x *TextEvent) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEvent.ProtoReflect.Descriptor instead.
func (*TextEvent) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{5}
}

func (x *TextEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MouseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mask          uint32                 `protobuf:"varint,1,opt,name=mask,proto3" json:"mask,omitempty"` // Button mask.
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`       // x position.
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`       // y position.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseEvent) Reset() {
	*x = MouseEvent{}
	mi := &file_desktop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseEvent) ProtoMessage() {}

func (x *MouseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseEvent.ProtoReflect.Descriptor instead.
func (*MouseEvent) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{6}
}

func (x *MouseEvent) GetMask() uint32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

func (x *MouseEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type TouchEventPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID for the touch point.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The absolute position of the touch point. These values on-the-wire are host physical pixel
	// coordinates: the top-left monitor on the system always starts from (0, 0).
	X float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	// The size of the touch point, used to aid hit-testing. Scaled to match the size on host.
	RadiusX float32 `protobuf:"fixed32,4,opt,name=radius_x,json=radiusX,proto3" json:"radius_x,omitempty"`
	RadiusY float32 `protobuf:"fixed32,5,opt,name=radius_y,json=radiusY,proto3" json:"radius_y,omitempty"`
	// Angle in degrees from the y-axis of the touch point.
	Angle float32 `protobuf:"fixed32,6,opt,name=angle,proto3" json:"angle,omitempty"`
	// The pressure of the touch point. The value should be in [0.0, 1.0].
	Pressure      float32 `protobuf:"fixed32,7,opt,name=pressure,proto3" json:"pressure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchEventPoint) Reset() {
	*x = TouchEventPoint{}
	mi := &file_desktop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchEventPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchEventPoint) ProtoMessage() {}

func (x *TouchEventPoint) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchEventPoint.ProtoReflect.Descriptor instead.
func (*TouchEventPoint) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{7}
}

func (x *TouchEventPoint) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TouchEventPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TouchEventPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TouchEventPoint) GetRadiusX() float32 {
	if x != nil {
		return x.RadiusX
	}
	return 0
}

func (x *TouchEventPoint) GetRadiusY() float32 {
	if x != nil {
		return x.RadiusY
	}
	return 0
}

func (x *TouchEventPoint) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *TouchEventPoint) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

type TouchEvent struct {
	state     protoimpl.MessageState    `protogen:"open.v1"`
	EventType TouchEvent_TouchEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=proto.desktop.TouchEvent_TouchEventType" json:"event_type,omitempty"`
	// Only the changed touch points are added to this field.
	// Given the existing touch point APIs (e.g. Android and PPAPI)
	// for START, END, and CANCEL events the size of this field will typically be 1, but for MOVE
	// events it is likely to have multiple points.
	TouchPoints   []*TouchEventPoint `protobuf:"bytes,2,rep,name=touch_points,json=touchPoints,proto3" json:"touch_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchEvent) Reset() {
	*x = TouchEvent{}
	mi := &file_desktop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchEvent) ProtoMessage() {}

func (x *TouchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchEvent.ProtoReflect.Descriptor instead.
func (*TouchEvent) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{8}
}

func (x *TouchEvent) GetEventType() TouchEvent_TouchEventType {
	if x != nil {
		return x.EventType
	}
	return TouchEvent_TOUCH_POINT_UNKNOWN
}

func (x *TouchEvent) GetTouchPoints() []*TouchEventPoint {
	if x != nil {
		return x.TouchPoints
	}
	return nil
}

type ClipboardEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipboardEvent) Reset() {
	*x = ClipboardEvent{}
	mi := &file_desktop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipboardEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardEvent) ProtoMessage() {}

func (x *ClipboardEvent) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardEvent.ProtoReflect.Descriptor instead.
func (*ClipboardEvent) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{9}
}

func (x *ClipboardEvent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ClipboardEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CursorShape struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// We use only the first byte in this field.
	// If bit 7 is set to 1, then bits 0-4 contain the cursor index in the cache.
	// If bit 7 is not set, then the cursor image is received.
	// If bit 6 is set to 1, then the command to reset the contents of the cache
	// is received, and bits 0-4 contain a new cache size.
	// Bit 5 is reserved.
	Flags uint32 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	// Width, height (in screen pixels) of the cursor.
	Width  int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// X,Y coordinates (relative to upper-left corner) of the cursor hotspot.
	HotspotX int32 `protobuf:"varint,4,opt,name=hotspot_x,json=hotspotX,proto3" json:"hotspot_x,omitempty"`
	HotspotY int32 `protobuf:"varint,5,opt,name=hotspot_y,json=hotspotY,proto3" json:"hotspot_y,omitempty"`
	// Cursor pixmap data in 32-bit BGRA format compressed with Zstd.
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// Screen DPI for current cursor.
	DpiX          int32 `protobuf:"varint,7,opt,name=dpi_x,json=dpiX,proto3" json:"dpi_x,omitempty"`
	DpiY          int32 `protobuf:"varint,8,opt,name=dpi_y,json=dpiY,proto3" json:"dpi_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorShape) Reset() {
	*x = CursorShape{}
	mi := &file_desktop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorShape) ProtoMessage() {}

func (x *CursorShape) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorShape.ProtoReflect.Descriptor instead.
func (*CursorShape) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{10}
}

func (x *CursorShape) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *CursorShape) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CursorShape) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CursorShape) GetHotspotX() int32 {
	if x != nil {
		return x.HotspotX
	}
	return 0
}

func (x *CursorShape) GetHotspotY() int32 {
	if x != nil {
		return x.HotspotY
	}
	return 0
}

func (x *CursorShape) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CursorShape) GetDpiX() int32 {
	if x != nil {
		return x.DpiX
	}
	return 0
}

func (x *CursorShape) GetDpiY() int32 {
	if x != nil {
		return x.DpiY
	}
	return 0
}

type CursorPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPosition) Reset() {
	*x = CursorPosition{}
	mi := &file_desktop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPosition) ProtoMessage() {}

func (x *CursorPosition) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPosition.ProtoReflect.Descriptor instead.
func (*CursorPosition) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{11}
}

func (x *CursorPosition) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CursorPosition) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type VideoPacketFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoRect     *Rect                  `protobuf:"bytes,1,opt,name=video_rect,json=videoRect,proto3" json:"video_rect,omitempty"`
	PixelFormat   *PixelFormat           `protobuf:"bytes,2,opt,name=pixel_format,json=pixelFormat,proto3" json:"pixel_format,omitempty"`
	ScreenSize    *Size                  `protobuf:"bytes,3,opt,name=screen_size,json=screenSize,proto3" json:"screen_size,omitempty"`
	CapturerType  uint32                 `protobuf:"varint,4,opt,name=capturer_type,json=capturerType,proto3" json:"capturer_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPacketFormat) Reset() {
	*x = VideoPacketFormat{}
	mi := &file_desktop_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPacketFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPacketFormat) ProtoMessage() {}

func (x *VideoPacketFormat) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPacketFormat.ProtoReflect.Descriptor instead.
func (*VideoPacketFormat) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{12}
}

func (x *VideoPacketFormat) GetVideoRect() *Rect {
	if x != nil {
		return x.VideoRect
	}
	return nil
}

func (x *VideoPacketFormat) GetPixelFormat() *PixelFormat {
	if x != nil {
		return x.PixelFormat
	}
	return nil
}

func (x *VideoPacketFormat) GetScreenSize() *Size {
	if x != nil {
		return x.ScreenSize
	}
	return nil
}

func (x *VideoPacketFormat) GetCapturerType() uint32 {
	if x != nil {
		return x.CapturerType
	}
	return 0
}

type VideoPacket struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Encoding VideoEncoding          `protobuf:"varint,1,opt,name=encoding,proto3,enum=proto.desktop.VideoEncoding" json:"encoding,omitempty"`
	// If the screen size or the pixel format has changed, the field must be filled.
	Format *VideoPacketFormat `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// The list of changed rectangles (areas) of the screen.
	DirtyRect []*Rect `protobuf:"bytes,3,rep,name=dirty_rect,json=dirtyRect,proto3" json:"dirty_rect,omitempty"`
	// Video packet data.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// If there is no error, then it takes the value VIDEO_ERROR_CODE_OK.
	// If the field has any other value, then all other fields are ignored.
	ErrorCode     VideoErrorCode `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3,enum=proto.desktop.VideoErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPacket) Reset() {
	*x = VideoPacket{}
	mi := &file_desktop_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPacket) ProtoMessage() {}

func (x *VideoPacket) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPacket.ProtoReflect.Descriptor instead.
func (*VideoPacket) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{13}
}

func (x *VideoPacket) GetEncoding() VideoEncoding {
	if x != nil {
		return x.Encoding
	}
	return VideoEncoding_VIDEO_ENCODING_UNKNOWN
}

func (x *VideoPacket) GetFormat() *VideoPacketFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *VideoPacket) GetDirtyRect() []*Rect {
	if x != nil {
		return x.DirtyRect
	}
	return nil
}

func (x *VideoPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoPacket) GetErrorCode() VideoErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return VideoErrorCode_VIDEO_ERROR_CODE_OK
}

type AudioPacket struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Timestamp      int32                      `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data           [][]byte                   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Encoding       AudioEncoding              `protobuf:"varint,3,opt,name=encoding,proto3,enum=proto.desktop.AudioEncoding" json:"encoding,omitempty"`
	SamplingRate   AudioPacket_SamplingRate   `protobuf:"varint,4,opt,name=sampling_rate,json=samplingRate,proto3,enum=proto.desktop.AudioPacket_SamplingRate" json:"sampling_rate,omitempty"`
	BytesPerSample AudioPacket_BytesPerSample `protobuf:"varint,5,opt,name=bytes_per_sample,json=bytesPerSample,proto3,enum=proto.desktop.AudioPacket_BytesPerSample" json:"bytes_per_sample,omitempty"`
	Channels       AudioPacket_Channels       `protobuf:"varint,6,opt,name=channels,proto3,enum=proto.desktop.AudioPacket_Channels" json:"channels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AudioPacket) Reset() {
	*x = AudioPacket{}
	mi := &file_desktop_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPacket) ProtoMessage() {}

func (x *AudioPacket) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPacket.ProtoReflect.Descriptor instead.
func (*AudioPacket) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{14}
}

func (x *AudioPacket) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AudioPacket) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioPacket) GetEncoding() AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return AudioEncoding_AUDIO_ENCODING_UNKNOWN
}

func (x *AudioPacket) GetSamplingRate() AudioPacket_SamplingRate {
	if x != nil {
		return x.SamplingRate
	}
	return AudioPacket_SAMPLING_RATE_INVALID
}

func (x *AudioPacket) GetBytesPerSample() AudioPacket_BytesPerSample {
	if x != nil {
		return x.BytesPerSample
	}
	return AudioPacket_BYTES_PER_SAMPLE_INVALID
}

func (x *AudioPacket) GetChannels() AudioPacket_Channels {
	if x != nil {
		return x.Channels
	}
	return AudioPacket_CHANNELS_INVALID
}

type Extension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_desktop_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{15}
}

func (x *Extension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Extension) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Extension name: "select_screen"
// Sent by client to host for screen or screen resolution selection.
type Screen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Position      *Point                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Resolution    *Size                  `protobuf:"bytes,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Dpi           *Point                 `protobuf:"bytes,5,opt,name=dpi,proto3" json:"dpi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Screen) Reset() {
	*x = Screen{}
	mi := &file_desktop_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{16}
}

func (x *Screen) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Screen) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Screen) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Screen) GetResolution() *Size {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *Screen) GetDpi() *Point {
	if x != nil {
		return x.Dpi
	}
	return nil
}

// Extension name: "select_screen"
// Sent by host to client. Contains a list of screens on the host.
type ScreenList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screen        []*Screen              `protobuf:"bytes,1,rep,name=screen,proto3" json:"screen,omitempty"`                                     // List of screens on the remote computer.
	CurrentScreen int64                  `protobuf:"varint,2,opt,name=current_screen,json=currentScreen,proto3" json:"current_screen,omitempty"` // ID of current screen.
	PrimaryScreen int64                  `protobuf:"varint,3,opt,name=primary_screen,json=primaryScreen,proto3" json:"primary_screen,omitempty"` // ID of primary screen.
	Resolution    []*Size                `protobuf:"bytes,4,rep,name=resolution,proto3" json:"resolution,omitempty"`                             // List of resolutions for current screen.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenList) Reset() {
	*x = ScreenList{}
	mi := &file_desktop_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenList) ProtoMessage() {}

func (x *ScreenList) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenList.ProtoReflect.Descriptor instead.
func (*ScreenList) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{17}
}

func (x *ScreenList) GetScreen() []*Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *ScreenList) GetCurrentScreen() int64 {
	if x != nil {
		return x.CurrentScreen
	}
	return 0
}

func (x *ScreenList) GetPrimaryScreen() int64 {
	if x != nil {
		return x.PrimaryScreen
	}
	return 0
}

func (x *ScreenList) GetResolution() []*Size {
	if x != nil {
		return x.Resolution
	}
	return nil
}

// Extension name: "video_pause", "audio_pause"
// Sent by client to host.
type Pause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pause) Reset() {
	*x = Pause{}
	mi := &file_desktop_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{18}
}

func (x *Pause) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

// Extension name: "power_control"
// Sent by client to host.
type PowerControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        PowerControl_Action    `protobuf:"varint,1,opt,name=action,proto3,enum=proto.desktop.PowerControl_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerControl) Reset() {
	*x = PowerControl{}
	mi := &file_desktop_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerControl) ProtoMessage() {}

func (x *PowerControl) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerControl.ProtoReflect.Descriptor instead.
func (*PowerControl) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{19}
}

func (x *PowerControl) GetAction() PowerControl_Action {
	if x != nil {
		return x.Action
	}
	return PowerControl_ACTION_UNKNOWN
}

// Extension name: "video_recording"
// Sent by host to client and by client to host.
type VideoRecording struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        VideoRecording_Action  `protobuf:"varint,1,opt,name=action,proto3,enum=proto.desktop.VideoRecording_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRecording) Reset() {
	*x = VideoRecording{}
	mi := &file_desktop_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRecording) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRecording) ProtoMessage() {}

func (x *VideoRecording) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRecording.ProtoReflect.Descriptor instead.
func (*VideoRecording) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{20}
}

func (x *VideoRecording) GetAction() VideoRecording_Action {
	if x != nil {
		return x.Action
	}
	return VideoRecording_ACTION_UNKNOWN
}

// Extension name: "screen_type"
// Sent by host to client.
type ScreenType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ScreenType_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=proto.desktop.ScreenType_Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenType) Reset() {
	*x = ScreenType{}
	mi := &file_desktop_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenType) ProtoMessage() {}

func (x *ScreenType) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenType.ProtoReflect.Descriptor instead.
func (*ScreenType) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{21}
}

func (x *ScreenType) GetType() ScreenType_Type {
	if x != nil {
		return x.Type
	}
	return ScreenType_TYPE_UNKNOWN
}

func (x *ScreenType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Capabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Extensions     string                 `protobuf:"bytes,1,opt,name=extensions,proto3" json:"extensions,omitempty"`
	VideoEncodings uint32                 `protobuf:"varint,2,opt,name=video_encodings,json=videoEncodings,proto3" json:"video_encodings,omitempty"`
	AudioEncodings uint32                 `protobuf:"varint,3,opt,name=audio_encodings,json=audioEncodings,proto3" json:"audio_encodings,omitempty"`
	OsType         Capabilities_OsType    `protobuf:"varint,4,opt,name=os_type,json=osType,proto3,enum=proto.desktop.Capabilities_OsType" json:"os_type,omitempty"`
	Flag           []*Capabilities_Flag   `protobuf:"bytes,5,rep,name=flag,proto3" json:"flag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_desktop_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{22}
}

func (x *Capabilities) GetExtensions() string {
	if x != nil {
		return x.Extensions
	}
	return ""
}

func (x *Capabilities) GetVideoEncodings() uint32 {
	if x != nil {
		return x.VideoEncodings
	}
	return 0
}

func (x *Capabilities) GetAudioEncodings() uint32 {
	if x != nil {
		return x.AudioEncodings
	}
	return 0
}

func (x *Capabilities) GetOsType() Capabilities_OsType {
	if x != nil {
		return x.OsType
	}
	return Capabilities_OS_TYPE_WINDOWS
}

func (x *Capabilities) GetFlag() []*Capabilities_Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	VideoEncoding VideoEncoding          `protobuf:"varint,2,opt,name=video_encoding,json=videoEncoding,proto3,enum=proto.desktop.VideoEncoding" json:"video_encoding,omitempty"`
	PixelFormat   *PixelFormat           `protobuf:"bytes,3,opt,name=pixel_format,json=pixelFormat,proto3" json:"pixel_format,omitempty"`
	// Field 4 is deprecated.
	CompressRatio uint32 `protobuf:"varint,5,opt,name=compress_ratio,json=compressRatio,proto3" json:"compress_ratio,omitempty"`
	// Field 6 is deprecated.
	AudioEncoding AudioEncoding `protobuf:"varint,7,opt,name=audio_encoding,json=audioEncoding,proto3,enum=proto.desktop.AudioEncoding" json:"audio_encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_desktop_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{23}
}

func (x *Config) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Config) GetVideoEncoding() VideoEncoding {
	if x != nil {
		return x.VideoEncoding
	}
	return VideoEncoding_VIDEO_ENCODING_UNKNOWN
}

func (x *Config) GetPixelFormat() *PixelFormat {
	if x != nil {
		return x.PixelFormat
	}
	return nil
}

func (x *Config) GetCompressRatio() uint32 {
	if x != nil {
		return x.CompressRatio
	}
	return 0
}

func (x *Config) GetAudioEncoding() AudioEncoding {
	if x != nil {
		return x.AudioEncoding
	}
	return AudioEncoding_AUDIO_ENCODING_UNKNOWN
}

type HostToClient struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoPacket    *VideoPacket           `protobuf:"bytes,1,opt,name=video_packet,json=videoPacket,proto3" json:"video_packet,omitempty"`
	AudioPacket    *AudioPacket           `protobuf:"bytes,2,opt,name=audio_packet,json=audioPacket,proto3" json:"audio_packet,omitempty"`
	CursorShape    *CursorShape           `protobuf:"bytes,3,opt,name=cursor_shape,json=cursorShape,proto3" json:"cursor_shape,omitempty"`
	ClipboardEvent *ClipboardEvent        `protobuf:"bytes,4,opt,name=clipboard_event,json=clipboardEvent,proto3" json:"clipboard_event,omitempty"`
	Extension      *Extension             `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	Capabilities   *Capabilities          `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	CursorPosition *CursorPosition        `protobuf:"bytes,7,opt,name=cursor_position,json=cursorPosition,proto3" json:"cursor_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostToClient) Reset() {
	*x = HostToClient{}
	mi := &file_desktop_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostToClient) ProtoMessage() {}

func (x *HostToClient) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostToClient.ProtoReflect.Descriptor instead.
func (*HostToClient) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{24}
}

func (x *HostToClient) GetVideoPacket() *VideoPacket {
	if x != nil {
		return x.VideoPacket
	}
	return nil
}

func (x *HostToClient) GetAudioPacket() *AudioPacket {
	if x != nil {
		return x.AudioPacket
	}
	return nil
}

func (x *HostToClient) GetCursorShape() *CursorShape {
	if x != nil {
		return x.CursorShape
	}
	return nil
}

func (x *HostToClient) GetClipboardEvent() *ClipboardEvent {
	if x != nil {
		return x.ClipboardEvent
	}
	return nil
}

func (x *HostToClient) GetExtension() *Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *HostToClient) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HostToClient) GetCursorPosition() *CursorPosition {
	if x != nil {
		return x.CursorPosition
	}
	return nil
}

type ClientToHost struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MouseEvent     *MouseEvent            `protobuf:"bytes,1,opt,name=mouse_event,json=mouseEvent,proto3" json:"mouse_event,omitempty"`
	KeyEvent       *KeyEvent              `protobuf:"bytes,2,opt,name=key_event,json=keyEvent,proto3" json:"key_event,omitempty"`
	TouchEvent     *TouchEvent            `protobuf:"bytes,3,opt,name=touch_event,json=touchEvent,proto3" json:"touch_event,omitempty"`
	TextEvent      *TextEvent             `protobuf:"bytes,4,opt,name=text_event,json=textEvent,proto3" json:"text_event,omitempty"`
	ClipboardEvent *ClipboardEvent        `protobuf:"bytes,5,opt,name=clipboard_event,json=clipboardEvent,proto3" json:"clipboard_event,omitempty"`
	Extension      *Extension             `protobuf:"bytes,6,opt,name=extension,proto3" json:"extension,omitempty"`
	Config         *Config                `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	AudioPacket    *AudioPacket           `protobuf:"bytes,8,opt,name=audio_packet,json=audioPacket,proto3" json:"audio_packet,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientToHost) Reset() {
	*x = ClientToHost{}
	mi := &file_desktop_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToHost) ProtoMessage() {}

func (x *ClientToHost) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToHost.ProtoReflect.Descriptor instead.
func (*ClientToHost) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{25}
}

func (x *ClientToHost) GetMouseEvent() *MouseEvent {
	if x != nil {
		return x.MouseEvent
	}
	return nil
}

func (x *ClientToHost) GetKeyEvent() *KeyEvent {
	if x != nil {
		return x.KeyEvent
	}
	return nil
}

func (x *ClientToHost) GetTouchEvent() *TouchEvent {
	if x != nil {
		return x.TouchEvent
	}
	return nil
}

func (x *ClientToHost) GetTextEvent() *TextEvent {
	if x != nil {
		return x.TextEvent
	}
	return nil
}

func (x *ClientToHost) GetClipboardEvent() *ClipboardEvent {
	if x != nil {
		return x.ClipboardEvent
	}
	return nil
}

func (x *ClientToHost) GetExtension() *Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *ClientToHost) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ClientToHost) GetAudioPacket() *AudioPacket {
	if x != nil {
		return x.AudioPacket
	}
	return nil
}

type ClipboardEvent_FileList struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	File          []*ClipboardEvent_FileList_File `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipboardEvent_FileList) Reset() {
	*x = ClipboardEvent_FileList{}
	mi := &file_desktop_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipboardEvent_FileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardEvent_FileList) ProtoMessage() {}

func (x *ClipboardEvent_FileList) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardEvent_FileList.ProtoReflect.Descriptor instead.
func (*ClipboardEvent_FileList) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ClipboardEvent_FileList) GetFile() []*ClipboardEvent_FileList_File {
	if x != nil {
		return x.File
	}
	return nil
}

type ClipboardEvent_FileList_File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	AccessTime    int64                  `protobuf:"varint,5,opt,name=access_time,json=accessTime,proto3" json:"access_time,omitempty"`
	ModifyTime    int64                  `protobuf:"varint,6,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipboardEvent_FileList_File) Reset() {
	*x = ClipboardEvent_FileList_File{}
	mi := &file_desktop_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipboardEvent_FileList_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardEvent_FileList_File) ProtoMessage() {}

func (x *ClipboardEvent_FileList_File) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardEvent_FileList_File.ProtoReflect.Descriptor instead.
func (*ClipboardEvent_FileList_File) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{9, 0, 0}
}

func (x *ClipboardEvent_FileList_File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ClipboardEvent_FileList_File) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *ClipboardEvent_FileList_File) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ClipboardEvent_FileList_File) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ClipboardEvent_FileList_File) GetAccessTime() int64 {
	if x != nil {
		return x.AccessTime
	}
	return 0
}

func (x *ClipboardEvent_FileList_File) GetModifyTime() int64 {
	if x != nil {
		return x.ModifyTime
	}
	return 0
}

type Capabilities_Flag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities_Flag) Reset() {
	*x = Capabilities_Flag{}
	mi := &file_desktop_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities_Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities_Flag) ProtoMessage() {}

func (x *Capabilities_Flag) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities_Flag.ProtoReflect.Descriptor instead.
func (*Capabilities_Flag) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{22, 0}
}

func (x *Capabilities_Flag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capabilities_Flag) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

var File_desktop_proto protoreflect.FileDescriptor

const file_desktop_proto_rawDesc = "" +
	"\n" +
	"\rdesktop.proto\x12\rproto.desktop\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"4\n" +
	"\x04Size\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"P\n" +
	"\x04Rect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\xe1\x01\n" +
	"\vPixelFormat\x12$\n" +
	"\x0ebits_per_pixel\x18\x01 \x01(\rR\fbitsPerPixel\x12\x17\n" +
	"\ared_max\x18\x02 \x01(\rR\x06redMax\x12\x1b\n" +
	"\tgreen_max\x18\x03 \x01(\rR\bgreenMax\x12\x19\n" +
	"\bblue_max\x18\x04 \x01(\rR\ablueMax\x12\x1b\n" +
	"\tred_shift\x18\x05 \x01(\rR\bredShift\x12\x1f\n" +
	"\vgreen_shift\x18\x06 \x01(\rR\n" +
	"greenShift\x12\x1d\n" +
	"\n" +
	"blue_shift\x18\a \x01(\rR\tblueShift\"\x7f\n" +
	"\bKeyEvent\x12\x1f\n" +
	"\vusb_keycode\x18\x01 \x01(\rR\n" +
	"usbKeycode\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\"<\n" +
	"\x05Flags\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bCAPSLOCK\x10\x01\x12\v\n" +
	"\aNUMLOCK\x10\x02\x12\v\n" +
	"\aPRESSED\x10\x04\"\x1f\n" +
	"\tTextEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xcf\x01\n" +
	"\n" +
	"MouseEvent\x12\x12\n" +
	"\x04mask\x18\x01 \x01(\rR\x04mask\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\x90\x01\n" +
	"\n" +
	"ButtonMask\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\x0f\n" +
	"\vLEFT_BUTTON\x10\x01\x12\x11\n" +
	"\rMIDDLE_BUTTON\x10\x02\x12\x10\n" +
	"\fRIGHT_BUTTON\x10\x04\x12\f\n" +
	"\bWHEEL_UP\x10\b\x12\x0e\n" +
	"\n" +
	"WHEEL_DOWN\x10\x10\x12\x0f\n" +
	"\vBACK_BUTTON\x10 \x12\x12\n" +
	"\x0eFORWARD_BUTTON\x10@\"\xa5\x01\n" +
	"\x0fTouchEventPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x19\n" +
	"\bradius_x\x18\x04 \x01(\x02R\aradiusX\x12\x19\n" +
	"\bradius_y\x18\x05 \x01(\x02R\aradiusY\x12\x14\n" +
	"\x05angle\x18\x06 \x01(\x02R\x05angle\x12\x1a\n" +
	"\bpressure\x18\a \x01(\x02R\bpressure\"\x9e\x02\n" +
	"\n" +
	"TouchEvent\x12G\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2(.proto.desktop.TouchEvent.TouchEventTypeR\teventType\x12A\n" +
	"\ftouch_points\x18\x02 \x03(\v2\x1e.proto.desktop.TouchEventPointR\vtouchPoints\"\x83\x01\n" +
	"\x0eTouchEventType\x12\x17\n" +
	"\x13TOUCH_POINT_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11TOUCH_POINT_START\x10\x01\x12\x14\n" +
	"\x10TOUCH_POINT_MOVE\x10\x02\x12\x13\n" +
	"\x0fTOUCH_POINT_END\x10\x03\x12\x16\n" +
	"\x12TOUCH_POINT_CANCEL\x10\x04\"\xc3\x02\n" +
	"\x0eClipboardEvent\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1a\xff\x01\n" +
	"\bFileList\x12?\n" +
	"\x04file\x18\x01 \x03(\v2+.proto.desktop.ClipboardEvent.FileList.FileR\x04file\x1a\xb1\x01\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vaccess_time\x18\x05 \x01(\x03R\n" +
	"accessTime\x12\x1f\n" +
	"\vmodify_time\x18\x06 \x01(\x03R\n" +
	"modifyTime\"\xfc\x01\n" +
	"\vCursorShape\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1b\n" +
	"\thotspot_x\x18\x04 \x01(\x05R\bhotspotX\x12\x1b\n" +
	"\thotspot_y\x18\x05 \x01(\x05R\bhotspotY\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x13\n" +
	"\x05dpi_x\x18\a \x01(\x05R\x04dpiX\x12\x13\n" +
	"\x05dpi_y\x18\b \x01(\x05R\x04dpiY\"1\n" +
	"\x05Flags\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vRESET_CACHE\x10@\x12\n" +
	"\n" +
	"\x05CACHE\x10\x80\x01\",\n" +
	"\x0eCursorPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xe1\x01\n" +
	"\x11VideoPacketFormat\x122\n" +
	"\n" +
	"video_rect\x18\x01 \x01(\v2\x13.proto.desktop.RectR\tvideoRect\x12=\n" +
	"\fpixel_format\x18\x02 \x01(\v2\x1a.proto.desktop.PixelFormatR\vpixelFormat\x124\n" +
	"\vscreen_size\x18\x03 \x01(\v2\x13.proto.desktop.SizeR\n" +
	"screenSize\x12#\n" +
	"\rcapturer_type\x18\x04 \x01(\rR\fcapturerType\"\x87\x02\n" +
	"\vVideoPacket\x128\n" +
	"\bencoding\x18\x01 \x01(\x0e2\x1c.proto.desktop.VideoEncodingR\bencoding\x128\n" +
	"\x06format\x18\x02 \x01(\v2 .proto.desktop.VideoPacketFormatR\x06format\x122\n" +
	"\n" +
	"dirty_rect\x18\x03 \x03(\v2\x13.proto.desktop.RectR\tdirtyRect\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12<\n" +
	"\n" +
	"error_code\x18\x05 \x01(\x0e2\x1d.proto.desktop.VideoErrorCodeR\terrorCode\"\xfa\x05\n" +
	"\vAudioPacket\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x05R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x02 \x03(\fR\x04data\x128\n" +
	"\bencoding\x18\x03 \x01(\x0e2\x1c.proto.desktop.AudioEncodingR\bencoding\x12L\n" +
	"\rsampling_rate\x18\x04 \x01(\x0e2'.proto.desktop.AudioPacket.SamplingRateR\fsamplingRate\x12S\n" +
	"\x10bytes_per_sample\x18\x05 \x01(\x0e2).proto.desktop.AudioPacket.BytesPerSampleR\x0ebytesPerSample\x12?\n" +
	"\bchannels\x18\x06 \x01(\x0e2#.proto.desktop.AudioPacket.ChannelsR\bchannels\"\x96\x01\n" +
	"\fSamplingRate\x12\x19\n" +
	"\x15SAMPLING_RATE_INVALID\x10\x00\x12\x19\n" +
	"\x13SAMPLING_RATE_44100\x10\xc4\xd8\x02\x12\x19\n" +
	"\x13SAMPLING_RATE_48000\x10\x80\xf7\x02\x12\x19\n" +
	"\x13SAMPLING_RATE_96000\x10\x80\xee\x05\x12\x1a\n" +
	"\x14SAMPLING_RATE_192000\x10\x80\xdc\v\"F\n" +
	"\x0eBytesPerSample\x12\x1c\n" +
	"\x18BYTES_PER_SAMPLE_INVALID\x10\x00\x12\x16\n" +
	"\x12BYTES_PER_SAMPLE_2\x10\x02\"\xb9\x01\n" +
	"\bChannels\x12\x14\n" +
	"\x10CHANNELS_INVALID\x10\x00\x12\x11\n" +
	"\rCHANNELS_MONO\x10\x01\x12\x13\n" +
	"\x0fCHANNELS_STEREO\x10\x02\x12\x15\n" +
	"\x11CHANNELS_SURROUND\x10\x03\x12\x10\n" +
	"\fCHANNELS_4_0\x10\x04\x12\x10\n" +
	"\fCHANNELS_4_1\x10\x05\x12\x10\n" +
	"\fCHANNELS_5_1\x10\x06\x12\x10\n" +
	"\fCHANNELS_6_1\x10\a\x12\x10\n" +
	"\fCHANNELS_7_1\x10\b\"3\n" +
	"\tExtension\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xbd\x01\n" +
	"\x06Screen\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x120\n" +
	"\bposition\x18\x03 \x01(\v2\x14.proto.desktop.PointR\bposition\x123\n" +
	"\n" +
	"resolution\x18\x04 \x01(\v2\x13.proto.desktop.SizeR\n" +
	"resolution\x12&\n" +
	"\x03dpi\x18\x05 \x01(\v2\x14.proto.desktop.PointR\x03dpi\"\xbe\x01\n" +
	"\n" +
	"ScreenList\x12-\n" +
	"\x06screen\x18\x01 \x03(\v2\x15.proto.desktop.ScreenR\x06screen\x12%\n" +
	"\x0ecurrent_screen\x18\x02 \x01(\x03R\rcurrentScreen\x12%\n" +
	"\x0eprimary_screen\x18\x03 \x01(\x03R\rprimaryScreen\x123\n" +
	"\n" +
	"resolution\x18\x04 \x03(\v2\x13.proto.desktop.SizeR\n" +
	"resolution\"\x1f\n" +
	"\x05Pause\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\"\xd2\x01\n" +
	"\fPowerControl\x12:\n" +
	"\x06action\x18\x01 \x01(\x0e2\".proto.desktop.PowerControl.ActionR\x06action\"\x85\x01\n" +
	"\x06Action\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fACTION_SHUTDOWN\x10\x01\x12\x11\n" +
	"\rACTION_REBOOT\x10\x02\x12\x11\n" +
	"\rACTION_LOGOFF\x10\x03\x12\x0f\n" +
	"\vACTION_LOCK\x10\x04\x12\x1b\n" +
	"\x17ACTION_REBOOT_SAFE_MODE\x10\x05\"\x94\x01\n" +
	"\x0eVideoRecording\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.proto.desktop.VideoRecording.ActionR\x06action\"D\n" +
	"\x06Action\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eACTION_STARTED\x10\x01\x12\x12\n" +
	"\x0eACTION_STOPPED\x10\x02\"\xaf\x01\n" +
	"\n" +
	"ScreenType\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.proto.desktop.ScreenType.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"Y\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fTYPE_DESKTOP\x10\x01\x12\r\n" +
	"\tTYPE_LOCK\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_LOGIN\x10\x03\x12\x0e\n" +
	"\n" +
	"TYPE_OTHER\x10\x04\"\xeb\x02\n" +
	"\fCapabilities\x12\x1e\n" +
	"\n" +
	"extensions\x18\x01 \x01(\tR\n" +
	"extensions\x12'\n" +
	"\x0fvideo_encodings\x18\x02 \x01(\rR\x0evideoEncodings\x12'\n" +
	"\x0faudio_encodings\x18\x03 \x01(\rR\x0eaudioEncodings\x12;\n" +
	"\aos_type\x18\x04 \x01(\x0e2\".proto.desktop.Capabilities.OsTypeR\x06osType\x124\n" +
	"\x04flag\x18\x05 \x03(\v2 .proto.desktop.Capabilities.FlagR\x04flag\x1a0\n" +
	"\x04Flag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"D\n" +
	"\x06OsType\x12\x13\n" +
	"\x0fOS_TYPE_WINDOWS\x10\x00\x12\x11\n" +
	"\rOS_TYPE_LINUX\x10\x01\x12\x12\n" +
	"\x0eOS_TYPE_MACOSX\x10\x02\"\x8e\x02\n" +
	"\x06Config\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\x12C\n" +
	"\x0evideo_encoding\x18\x02 \x01(\x0e2\x1c.proto.desktop.VideoEncodingR\rvideoEncoding\x12=\n" +
	"\fpixel_format\x18\x03 \x01(\v2\x1a.proto.desktop.PixelFormatR\vpixelFormat\x12%\n" +
	"\x0ecompress_ratio\x18\x05 \x01(\rR\rcompressRatio\x12C\n" +
	"\x0eaudio_encoding\x18\a \x01(\x0e2\x1c.proto.desktop.AudioEncodingR\raudioEncoding\"\xd4\x03\n" +
	"\fHostToClient\x12=\n" +
	"\fvideo_packet\x18\x01 \x01(\v2\x1a.proto.desktop.VideoPacketR\vvideoPacket\x12=\n" +
	"\faudio_packet\x18\x02 \x01(\v2\x1a.proto.desktop.AudioPacketR\vaudioPacket\x12=\n" +
	"\fcursor_shape\x18\x03 \x01(\v2\x1a.proto.desktop.CursorShapeR\vcursorShape\x12F\n" +
	"\x0fclipboard_event\x18\x04 \x01(\v2\x1d.proto.desktop.ClipboardEventR\x0eclipboardEvent\x126\n" +
	"\textension\x18\x05 \x01(\v2\x18.proto.desktop.ExtensionR\textension\x12?\n" +
	"\fcapabilities\x18\x06 \x01(\v2\x1b.proto.desktop.CapabilitiesR\fcapabilities\x12F\n" +
	"\x0fcursor_position\x18\a \x01(\v2\x1d.proto.desktop.CursorPositionR\x0ecursorPosition\"\xe3\x03\n" +
	"\fClientToHost\x12:\n" +
	"\vmouse_event\x18\x01 \x01(\v2\x19.proto.desktop.MouseEventR\n" +
	"mouseEvent\x124\n" +
	"\tkey_event\x18\x02 \x01(\v2\x17.proto.desktop.KeyEventR\bkeyEvent\x12:\n" +
	"\vtouch_event\x18\x03 \x01(\v2\x19.proto.desktop.TouchEventR\n" +
	"touchEvent\x127\n" +
	"\n" +
	"text_event\x18\x04 \x01(\v2\x18.proto.desktop.TextEventR\ttextEvent\x12F\n" +
	"\x0fclipboard_event\x18\x05 \x01(\v2\x1d.proto.desktop.ClipboardEventR\x0eclipboardEvent\x126\n" +
	"\textension\x18\x06 \x01(\v2\x18.proto.desktop.ExtensionR\textension\x12-\n" +
	"\x06config\x18\a \x01(\v2\x15.proto.desktop.ConfigR\x06config\x12=\n" +
	"\faudio_packet\x18\b \x01(\v2\x1a.proto.desktop.AudioPacketR\vaudioPacket*t\n" +
	"\rVideoEncoding\x12\x1a\n" +
	"\x16VIDEO_ENCODING_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13VIDEO_ENCODING_ZSTD\x10\x01\x12\x16\n" +
	"\x12VIDEO_ENCODING_VP8\x10\x02\x12\x16\n" +
	"\x12VIDEO_ENCODING_VP9\x10\x04*\x86\x01\n" +
	"\x0eVideoErrorCode\x12\x17\n" +
	"\x13VIDEO_ERROR_CODE_OK\x10\x00\x12\x1b\n" +
	"\x17VIDEO_ERROR_CODE_PAUSED\x10\x01\x12\x1e\n" +
	"\x1aVIDEO_ERROR_CODE_TEMPORARY\x10\x02\x12\x1e\n" +
	"\x1aVIDEO_ERROR_CODE_PERMANENT\x10\x03*x\n" +
	"\rAudioEncoding\x12\x1a\n" +
	"\x16AUDIO_ENCODING_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16AUDIO_ENCODING_DEFAULT\x10\x01\x12\x16\n" +
	"\x12AUDIO_ENCODING_RAW\x10\x02\x12\x17\n" +
	"\x13AUDIO_ENCODING_OPUS\x10\x03*\xee\x01\n" +
	"\vConfigFlags\x12\f\n" +
	"\bNO_FLAGS\x10\x00\x12\x17\n" +
	"\x13ENABLE_CURSOR_SHAPE\x10\x01\x12\x14\n" +
	"\x10ENABLE_CLIPBOARD\x10\x02\x12\x13\n" +
	"\x0fDISABLE_EFFECTS\x10\x04\x12\x15\n" +
	"\x11DISABLE_WALLPAPER\x10\b\x12\x1a\n" +
	"\x16DISABLE_FONT_SMOOTHING\x10\x10\x12\x16\n" +
	"\x12BLOCK_REMOTE_INPUT\x10 \x12\x16\n" +
	"\x12LOCK_AT_DISCONNECT\x10@\x12\x14\n" +
	"\x0fCURSOR_POSITION\x10\x80\x01\x12\x14\n" +
	"\x0fCLEAR_CLIPBOARD\x10\x80\x02B H\x03Z\x1caspia_rest_api/proto/desktopb\x06proto3"

var (
	file_desktop_proto_rawDescOnce sync.Once
	file_desktop_proto_rawDescData []byte
)

func file_desktop_proto_rawDescGZIP() []byte {
	file_desktop_proto_rawDescOnce.Do(func() {
		file_desktop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desktop_proto_rawDesc), len(file_desktop_proto_rawDesc)))
	})
	return file_desktop_proto_rawDescData
}

var file_desktop_proto_enumTypes = make([]protoimpl.EnumInfo, 15)
var file_desktop_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_desktop_proto_goTypes = []any{
	(VideoEncoding)(0),                   // 0: proto.desktop.VideoEncoding
	(VideoErrorCode)(0),                  // 1: proto.desktop.VideoErrorCode
	(AudioEncoding)(0),                   // 2: proto.desktop.AudioEncoding
	(ConfigFlags)(0),                     // 3: proto.desktop.ConfigFlags
	(KeyEvent_Flags)(0),                  // 4: proto.desktop.KeyEvent.Flags
	(MouseEvent_ButtonMask)(0),           // 5: proto.desktop.MouseEvent.ButtonMask
	(TouchEvent_TouchEventType)(0),       // 6: proto.desktop.TouchEvent.TouchEventType
	(CursorShape_Flags)(0),               // 7: proto.desktop.CursorShape.Flags
	(AudioPacket_SamplingRate)(0),        // 8: proto.desktop.AudioPacket.SamplingRate
	(AudioPacket_BytesPerSample)(0),      // 9: proto.desktop.AudioPacket.BytesPerSample
	(AudioPacket_Channels)(0),            // 10: proto.desktop.AudioPacket.Channels
	(PowerControl_Action)(0),             // 11: proto.desktop.PowerControl.Action
	(VideoRecording_Action)(0),           // 12: proto.desktop.VideoRecording.Action
	(ScreenType_Type)(0),                 // 13: proto.desktop.ScreenType.Type
	(Capabilities_OsType)(0),             // 14: proto.desktop.Capabilities.OsType
	(*Point)(nil),                        // 15: proto.desktop.Point
	(*Size)(nil),                         // 16: proto.desktop.Size
	(*Rect)(nil),                         // 17: proto.desktop.Rect
	(*PixelFormat)(nil),                  // 18: proto.desktop.PixelFormat
	(*KeyEvent)(nil),                     // 19: proto.desktop.KeyEvent
	(*TextEvent)(nil),                    // 20: proto.desktop.TextEvent
	(*MouseEvent)(nil),                   // 21: proto.desktop.MouseEvent
	(*TouchEventPoint)(nil),              // 22: proto.desktop.TouchEventPoint
	(*TouchEvent)(nil),                   // 23: proto.desktop.TouchEvent
	(*ClipboardEvent)(nil),               // 24: proto.desktop.ClipboardEvent
	(*CursorShape)(nil),                  // 25: proto.desktop.CursorShape
	(*CursorPosition)(nil),               // 26: proto.desktop.CursorPosition
	(*VideoPacketFormat)(nil),            // 27: proto.desktop.VideoPacketFormat
	(*VideoPacket)(nil),                  // 28: proto.desktop.VideoPacket
	(*AudioPacket)(nil),                  // 29: proto.desktop.AudioPacket
	(*Extension)(nil),                    // 30: proto.desktop.Extension
	(*Screen)(nil),                       // 31: proto.desktop.Screen
	(*ScreenList)(nil),                   // 32: proto.desktop.ScreenList
	(*Pause)(nil),                        // 33: proto.desktop.Pause
	(*PowerControl)(nil),                 // 34: proto.desktop.PowerControl
	(*VideoRecording)(nil),               // 35: proto.desktop.VideoRecording
	(*ScreenType)(nil),                   // 36: proto.desktop.ScreenType
	(*Capabilities)(nil),                 // 37: proto.desktop.Capabilities
	(*Config)(nil),                       // 38: proto.desktop.Config
	(*HostToClient)(nil),                 // 39: proto.desktop.HostToClient
	(*ClientToHost)(nil),                 // 40: proto.desktop.ClientToHost
	(*ClipboardEvent_FileList)(nil),      // 41: proto.desktop.ClipboardEvent.FileList
	(*ClipboardEvent_FileList_File)(nil), // 42: proto.desktop.ClipboardEvent.FileList.File
	(*Capabilities_Flag)(nil),            // 43: proto.desktop.Capabilities.Flag
}
var file_desktop_proto_depIdxs = []int32{
	6,  // 0: proto.desktop.TouchEvent.event_type:type_name -> proto.desktop.TouchEvent.TouchEventType
	22, // 1: proto.desktop.TouchEvent.touch_points:type_name -> proto.desktop.TouchEventPoint
	17, // 2: proto.desktop.VideoPacketFormat.video_rect:type_name -> proto.desktop.Rect
	18, // 3: proto.desktop.VideoPacketFormat.pixel_format:type_name -> proto.desktop.PixelFormat
	16, // 4: proto.desktop.VideoPacketFormat.screen_size:type_name -> proto.desktop.Size
	0,  // 5: proto.desktop.VideoPacket.encoding:type_name -> proto.desktop.VideoEncoding
	27, // 6: proto.desktop.VideoPacket.format:type_name -> proto.desktop.VideoPacketFormat
	17, // 7: proto.desktop.VideoPacket.dirty_rect:type_name -> proto.desktop.Rect
	1,  // 8: proto.desktop.VideoPacket.error_code:type_name -> proto.desktop.VideoErrorCode
	2,  // 9: proto.desktop.AudioPacket.encoding:type_name -> proto.desktop.AudioEncoding
	8,  // 10: proto.desktop.AudioPacket.sampling_rate:type_name -> proto.desktop.AudioPacket.SamplingRate
	9,  // 11: proto.desktop.AudioPacket.bytes_per_sample:type_name -> proto.desktop.AudioPacket.BytesPerSample
	10, // 12: proto.desktop.AudioPacket.channels:type_name -> proto.desktop.AudioPacket.Channels
	15, // 13: proto.desktop.Screen.position:type_name -> proto.desktop.Point
	16, // 14: proto.desktop.Screen.resolution:type_name -> proto.desktop.Size
	15, // 15: proto.desktop.Screen.dpi:type_name -> proto.desktop.Point
	31, // 16: proto.desktop.ScreenList.screen:type_name -> proto.desktop.Screen
	16, // 17: proto.desktop.ScreenList.resolution:type_name -> proto.desktop.Size
	11, // 18: proto.desktop.PowerControl.action:type_name -> proto.desktop.PowerControl.Action
	12, // 19: proto.desktop.VideoRecording.action:type_name -> proto.desktop.VideoRecording.Action
	13, // 20: proto.desktop.ScreenType.type:type_name -> proto.desktop.ScreenType.Type
	14, // 21: proto.desktop.Capabilities.os_type:type_name -> proto.desktop.Capabilities.OsType
	43, // 22: proto.desktop.Capabilities.flag:type_name -> proto.desktop.Capabilities.Flag
	0,  // 23: proto.desktop.Config.video_encoding:type_name -> proto.desktop.VideoEncoding
	18, // 24: proto.desktop.Config.pixel_format:type_name -> proto.desktop.PixelFormat
	2,  // 25: proto.desktop.Config.audio_encoding:type_name -> proto.desktop.AudioEncoding
	28, // 26: proto.desktop.HostToClient.video_packet:type_name -> proto.desktop.VideoPacket
	29, // 27: proto.desktop.HostToClient.audio_packet:type_name -> proto.desktop.AudioPacket
	25, // 28: proto.desktop.HostToClient.cursor_shape:type_name -> proto.desktop.CursorShape
	24, // 29: proto.desktop.HostToClient.clipboard_event:type_name -> proto.desktop.ClipboardEvent
	30, // 30: proto.desktop.HostToClient.extension:type_name -> proto.desktop.Extension
	37, // 31: proto.desktop.HostToClient.capabilities:type_name -> proto.desktop.Capabilities
	26, // 32: proto.desktop.HostToClient.cursor_position:type_name -> proto.desktop.CursorPosition
	21, // 33: proto.desktop.ClientToHost.mouse_event:type_name -> proto.desktop.MouseEvent
	19, // 34: proto.desktop.ClientToHost.key_event:type_name -> proto.desktop.KeyEvent
	23, // 35: proto.desktop.ClientToHost.touch_event:type_name -> proto.desktop.TouchEvent
	20, // 36: proto.desktop.ClientToHost.text_event:type_name -> proto.desktop.TextEvent
	24, // 37: proto.desktop.ClientToHost.clipboard_event:type_name -> proto.desktop.ClipboardEvent
	30, // 38: proto.desktop.ClientToHost.extension:type_name -> proto.desktop.Extension
	38, // 39: proto.desktop.ClientToHost.config:type_name -> proto.desktop.Config
	29, // 40: proto.desktop.ClientToHost.audio_packet:type_name -> proto.desktop.AudioPacket
	42, // 41: proto.desktop.ClipboardEvent.FileList.file:type_name -> proto.desktop.ClipboardEvent.FileList.File
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_desktop_proto_init() }
func file_desktop_proto_init() {
	if File_desktop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desktop_proto_rawDesc), len(file_desktop_proto_rawDesc)),
			NumEnums:      15,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_desktop_proto_goTypes,
		DependencyIndexes: file_desktop_proto_depIdxs,
		EnumInfos:         file_desktop_proto_enumTypes,
		MessageInfos:      file_desktop_proto_msgTypes,
	}.Build()
	File_desktop_proto = out.File
	file_desktop_proto_goTypes = nil
	file_desktop_proto_depIdxs = nil
}
