//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: router_peer.proto

package router_peer

import (
	router "aspia_rest_api/proto/router"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostIdRequest_Type int32

const (
	HostIdRequest_UNKNOWN     HostIdRequest_Type = 0
	HostIdRequest_NEW_ID      HostIdRequest_Type = 1
	HostIdRequest_EXISTING_ID HostIdRequest_Type = 2
)

// Enum value maps for HostIdRequest_Type.
var (
	HostIdRequest_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "NEW_ID",
		2: "EXISTING_ID",
	}
	HostIdRequest_Type_value = map[string]int32{
		"UNKNOWN":     0,
		"NEW_ID":      1,
		"EXISTING_ID": 2,
	}
)

func (x HostIdRequest_Type) Enum() *HostIdRequest_Type {
	p := new(HostIdRequest_Type)
	*p = x
	return p
}

func (x HostIdRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostIdRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_router_peer_proto_enumTypes[0].Descriptor()
}

func (HostIdRequest_Type) Type() protoreflect.EnumType {
	return &file_router_peer_proto_enumTypes[0]
}

func (x HostIdRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostIdRequest_Type.Descriptor instead.
func (HostIdRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{0, 0}
}

type HostIdResponse_ErrorCode int32

const (
	HostIdResponse_SUCCESS       HostIdResponse_ErrorCode = 0
	HostIdResponse_UNKNOWN       HostIdResponse_ErrorCode = 1
	HostIdResponse_NO_HOST_FOUND HostIdResponse_ErrorCode = 2
)

// Enum value maps for HostIdResponse_ErrorCode.
var (
	HostIdResponse_ErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "UNKNOWN",
		2: "NO_HOST_FOUND",
	}
	HostIdResponse_ErrorCode_value = map[string]int32{
		"SUCCESS":       0,
		"UNKNOWN":       1,
		"NO_HOST_FOUND": 2,
	}
)

func (x HostIdResponse_ErrorCode) Enum() *HostIdResponse_ErrorCode {
	p := new(HostIdResponse_ErrorCode)
	*p = x
	return p
}

func (x HostIdResponse_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostIdResponse_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_router_peer_proto_enumTypes[1].Descriptor()
}

func (HostIdResponse_ErrorCode) Type() protoreflect.EnumType {
	return &file_router_peer_proto_enumTypes[1]
}

func (x HostIdResponse_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostIdResponse_ErrorCode.Descriptor instead.
func (HostIdResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{2, 0}
}

type ConnectionOffer_PeerRole int32

const (
	ConnectionOffer_HOST   ConnectionOffer_PeerRole = 0
	ConnectionOffer_CLIENT ConnectionOffer_PeerRole = 1
)

// Enum value maps for ConnectionOffer_PeerRole.
var (
	ConnectionOffer_PeerRole_name = map[int32]string{
		0: "HOST",
		1: "CLIENT",
	}
	ConnectionOffer_PeerRole_value = map[string]int32{
		"HOST":   0,
		"CLIENT": 1,
	}
)

func (x ConnectionOffer_PeerRole) Enum() *ConnectionOffer_PeerRole {
	p := new(ConnectionOffer_PeerRole)
	*p = x
	return p
}

func (x ConnectionOffer_PeerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionOffer_PeerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_router_peer_proto_enumTypes[2].Descriptor()
}

func (ConnectionOffer_PeerRole) Type() protoreflect.EnumType {
	return &file_router_peer_proto_enumTypes[2]
}

func (x ConnectionOffer_PeerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionOffer_PeerRole.Descriptor instead.
func (ConnectionOffer_PeerRole) EnumDescriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{5, 0}
}

type ConnectionOffer_ErrorCode int32

const (
	ConnectionOffer_SUCCESS        ConnectionOffer_ErrorCode = 0
	ConnectionOffer_UNKNOWN_ERROR  ConnectionOffer_ErrorCode = 1
	ConnectionOffer_PEER_NOT_FOUND ConnectionOffer_ErrorCode = 2
	ConnectionOffer_ACCESS_DENIED  ConnectionOffer_ErrorCode = 3
	ConnectionOffer_KEY_POOL_EMPTY ConnectionOffer_ErrorCode = 4
)

// Enum value maps for ConnectionOffer_ErrorCode.
var (
	ConnectionOffer_ErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "UNKNOWN_ERROR",
		2: "PEER_NOT_FOUND",
		3: "ACCESS_DENIED",
		4: "KEY_POOL_EMPTY",
	}
	ConnectionOffer_ErrorCode_value = map[string]int32{
		"SUCCESS":        0,
		"UNKNOWN_ERROR":  1,
		"PEER_NOT_FOUND": 2,
		"ACCESS_DENIED":  3,
		"KEY_POOL_EMPTY": 4,
	}
)

func (x ConnectionOffer_ErrorCode) Enum() *ConnectionOffer_ErrorCode {
	p := new(ConnectionOffer_ErrorCode)
	*p = x
	return p
}

func (x ConnectionOffer_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionOffer_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_router_peer_proto_enumTypes[3].Descriptor()
}

func (ConnectionOffer_ErrorCode) Type() protoreflect.EnumType {
	return &file_router_peer_proto_enumTypes[3]
}

func (x ConnectionOffer_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionOffer_ErrorCode.Descriptor instead.
func (ConnectionOffer_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{5, 1}
}

type HostStatus_Status int32

const (
	HostStatus_STATUS_UNKNOWN HostStatus_Status = 0
	HostStatus_STATUS_OFFLINE HostStatus_Status = 1
	HostStatus_STATUS_ONLINE  HostStatus_Status = 2
)

// Enum value maps for HostStatus_Status.
var (
	HostStatus_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_OFFLINE",
		2: "STATUS_ONLINE",
	}
	HostStatus_Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_OFFLINE": 1,
		"STATUS_ONLINE":  2,
	}
)

func (x HostStatus_Status) Enum() *HostStatus_Status {
	p := new(HostStatus_Status)
	*p = x
	return p
}

func (x HostStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_router_peer_proto_enumTypes[4].Descriptor()
}

func (HostStatus_Status) Type() protoreflect.EnumType {
	return &file_router_peer_proto_enumTypes[4]
}

func (x HostStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostStatus_Status.Descriptor instead.
func (HostStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{7, 0}
}

type HostIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          HostIdRequest_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=proto.router.HostIdRequest_Type" json:"type,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostIdRequest) Reset() {
	*x = HostIdRequest{}
	mi := &file_router_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostIdRequest) ProtoMessage() {}

func (x *HostIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostIdRequest.ProtoReflect.Descriptor instead.
func (*HostIdRequest) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{0}
}

func (x *HostIdRequest) GetType() HostIdRequest_Type {
	if x != nil {
		return x.Type
	}
	return HostIdRequest_UNKNOWN
}

func (x *HostIdRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ResetHostId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        uint64                 `protobuf:"fixed64,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetHostId) Reset() {
	*x = ResetHostId{}
	mi := &file_router_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetHostId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetHostId) ProtoMessage() {}

func (x *ResetHostId) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetHostId.ProtoReflect.Descriptor instead.
func (*ResetHostId) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ResetHostId) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

type HostIdResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	HostId        uint64                   `protobuf:"fixed64,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Key           []byte                   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ErrorCode     HostIdResponse_ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=proto.router.HostIdResponse_ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostIdResponse) Reset() {
	*x = HostIdResponse{}
	mi := &file_router_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostIdResponse) ProtoMessage() {}

func (x *HostIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostIdResponse.ProtoReflect.Descriptor instead.
func (*HostIdResponse) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{2}
}

func (x *HostIdResponse) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *HostIdResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *HostIdResponse) GetErrorCode() HostIdResponse_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return HostIdResponse_SUCCESS
}

type ConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        uint64                 `protobuf:"fixed64,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_router_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionRequest) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

type HostOfferData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        uint64                 `protobuf:"fixed64,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"` // ID to which the client will connect.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostOfferData) Reset() {
	*x = HostOfferData{}
	mi := &file_router_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostOfferData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostOfferData) ProtoMessage() {}

func (x *HostOfferData) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostOfferData.ProtoReflect.Descriptor instead.
func (*HostOfferData) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{4}
}

func (x *HostOfferData) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

type ConnectionOffer struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	PeerRole      ConnectionOffer_PeerRole  `protobuf:"varint,1,opt,name=peer_role,json=peerRole,proto3,enum=proto.router.ConnectionOffer_PeerRole" json:"peer_role,omitempty"`
	ErrorCode     ConnectionOffer_ErrorCode `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=proto.router.ConnectionOffer_ErrorCode" json:"error_code,omitempty"`
	Relay         *router.RelayCredentials  `protobuf:"bytes,3,opt,name=relay,proto3" json:"relay,omitempty"`
	HostData      *HostOfferData            `protobuf:"bytes,4,opt,name=host_data,json=hostData,proto3" json:"host_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionOffer) Reset() {
	*x = ConnectionOffer{}
	mi := &file_router_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionOffer) ProtoMessage() {}

func (x *ConnectionOffer) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionOffer.ProtoReflect.Descriptor instead.
func (*ConnectionOffer) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectionOffer) GetPeerRole() ConnectionOffer_PeerRole {
	if x != nil {
		return x.PeerRole
	}
	return ConnectionOffer_HOST
}

func (x *ConnectionOffer) GetErrorCode() ConnectionOffer_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ConnectionOffer_SUCCESS
}

func (x *ConnectionOffer) GetRelay() *router.RelayCredentials {
	if x != nil {
		return x.Relay
	}
	return nil
}

func (x *ConnectionOffer) GetHostData() *HostOfferData {
	if x != nil {
		return x.HostData
	}
	return nil
}

type CheckHostStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        uint64                 `protobuf:"fixed64,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHostStatus) Reset() {
	*x = CheckHostStatus{}
	mi := &file_router_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHostStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHostStatus) ProtoMessage() {}

func (x *CheckHostStatus) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHostStatus.ProtoReflect.Descriptor instead.
func (*CheckHostStatus) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{6}
}

func (x *CheckHostStatus) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

type HostStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HostStatus_Status      `protobuf:"varint,1,opt,name=status,proto3,enum=proto.router.HostStatus_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStatus) Reset() {
	*x = HostStatus{}
	mi := &file_router_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStatus) ProtoMessage() {}

func (x *HostStatus) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStatus.ProtoReflect.Descriptor instead.
func (*HostStatus) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{7}
}

func (x *HostStatus) GetStatus() HostStatus_Status {
	if x != nil {
		return x.Status
	}
	return HostStatus_STATUS_UNKNOWN
}

type RouterToPeer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostIdResponse  *HostIdResponse        `protobuf:"bytes,1,opt,name=host_id_response,json=hostIdResponse,proto3" json:"host_id_response,omitempty"`
	ConnectionOffer *ConnectionOffer       `protobuf:"bytes,2,opt,name=connection_offer,json=connectionOffer,proto3" json:"connection_offer,omitempty"`
	HostStatus      *HostStatus            `protobuf:"bytes,3,opt,name=host_status,json=hostStatus,proto3" json:"host_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouterToPeer) Reset() {
	*x = RouterToPeer{}
	mi := &file_router_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterToPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterToPeer) ProtoMessage() {}

func (x *RouterToPeer) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterToPeer.ProtoReflect.Descriptor instead.
func (*RouterToPeer) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{8}
}

func (x *RouterToPeer) GetHostIdResponse() *HostIdResponse {
	if x != nil {
		return x.HostIdResponse
	}
	return nil
}

func (x *RouterToPeer) GetConnectionOffer() *ConnectionOffer {
	if x != nil {
		return x.ConnectionOffer
	}
	return nil
}

func (x *RouterToPeer) GetHostStatus() *HostStatus {
	if x != nil {
		return x.HostStatus
	}
	return nil
}

type PeerToRouter struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConnectionRequest *ConnectionRequest     `protobuf:"bytes,1,opt,name=connection_request,json=connectionRequest,proto3" json:"connection_request,omitempty"`
	HostIdRequest     *HostIdRequest         `protobuf:"bytes,2,opt,name=host_id_request,json=hostIdRequest,proto3" json:"host_id_request,omitempty"`
	ResetHostId       *ResetHostId           `protobuf:"bytes,3,opt,name=reset_host_id,json=resetHostId,proto3" json:"reset_host_id,omitempty"`
	CheckHostStatus   *CheckHostStatus       `protobuf:"bytes,4,opt,name=check_host_status,json=checkHostStatus,proto3" json:"check_host_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerToRouter) Reset() {
	*x = PeerToRouter{}
	mi := &file_router_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerToRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerToRouter) ProtoMessage() {}

func (x *PeerToRouter) ProtoReflect() protoreflect.Message {
	mi := &file_router_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerToRouter.ProtoReflect.Descriptor instead.
func (*PeerToRouter) Descriptor() ([]byte, []int) {
	return file_router_peer_proto_rawDescGZIP(), []int{9}
}

func (x *PeerToRouter) GetConnectionRequest() *ConnectionRequest {
	if x != nil {
		return x.ConnectionRequest
	}
	return nil
}

func (x *PeerToRouter) GetHostIdRequest() *HostIdRequest {
	if x != nil {
		return x.HostIdRequest
	}
	return nil
}

func (x *PeerToRouter) GetResetHostId() *ResetHostId {
	if x != nil {
		return x.ResetHostId
	}
	return nil
}

func (x *PeerToRouter) GetCheckHostStatus() *CheckHostStatus {
	if x != nil {
		return x.CheckHostStatus
	}
	return nil
}

var File_router_peer_proto protoreflect.FileDescriptor

const file_router_peer_proto_rawDesc = "" +
	"\n" +
	"\x11router_peer.proto\x12\fproto.router\x1a\frouter.proto\"\x89\x01\n" +
	"\rHostIdRequest\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .proto.router.HostIdRequest.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"0\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06NEW_ID\x10\x01\x12\x0f\n" +
	"\vEXISTING_ID\x10\x02\"&\n" +
	"\vResetHostId\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x06R\x06hostId\"\xbc\x01\n" +
	"\x0eHostIdResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x06R\x06hostId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12E\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x0e2&.proto.router.HostIdResponse.ErrorCodeR\terrorCode\"8\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x11\n" +
	"\rNO_HOST_FOUND\x10\x02\",\n" +
	"\x11ConnectionRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x06R\x06hostId\"(\n" +
	"\rHostOfferData\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x06R\x06hostId\"\x98\x03\n" +
	"\x0fConnectionOffer\x12C\n" +
	"\tpeer_role\x18\x01 \x01(\x0e2&.proto.router.ConnectionOffer.PeerRoleR\bpeerRole\x12F\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2'.proto.router.ConnectionOffer.ErrorCodeR\terrorCode\x124\n" +
	"\x05relay\x18\x03 \x01(\v2\x1e.proto.router.RelayCredentialsR\x05relay\x128\n" +
	"\thost_data\x18\x04 \x01(\v2\x1b.proto.router.HostOfferDataR\bhostData\" \n" +
	"\bPeerRole\x12\b\n" +
	"\x04HOST\x10\x00\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x01\"f\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x01\x12\x12\n" +
	"\x0ePEER_NOT_FOUND\x10\x02\x12\x11\n" +
	"\rACCESS_DENIED\x10\x03\x12\x12\n" +
	"\x0eKEY_POOL_EMPTY\x10\x04\"*\n" +
	"\x0fCheckHostStatus\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x06R\x06hostId\"\x8a\x01\n" +
	"\n" +
	"HostStatus\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.proto.router.HostStatus.StatusR\x06status\"C\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_OFFLINE\x10\x01\x12\x11\n" +
	"\rSTATUS_ONLINE\x10\x02\"\xdb\x01\n" +
	"\fRouterToPeer\x12F\n" +
	"\x10host_id_response\x18\x01 \x01(\v2\x1c.proto.router.HostIdResponseR\x0ehostIdResponse\x12H\n" +
	"\x10connection_offer\x18\x02 \x01(\v2\x1d.proto.router.ConnectionOfferR\x0fconnectionOffer\x129\n" +
	"\vhost_status\x18\x03 \x01(\v2\x18.proto.router.HostStatusR\n" +
	"hostStatus\"\xad\x02\n" +
	"\fPeerToRouter\x12N\n" +
	"\x12connection_request\x18\x01 \x01(\v2\x1f.proto.router.ConnectionRequestR\x11connectionRequest\x12C\n" +
	"\x0fhost_id_request\x18\x02 \x01(\v2\x1b.proto.router.HostIdRequestR\rhostIdRequest\x12=\n" +
	"\rreset_host_id\x18\x03 \x01(\v2\x19.proto.router.ResetHostIdR\vresetHostId\x12I\n" +
	"\x11check_host_status\x18\x04 \x01(\v2\x1d.proto.router.CheckHostStatusR\x0fcheckHostStatusB$H\x03Z aspia_rest_api/proto/router_peerb\x06proto3"

var (
	file_router_peer_proto_rawDescOnce sync.Once
	file_router_peer_proto_rawDescData []byte
)

func file_router_peer_proto_rawDescGZIP() []byte {
	file_router_peer_proto_rawDescOnce.Do(func() {
		file_router_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_peer_proto_rawDesc), len(file_router_peer_proto_rawDesc)))
	})
	return file_router_peer_proto_rawDescData
}

var file_router_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_router_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_router_peer_proto_goTypes = []any{
	(HostIdRequest_Type)(0),         // 0: proto.router.HostIdRequest.Type
	(HostIdResponse_ErrorCode)(0),   // 1: proto.router.HostIdResponse.ErrorCode
	(ConnectionOffer_PeerRole)(0),   // 2: proto.router.ConnectionOffer.PeerRole
	(ConnectionOffer_ErrorCode)(0),  // 3: proto.router.ConnectionOffer.ErrorCode
	(HostStatus_Status)(0),          // 4: proto.router.HostStatus.Status
	(*HostIdRequest)(nil),           // 5: proto.router.HostIdRequest
	(*ResetHostId)(nil),             // 6: proto.router.ResetHostId
	(*HostIdResponse)(nil),          // 7: proto.router.HostIdResponse
	(*ConnectionRequest)(nil),       // 8: proto.router.ConnectionRequest
	(*HostOfferData)(nil),           // 9: proto.router.HostOfferData
	(*ConnectionOffer)(nil),         // 10: proto.router.ConnectionOffer
	(*CheckHostStatus)(nil),         // 11: proto.router.CheckHostStatus
	(*HostStatus)(nil),              // 12: proto.router.HostStatus
	(*RouterToPeer)(nil),            // 13: proto.router.RouterToPeer
	(*PeerToRouter)(nil),            // 14: proto.router.PeerToRouter
	(*router.RelayCredentials)(nil), // 15: proto.router.RelayCredentials
}
var file_router_peer_proto_depIdxs = []int32{
	0,  // 0: proto.router.HostIdRequest.type:type_name -> proto.router.HostIdRequest.Type
	1,  // 1: proto.router.HostIdResponse.error_code:type_name -> proto.router.HostIdResponse.ErrorCode
	2,  // 2: proto.router.ConnectionOffer.peer_role:type_name -> proto.router.ConnectionOffer.PeerRole
	3,  // 3: proto.router.ConnectionOffer.error_code:type_name -> proto.router.ConnectionOffer.ErrorCode
	15, // 4: proto.router.ConnectionOffer.relay:type_name -> proto.router.RelayCredentials
	9,  // 5: proto.router.ConnectionOffer.host_data:type_name -> proto.router.HostOfferData
	4,  // 6: proto.router.HostStatus.status:type_name -> proto.router.HostStatus.Status
	7,  // 7: proto.router.RouterToPeer.host_id_response:type_name -> proto.router.HostIdResponse
	10, // 8: proto.router.RouterToPeer.connection_offer:type_name -> proto.router.ConnectionOffer
	12, // 9: proto.router.RouterToPeer.host_status:type_name -> proto.router.HostStatus
	8,  // 10: proto.router.PeerToRouter.connection_request:type_name -> proto.router.ConnectionRequest
	5,  // 11: proto.router.PeerToRouter.host_id_request:type_name -> proto.router.HostIdRequest
	6,  // 12: proto.router.PeerToRouter.reset_host_id:type_name -> proto.router.ResetHostId
	11, // 13: proto.router.PeerToRouter.check_host_status:type_name -> proto.router.CheckHostStatus
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_router_peer_proto_init() }
func file_router_peer_proto_init() {
	if File_router_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_peer_proto_rawDesc), len(file_router_peer_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_router_peer_proto_goTypes,
		DependencyIndexes: file_router_peer_proto_depIdxs,
		EnumInfos:         file_router_peer_proto_enumTypes,
		MessageInfos:      file_router_peer_proto_msgTypes,
	}.Build()
	File_router_peer_proto = out.File
	file_router_peer_proto_goTypes = nil
	file_router_peer_proto_depIdxs = nil
}
