//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: router.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelId int32

const (
	ChannelId_CHANNEL_ID_SESSION ChannelId = 0
)

// Enum value maps for ChannelId.
var (
	ChannelId_name = map[int32]string{
		0: "CHANNEL_ID_SESSION",
	}
	ChannelId_value = map[string]int32{
		"CHANNEL_ID_SESSION": 0,
	}
)

func (x ChannelId) Enum() *ChannelId {
	p := new(ChannelId)
	*p = x
	return p
}

func (x ChannelId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelId) Descriptor() protoreflect.EnumDescriptor {
	return file_router_proto_enumTypes[0].Descriptor()
}

func (ChannelId) Type() protoreflect.EnumType {
	return &file_router_proto_enumTypes[0]
}

func (x ChannelId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelId.Descriptor instead.
func (ChannelId) EnumDescriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{0}
}

type SessionType int32

const (
	SessionType_SESSION_TYPE_UNKNOWN SessionType = 0
	SessionType_SESSION_TYPE_ADMIN   SessionType = 1
	SessionType_SESSION_TYPE_CLIENT  SessionType = 2
	SessionType_SESSION_TYPE_HOST    SessionType = 4
	SessionType_SESSION_TYPE_RELAY   SessionType = 8
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0: "SESSION_TYPE_UNKNOWN",
		1: "SESSION_TYPE_ADMIN",
		2: "SESSION_TYPE_CLIENT",
		4: "SESSION_TYPE_HOST",
		8: "SESSION_TYPE_RELAY",
	}
	SessionType_value = map[string]int32{
		"SESSION_TYPE_UNKNOWN": 0,
		"SESSION_TYPE_ADMIN":   1,
		"SESSION_TYPE_CLIENT":  2,
		"SESSION_TYPE_HOST":    4,
		"SESSION_TYPE_RELAY":   8,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_router_proto_enumTypes[1].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_router_proto_enumTypes[1]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{1}
}

type PeerConnectionRequestType int32

const (
	PeerConnectionRequestType_PEER_CONNECTION_REQUEST_UNKNOWN    PeerConnectionRequestType = 0
	PeerConnectionRequestType_PEER_CONNECTION_REQUEST_DISCONNECT PeerConnectionRequestType = 1
)

// Enum value maps for PeerConnectionRequestType.
var (
	PeerConnectionRequestType_name = map[int32]string{
		0: "PEER_CONNECTION_REQUEST_UNKNOWN",
		1: "PEER_CONNECTION_REQUEST_DISCONNECT",
	}
	PeerConnectionRequestType_value = map[string]int32{
		"PEER_CONNECTION_REQUEST_UNKNOWN":    0,
		"PEER_CONNECTION_REQUEST_DISCONNECT": 1,
	}
)

func (x PeerConnectionRequestType) Enum() *PeerConnectionRequestType {
	p := new(PeerConnectionRequestType)
	*p = x
	return p
}

func (x PeerConnectionRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerConnectionRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_router_proto_enumTypes[2].Descriptor()
}

func (PeerConnectionRequestType) Type() protoreflect.EnumType {
	return &file_router_proto_enumTypes[2]
}

func (x PeerConnectionRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerConnectionRequestType.Descriptor instead.
func (PeerConnectionRequestType) EnumDescriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{2}
}

type RelayKey_Type int32

const (
	RelayKey_TYPE_UNKNOWN RelayKey_Type = 0
	RelayKey_TYPE_X25519  RelayKey_Type = 1
)

// Enum value maps for RelayKey_Type.
var (
	RelayKey_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_X25519",
	}
	RelayKey_Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"TYPE_X25519":  1,
	}
)

func (x RelayKey_Type) Enum() *RelayKey_Type {
	p := new(RelayKey_Type)
	*p = x
	return p
}

func (x RelayKey_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayKey_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_router_proto_enumTypes[3].Descriptor()
}

func (RelayKey_Type) Type() protoreflect.EnumType {
	return &file_router_proto_enumTypes[3]
}

func (x RelayKey_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayKey_Type.Descriptor instead.
func (RelayKey_Type) EnumDescriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{0, 0}
}

type RelayKey_Encryption int32

const (
	RelayKey_ENCRYPTION_UNKNOWN           RelayKey_Encryption = 0
	RelayKey_ENCRYPTION_CHACHA20_POLY1305 RelayKey_Encryption = 1
)

// Enum value maps for RelayKey_Encryption.
var (
	RelayKey_Encryption_name = map[int32]string{
		0: "ENCRYPTION_UNKNOWN",
		1: "ENCRYPTION_CHACHA20_POLY1305",
	}
	RelayKey_Encryption_value = map[string]int32{
		"ENCRYPTION_UNKNOWN":           0,
		"ENCRYPTION_CHACHA20_POLY1305": 1,
	}
)

func (x RelayKey_Encryption) Enum() *RelayKey_Encryption {
	p := new(RelayKey_Encryption)
	*p = x
	return p
}

func (x RelayKey_Encryption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayKey_Encryption) Descriptor() protoreflect.EnumDescriptor {
	return file_router_proto_enumTypes[4].Descriptor()
}

func (RelayKey_Encryption) Type() protoreflect.EnumType {
	return &file_router_proto_enumTypes[4]
}

func (x RelayKey_Encryption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayKey_Encryption.Descriptor instead.
func (RelayKey_Encryption) EnumDescriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{0, 1}
}

type PeerConnection_PeerStatus int32

const (
	PeerConnection_PEER_STATUS_UNKNOWN  PeerConnection_PeerStatus = 0
	PeerConnection_PEER_STATUS_ACTIVE   PeerConnection_PeerStatus = 1
	PeerConnection_PEER_STATUS_FINISHED PeerConnection_PeerStatus = 2
)

// Enum value maps for PeerConnection_PeerStatus.
var (
	PeerConnection_PeerStatus_name = map[int32]string{
		0: "PEER_STATUS_UNKNOWN",
		1: "PEER_STATUS_ACTIVE",
		2: "PEER_STATUS_FINISHED",
	}
	PeerConnection_PeerStatus_value = map[string]int32{
		"PEER_STATUS_UNKNOWN":  0,
		"PEER_STATUS_ACTIVE":   1,
		"PEER_STATUS_FINISHED": 2,
	}
)

func (x PeerConnection_PeerStatus) Enum() *PeerConnection_PeerStatus {
	p := new(PeerConnection_PeerStatus)
	*p = x
	return p
}

func (x PeerConnection_PeerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerConnection_PeerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_router_proto_enumTypes[5].Descriptor()
}

func (PeerConnection_PeerStatus) Type() protoreflect.EnumType {
	return &file_router_proto_enumTypes[5]
}

func (x PeerConnection_PeerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerConnection_PeerStatus.Descriptor instead.
func (PeerConnection_PeerStatus) EnumDescriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{2, 0}
}

type RelayKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique key identifier in the proxy pool.
	KeyId uint32 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Key type.
	Type RelayKey_Type `protobuf:"varint,2,opt,name=type,proto3,enum=proto.router.RelayKey_Type" json:"type,omitempty"`
	// Encryption algorithm.
	Encryption RelayKey_Encryption `protobuf:"varint,3,opt,name=encryption,proto3,enum=proto.router.RelayKey_Encryption" json:"encryption,omitempty"`
	// Public key of the proxy.
	PublicKey []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Initialization vector.
	Iv            []byte `protobuf:"bytes,5,opt,name=iv,proto3" json:"iv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayKey) Reset() {
	*x = RelayKey{}
	mi := &file_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayKey) ProtoMessage() {}

func (x *RelayKey) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayKey.ProtoReflect.Descriptor instead.
func (*RelayKey) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{0}
}

func (x *RelayKey) GetKeyId() uint32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *RelayKey) GetType() RelayKey_Type {
	if x != nil {
		return x.Type
	}
	return RelayKey_TYPE_UNKNOWN
}

func (x *RelayKey) GetEncryption() RelayKey_Encryption {
	if x != nil {
		return x.Encryption
	}
	return RelayKey_ENCRYPTION_UNKNOWN
}

func (x *RelayKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RelayKey) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

type RelayCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Key           *RelayKey              `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Secret        []byte                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayCredentials) Reset() {
	*x = RelayCredentials{}
	mi := &file_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayCredentials) ProtoMessage() {}

func (x *RelayCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayCredentials.ProtoReflect.Descriptor instead.
func (*RelayCredentials) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{1}
}

func (x *RelayCredentials) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RelayCredentials) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RelayCredentials) GetKey() *RelayKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RelayCredentials) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type PeerConnection struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SessionId        uint64                    `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status           PeerConnection_PeerStatus `protobuf:"varint,2,opt,name=status,proto3,enum=proto.router.PeerConnection_PeerStatus" json:"status,omitempty"`
	ClientAddress    string                    `protobuf:"bytes,3,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	ClientUserName   string                    `protobuf:"bytes,4,opt,name=client_user_name,json=clientUserName,proto3" json:"client_user_name,omitempty"`
	HostAddress      string                    `protobuf:"bytes,5,opt,name=host_address,json=hostAddress,proto3" json:"host_address,omitempty"`
	HostId           uint64                    `protobuf:"fixed64,6,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	BytesTransferred int64                     `protobuf:"varint,7,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	Duration         int64                     `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	IdleTime         int64                     `protobuf:"varint,9,opt,name=idle_time,json=idleTime,proto3" json:"idle_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerConnection) Reset() {
	*x = PeerConnection{}
	mi := &file_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerConnection) ProtoMessage() {}

func (x *PeerConnection) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerConnection.ProtoReflect.Descriptor instead.
func (*PeerConnection) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{2}
}

func (x *PeerConnection) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *PeerConnection) GetStatus() PeerConnection_PeerStatus {
	if x != nil {
		return x.Status
	}
	return PeerConnection_PEER_STATUS_UNKNOWN
}

func (x *PeerConnection) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

func (x *PeerConnection) GetClientUserName() string {
	if x != nil {
		return x.ClientUserName
	}
	return ""
}

func (x *PeerConnection) GetHostAddress() string {
	if x != nil {
		return x.HostAddress
	}
	return ""
}

func (x *PeerConnection) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PeerConnection) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *PeerConnection) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PeerConnection) GetIdleTime() int64 {
	if x != nil {
		return x.IdleTime
	}
	return 0
}

type PeerConnectionRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	RelaySessionId int64                     `protobuf:"varint,1,opt,name=relay_session_id,json=relaySessionId,proto3" json:"relay_session_id,omitempty"`
	Type           PeerConnectionRequestType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.router.PeerConnectionRequestType" json:"type,omitempty"`
	PeerSessionId  uint64                    `protobuf:"varint,3,opt,name=peer_session_id,json=peerSessionId,proto3" json:"peer_session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerConnectionRequest) Reset() {
	*x = PeerConnectionRequest{}
	mi := &file_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerConnectionRequest) ProtoMessage() {}

func (x *PeerConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerConnectionRequest.ProtoReflect.Descriptor instead.
func (*PeerConnectionRequest) Descriptor() ([]byte, []int) {
	return file_router_proto_rawDescGZIP(), []int{3}
}

func (x *PeerConnectionRequest) GetRelaySessionId() int64 {
	if x != nil {
		return x.RelaySessionId
	}
	return 0
}

func (x *PeerConnectionRequest) GetType() PeerConnectionRequestType {
	if x != nil {
		return x.Type
	}
	return PeerConnectionRequestType_PEER_CONNECTION_REQUEST_UNKNOWN
}

func (x *PeerConnectionRequest) GetPeerSessionId() uint64 {
	if x != nil {
		return x.PeerSessionId
	}
	return 0
}

var File_router_proto protoreflect.FileDescriptor

const file_router_proto_rawDesc = "" +
	"\n" +
	"\frouter.proto\x12\fproto.router\"\xb7\x02\n" +
	"\bRelayKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\rR\x05keyId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.proto.router.RelayKey.TypeR\x04type\x12A\n" +
	"\n" +
	"encryption\x18\x03 \x01(\x0e2!.proto.router.RelayKey.EncryptionR\n" +
	"encryption\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x0e\n" +
	"\x02iv\x18\x05 \x01(\fR\x02iv\")\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vTYPE_X25519\x10\x01\"F\n" +
	"\n" +
	"Encryption\x12\x16\n" +
	"\x12ENCRYPTION_UNKNOWN\x10\x00\x12 \n" +
	"\x1cENCRYPTION_CHACHA20_POLY1305\x10\x01\"|\n" +
	"\x10RelayCredentials\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12(\n" +
	"\x03key\x18\x03 \x01(\v2\x16.proto.router.RelayKeyR\x03key\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\fR\x06secret\"\xbc\x03\n" +
	"\x0ePeerConnection\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2'.proto.router.PeerConnection.PeerStatusR\x06status\x12%\n" +
	"\x0eclient_address\x18\x03 \x01(\tR\rclientAddress\x12(\n" +
	"\x10client_user_name\x18\x04 \x01(\tR\x0eclientUserName\x12!\n" +
	"\fhost_address\x18\x05 \x01(\tR\vhostAddress\x12\x17\n" +
	"\ahost_id\x18\x06 \x01(\x06R\x06hostId\x12+\n" +
	"\x11bytes_transferred\x18\a \x01(\x03R\x10bytesTransferred\x12\x1a\n" +
	"\bduration\x18\b \x01(\x03R\bduration\x12\x1b\n" +
	"\tidle_time\x18\t \x01(\x03R\bidleTime\"W\n" +
	"\n" +
	"PeerStatus\x12\x17\n" +
	"\x13PEER_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12PEER_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14PEER_STATUS_FINISHED\x10\x02\"\xa6\x01\n" +
	"\x15PeerConnectionRequest\x12(\n" +
	"\x10relay_session_id\x18\x01 \x01(\x03R\x0erelaySessionId\x12;\n" +
	"\x04type\x18\x02 \x01(\x0e2'.proto.router.PeerConnectionRequestTypeR\x04type\x12&\n" +
	"\x0fpeer_session_id\x18\x03 \x01(\x04R\rpeerSessionId*#\n" +
	"\tChannelId\x12\x16\n" +
	"\x12CHANNEL_ID_SESSION\x10\x00*\x87\x01\n" +
	"\vSessionType\x12\x18\n" +
	"\x14SESSION_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12SESSION_TYPE_ADMIN\x10\x01\x12\x17\n" +
	"\x13SESSION_TYPE_CLIENT\x10\x02\x12\x15\n" +
	"\x11SESSION_TYPE_HOST\x10\x04\x12\x16\n" +
	"\x12SESSION_TYPE_RELAY\x10\b*h\n" +
	"\x19PeerConnectionRequestType\x12#\n" +
	"\x1fPEER_CONNECTION_REQUEST_UNKNOWN\x10\x00\x12&\n" +
	"\"PEER_CONNECTION_REQUEST_DISCONNECT\x10\x01B\x1fH\x03Z\x1baspia_rest_api/proto/routerb\x06proto3"

var (
	file_router_proto_rawDescOnce sync.Once
	file_router_proto_rawDescData []byte
)

func file_router_proto_rawDescGZIP() []byte {
	file_router_proto_rawDescOnce.Do(func() {
		file_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)))
	})
	return file_router_proto_rawDescData
}

var file_router_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_router_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_router_proto_goTypes = []any{
	(ChannelId)(0),                 // 0: proto.router.ChannelId
	(SessionType)(0),               // 1: proto.router.SessionType
	(PeerConnectionRequestType)(0), // 2: proto.router.PeerConnectionRequestType
	(RelayKey_Type)(0),             // 3: proto.router.RelayKey.Type
	(RelayKey_Encryption)(0),       // 4: proto.router.RelayKey.Encryption
	(PeerConnection_PeerStatus)(0), // 5: proto.router.PeerConnection.PeerStatus
	(*RelayKey)(nil),               // 6: proto.router.RelayKey
	(*RelayCredentials)(nil),       // 7: proto.router.RelayCredentials
	(*PeerConnection)(nil),         // 8: proto.router.PeerConnection
	(*PeerConnectionRequest)(nil),  // 9: proto.router.PeerConnectionRequest
}
var file_router_proto_depIdxs = []int32{
	3, // 0: proto.router.RelayKey.type:type_name -> proto.router.RelayKey.Type
	4, // 1: proto.router.RelayKey.encryption:type_name -> proto.router.RelayKey.Encryption
	6, // 2: proto.router.RelayCredentials.key:type_name -> proto.router.RelayKey
	5, // 3: proto.router.PeerConnection.status:type_name -> proto.router.PeerConnection.PeerStatus
	2, // 4: proto.router.PeerConnectionRequest.type:type_name -> proto.router.PeerConnectionRequestType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_router_proto_init() }
func file_router_proto_init() {
	if File_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_proto_rawDesc), len(file_router_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_router_proto_goTypes,
		DependencyIndexes: file_router_proto_depIdxs,
		EnumInfos:         file_router_proto_enumTypes,
		MessageInfos:      file_router_proto_msgTypes,
	}.Build()
	File_router_proto = out.File
	file_router_proto_goTypes = nil
	file_router_proto_depIdxs = nil
}
