//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: peer.proto

package peer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelId int32

const (
	ChannelId_CHANNEL_ID_SESSION ChannelId = 0
	ChannelId_CHANNEL_ID_SERVICE ChannelId = 1
)

// Enum value maps for ChannelId.
var (
	ChannelId_name = map[int32]string{
		0: "CHANNEL_ID_SESSION",
		1: "CHANNEL_ID_SERVICE",
	}
	ChannelId_value = map[string]int32{
		"CHANNEL_ID_SESSION": 0,
		"CHANNEL_ID_SERVICE": 1,
	}
)

func (x ChannelId) Enum() *ChannelId {
	p := new(ChannelId)
	*p = x
	return p
}

func (x ChannelId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelId) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_proto_enumTypes[0].Descriptor()
}

func (ChannelId) Type() protoreflect.EnumType {
	return &file_peer_proto_enumTypes[0]
}

func (x ChannelId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelId.Descriptor instead.
func (ChannelId) EnumDescriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{0}
}

type SessionType int32

const (
	SessionType_SESSION_TYPE_UNKNOWN         SessionType = 0
	SessionType_SESSION_TYPE_DESKTOP_MANAGE  SessionType = 1
	SessionType_SESSION_TYPE_DESKTOP_VIEW    SessionType = 2
	SessionType_SESSION_TYPE_FILE_TRANSFER   SessionType = 4
	SessionType_SESSION_TYPE_SYSTEM_INFO     SessionType = 8
	SessionType_SESSION_TYPE_TEXT_CHAT       SessionType = 16
	SessionType_SESSION_TYPE_PORT_FORWARDING SessionType = 32
	// When adding or removing session types, you need to recalculate this value.
	SessionType_SESSION_TYPE_ALL SessionType = 63
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0:  "SESSION_TYPE_UNKNOWN",
		1:  "SESSION_TYPE_DESKTOP_MANAGE",
		2:  "SESSION_TYPE_DESKTOP_VIEW",
		4:  "SESSION_TYPE_FILE_TRANSFER",
		8:  "SESSION_TYPE_SYSTEM_INFO",
		16: "SESSION_TYPE_TEXT_CHAT",
		32: "SESSION_TYPE_PORT_FORWARDING",
		63: "SESSION_TYPE_ALL",
	}
	SessionType_value = map[string]int32{
		"SESSION_TYPE_UNKNOWN":         0,
		"SESSION_TYPE_DESKTOP_MANAGE":  1,
		"SESSION_TYPE_DESKTOP_VIEW":    2,
		"SESSION_TYPE_FILE_TRANSFER":   4,
		"SESSION_TYPE_SYSTEM_INFO":     8,
		"SESSION_TYPE_TEXT_CHAT":       16,
		"SESSION_TYPE_PORT_FORWARDING": 32,
		"SESSION_TYPE_ALL":             63,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_proto_enumTypes[1].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_peer_proto_enumTypes[1]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{1}
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         uint32                 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	Revision      uint32                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Version) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Version) GetPatch() uint32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *Version) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_peer_proto protoreflect.FileDescriptor

const file_peer_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"peer.proto\x12\n" +
	"proto.peer\"g\n" +
	"\aVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\rR\x05patch\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\rR\brevision*;\n" +
	"\tChannelId\x12\x16\n" +
	"\x12CHANNEL_ID_SESSION\x10\x00\x12\x16\n" +
	"\x12CHANNEL_ID_SERVICE\x10\x01*\xf9\x01\n" +
	"\vSessionType\x12\x18\n" +
	"\x14SESSION_TYPE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bSESSION_TYPE_DESKTOP_MANAGE\x10\x01\x12\x1d\n" +
	"\x19SESSION_TYPE_DESKTOP_VIEW\x10\x02\x12\x1e\n" +
	"\x1aSESSION_TYPE_FILE_TRANSFER\x10\x04\x12\x1c\n" +
	"\x18SESSION_TYPE_SYSTEM_INFO\x10\b\x12\x1a\n" +
	"\x16SESSION_TYPE_TEXT_CHAT\x10\x10\x12 \n" +
	"\x1cSESSION_TYPE_PORT_FORWARDING\x10 \x12\x14\n" +
	"\x10SESSION_TYPE_ALL\x10?B\x1dH\x03Z\x19aspia_rest_api/proto/peerb\x06proto3"

var (
	file_peer_proto_rawDescOnce sync.Once
	file_peer_proto_rawDescData []byte
)

func file_peer_proto_rawDescGZIP() []byte {
	file_peer_proto_rawDescOnce.Do(func() {
		file_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)))
	})
	return file_peer_proto_rawDescData
}

var file_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_peer_proto_goTypes = []any{
	(ChannelId)(0),   // 0: proto.peer.ChannelId
	(SessionType)(0), // 1: proto.peer.SessionType
	(*Version)(nil),  // 2: proto.peer.Version
}
var file_peer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_peer_proto_init() }
func file_peer_proto_init() {
	if File_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_proto_goTypes,
		DependencyIndexes: file_peer_proto_depIdxs,
		EnumInfos:         file_peer_proto_enumTypes,
		MessageInfos:      file_peer_proto_msgTypes,
	}.Build()
	File_peer_proto = out.File
	file_peer_proto_goTypes = nil
	file_peer_proto_depIdxs = nil
}
