//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: key_exchange.proto

package key_exchange

import (
	peer "aspia_rest_api/proto/peer"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identify int32

const (
	Identify_IDENTIFY_SRP       Identify = 0
	Identify_IDENTIFY_ANONYMOUS Identify = 1
)

// Enum value maps for Identify.
var (
	Identify_name = map[int32]string{
		0: "IDENTIFY_SRP",
		1: "IDENTIFY_ANONYMOUS",
	}
	Identify_value = map[string]int32{
		"IDENTIFY_SRP":       0,
		"IDENTIFY_ANONYMOUS": 1,
	}
)

func (x Identify) Enum() *Identify {
	p := new(Identify)
	*p = x
	return p
}

func (x Identify) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Identify) Descriptor() protoreflect.EnumDescriptor {
	return file_key_exchange_proto_enumTypes[0].Descriptor()
}

func (Identify) Type() protoreflect.EnumType {
	return &file_key_exchange_proto_enumTypes[0]
}

func (x Identify) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Identify.Descriptor instead.
func (Identify) EnumDescriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{0}
}

type Encryption int32

const (
	Encryption_ENCRYPTION_UNKNOWN           Encryption = 0
	Encryption_ENCRYPTION_CHACHA20_POLY1305 Encryption = 1
	Encryption_ENCRYPTION_AES256_GCM        Encryption = 2
)

// Enum value maps for Encryption.
var (
	Encryption_name = map[int32]string{
		0: "ENCRYPTION_UNKNOWN",
		1: "ENCRYPTION_CHACHA20_POLY1305",
		2: "ENCRYPTION_AES256_GCM",
	}
	Encryption_value = map[string]int32{
		"ENCRYPTION_UNKNOWN":           0,
		"ENCRYPTION_CHACHA20_POLY1305": 1,
		"ENCRYPTION_AES256_GCM":        2,
	}
)

func (x Encryption) Enum() *Encryption {
	p := new(Encryption)
	*p = x
	return p
}

func (x Encryption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encryption) Descriptor() protoreflect.EnumDescriptor {
	return file_key_exchange_proto_enumTypes[1].Descriptor()
}

func (Encryption) Type() protoreflect.EnumType {
	return &file_key_exchange_proto_enumTypes[1]
}

func (x Encryption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encryption.Descriptor instead.
func (Encryption) EnumDescriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{1}
}

// Client to server.
type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encryption    uint32                 `protobuf:"varint,1,opt,name=encryption,proto3" json:"encryption,omitempty"`
	Identify      Identify               `protobuf:"varint,2,opt,name=identify,proto3,enum=proto.key_exchange.Identify" json:"identify,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Iv            []byte                 `protobuf:"bytes,4,opt,name=iv,proto3" json:"iv,omitempty"`
	Version       *peer.Version          `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_key_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetEncryption() uint32 {
	if x != nil {
		return x.Encryption
	}
	return 0
}

func (x *ClientHello) GetIdentify() Identify {
	if x != nil {
		return x.Identify
	}
	return Identify_IDENTIFY_SRP
}

func (x *ClientHello) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ClientHello) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *ClientHello) GetVersion() *peer.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

// Server to client.
type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encryption    Encryption             `protobuf:"varint,1,opt,name=encryption,proto3,enum=proto.key_exchange.Encryption" json:"encryption,omitempty"`
	Iv            []byte                 `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	Version       *peer.Version          `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_key_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetEncryption() Encryption {
	if x != nil {
		return x.Encryption
	}
	return Encryption_ENCRYPTION_UNKNOWN
}

func (x *ServerHello) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *ServerHello) GetVersion() *peer.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

// Client to server.
type SrpIdentify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SrpIdentify) Reset() {
	*x = SrpIdentify{}
	mi := &file_key_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SrpIdentify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrpIdentify) ProtoMessage() {}

func (x *SrpIdentify) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrpIdentify.ProtoReflect.Descriptor instead.
func (*SrpIdentify) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *SrpIdentify) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Server to client.
type SrpServerKeyExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        []byte                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Generator     []byte                 `protobuf:"bytes,2,opt,name=generator,proto3" json:"generator,omitempty"`
	Salt          []byte                 `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	B             []byte                 `protobuf:"bytes,4,opt,name=B,proto3" json:"B,omitempty"`
	Iv            []byte                 `protobuf:"bytes,5,opt,name=iv,proto3" json:"iv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SrpServerKeyExchange) Reset() {
	*x = SrpServerKeyExchange{}
	mi := &file_key_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SrpServerKeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrpServerKeyExchange) ProtoMessage() {}

func (x *SrpServerKeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrpServerKeyExchange.ProtoReflect.Descriptor instead.
func (*SrpServerKeyExchange) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *SrpServerKeyExchange) GetNumber() []byte {
	if x != nil {
		return x.Number
	}
	return nil
}

func (x *SrpServerKeyExchange) GetGenerator() []byte {
	if x != nil {
		return x.Generator
	}
	return nil
}

func (x *SrpServerKeyExchange) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *SrpServerKeyExchange) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *SrpServerKeyExchange) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

// Client to server.
type SrpClientKeyExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             []byte                 `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	Iv            []byte                 `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SrpClientKeyExchange) Reset() {
	*x = SrpClientKeyExchange{}
	mi := &file_key_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SrpClientKeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SrpClientKeyExchange) ProtoMessage() {}

func (x *SrpClientKeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SrpClientKeyExchange.ProtoReflect.Descriptor instead.
func (*SrpClientKeyExchange) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *SrpClientKeyExchange) GetA() []byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *SrpClientKeyExchange) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

// Server to client.
type SessionChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *peer.Version          `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Deprecated since version 3.0.0. For backward compatibility only.
	SessionTypes  uint32                 `protobuf:"varint,2,opt,name=session_types,json=sessionTypes,proto3" json:"session_types,omitempty"`
	CpuCores      uint32                 `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	OsName        string                 `protobuf:"bytes,4,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	ComputerName  string                 `protobuf:"bytes,5,opt,name=computer_name,json=computerName,proto3" json:"computer_name,omitempty"`
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	DisplayName   string                 `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionChallenge) Reset() {
	*x = SessionChallenge{}
	mi := &file_key_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionChallenge) ProtoMessage() {}

func (x *SessionChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionChallenge.ProtoReflect.Descriptor instead.
func (*SessionChallenge) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *SessionChallenge) GetVersion() *peer.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SessionChallenge) GetSessionTypes() uint32 {
	if x != nil {
		return x.SessionTypes
	}
	return 0
}

func (x *SessionChallenge) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SessionChallenge) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *SessionChallenge) GetComputerName() string {
	if x != nil {
		return x.ComputerName
	}
	return ""
}

func (x *SessionChallenge) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SessionChallenge) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// Client to server.
type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *peer.Version          `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Deprecated since version 3.0.0. For backward compatibility only.
	SessionType   uint32                 `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	CpuCores      uint32                 `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	OsName        string                 `protobuf:"bytes,4,opt,name=os_name,json=osName,proto3" json:"os_name,omitempty"`
	ComputerName  string                 `protobuf:"bytes,5,opt,name=computer_name,json=computerName,proto3" json:"computer_name,omitempty"`
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	DisplayName   string                 `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_key_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_key_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *SessionResponse) GetVersion() *peer.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SessionResponse) GetSessionType() uint32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *SessionResponse) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SessionResponse) GetOsName() string {
	if x != nil {
		return x.OsName
	}
	return ""
}

func (x *SessionResponse) GetComputerName() string {
	if x != nil {
		return x.ComputerName
	}
	return ""
}

func (x *SessionResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SessionResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_key_exchange_proto protoreflect.FileDescriptor

const file_key_exchange_proto_rawDesc = "" +
	"\n" +
	"\x12key_exchange.proto\x12\x12proto.key_exchange\x1a\n" +
	"peer.proto\"\xc5\x01\n" +
	"\vClientHello\x12\x1e\n" +
	"\n" +
	"encryption\x18\x01 \x01(\rR\n" +
	"encryption\x128\n" +
	"\bidentify\x18\x02 \x01(\x0e2\x1c.proto.key_exchange.IdentifyR\bidentify\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x0e\n" +
	"\x02iv\x18\x04 \x01(\fR\x02iv\x12-\n" +
	"\aversion\x18\x05 \x01(\v2\x13.proto.peer.VersionR\aversion\"\x8c\x01\n" +
	"\vServerHello\x12>\n" +
	"\n" +
	"encryption\x18\x01 \x01(\x0e2\x1e.proto.key_exchange.EncryptionR\n" +
	"encryption\x12\x0e\n" +
	"\x02iv\x18\x02 \x01(\fR\x02iv\x12-\n" +
	"\aversion\x18\x03 \x01(\v2\x13.proto.peer.VersionR\aversion\")\n" +
	"\vSrpIdentify\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"~\n" +
	"\x14SrpServerKeyExchange\x12\x16\n" +
	"\x06number\x18\x01 \x01(\fR\x06number\x12\x1c\n" +
	"\tgenerator\x18\x02 \x01(\fR\tgenerator\x12\x12\n" +
	"\x04salt\x18\x03 \x01(\fR\x04salt\x12\f\n" +
	"\x01B\x18\x04 \x01(\fR\x01B\x12\x0e\n" +
	"\x02iv\x18\x05 \x01(\fR\x02iv\"4\n" +
	"\x14SrpClientKeyExchange\x12\f\n" +
	"\x01A\x18\x01 \x01(\fR\x01A\x12\x0e\n" +
	"\x02iv\x18\x02 \x01(\fR\x02iv\"\xf8\x01\n" +
	"\x10SessionChallenge\x12-\n" +
	"\aversion\x18\x01 \x01(\v2\x13.proto.peer.VersionR\aversion\x12#\n" +
	"\rsession_types\x18\x02 \x01(\rR\fsessionTypes\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\rR\bcpuCores\x12\x17\n" +
	"\aos_name\x18\x04 \x01(\tR\x06osName\x12#\n" +
	"\rcomputer_name\x18\x05 \x01(\tR\fcomputerName\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\"\xf5\x01\n" +
	"\x0fSessionResponse\x12-\n" +
	"\aversion\x18\x01 \x01(\v2\x13.proto.peer.VersionR\aversion\x12!\n" +
	"\fsession_type\x18\x02 \x01(\rR\vsessionType\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\rR\bcpuCores\x12\x17\n" +
	"\aos_name\x18\x04 \x01(\tR\x06osName\x12#\n" +
	"\rcomputer_name\x18\x05 \x01(\tR\fcomputerName\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName*4\n" +
	"\bIdentify\x12\x10\n" +
	"\fIDENTIFY_SRP\x10\x00\x12\x16\n" +
	"\x12IDENTIFY_ANONYMOUS\x10\x01*a\n" +
	"\n" +
	"Encryption\x12\x16\n" +
	"\x12ENCRYPTION_UNKNOWN\x10\x00\x12 \n" +
	"\x1cENCRYPTION_CHACHA20_POLY1305\x10\x01\x12\x19\n" +
	"\x15ENCRYPTION_AES256_GCM\x10\x02B%H\x03Z!aspia_rest_api/proto/key_exchangeb\x06proto3"

var (
	file_key_exchange_proto_rawDescOnce sync.Once
	file_key_exchange_proto_rawDescData []byte
)

func file_key_exchange_proto_rawDescGZIP() []byte {
	file_key_exchange_proto_rawDescOnce.Do(func() {
		file_key_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_exchange_proto_rawDesc), len(file_key_exchange_proto_rawDesc)))
	})
	return file_key_exchange_proto_rawDescData
}

var file_key_exchange_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_key_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_key_exchange_proto_goTypes = []any{
	(Identify)(0),                // 0: proto.key_exchange.Identify
	(Encryption)(0),              // 1: proto.key_exchange.Encryption
	(*ClientHello)(nil),          // 2: proto.key_exchange.ClientHello
	(*ServerHello)(nil),          // 3: proto.key_exchange.ServerHello
	(*SrpIdentify)(nil),          // 4: proto.key_exchange.SrpIdentify
	(*SrpServerKeyExchange)(nil), // 5: proto.key_exchange.SrpServerKeyExchange
	(*SrpClientKeyExchange)(nil), // 6: proto.key_exchange.SrpClientKeyExchange
	(*SessionChallenge)(nil),     // 7: proto.key_exchange.SessionChallenge
	(*SessionResponse)(nil),      // 8: proto.key_exchange.SessionResponse
	(*peer.Version)(nil),         // 9: proto.peer.Version
}
var file_key_exchange_proto_depIdxs = []int32{
	0, // 0: proto.key_exchange.ClientHello.identify:type_name -> proto.key_exchange.Identify
	9, // 1: proto.key_exchange.ClientHello.version:type_name -> proto.peer.Version
	1, // 2: proto.key_exchange.ServerHello.encryption:type_name -> proto.key_exchange.Encryption
	9, // 3: proto.key_exchange.ServerHello.version:type_name -> proto.peer.Version
	9, // 4: proto.key_exchange.SessionChallenge.version:type_name -> proto.peer.Version
	9, // 5: proto.key_exchange.SessionResponse.version:type_name -> proto.peer.Version
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_key_exchange_proto_init() }
func file_key_exchange_proto_init() {
	if File_key_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_exchange_proto_rawDesc), len(file_key_exchange_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_key_exchange_proto_goTypes,
		DependencyIndexes: file_key_exchange_proto_depIdxs,
		EnumInfos:         file_key_exchange_proto_enumTypes,
		MessageInfos:      file_key_exchange_proto_msgTypes,
	}.Build()
	File_key_exchange_proto = out.File
	file_key_exchange_proto_goTypes = nil
	file_key_exchange_proto_depIdxs = nil
}
