//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: text_chat.proto

package text_chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status_Code int32

const (
	Status_CODE_UNKNOWN           Status_Code = 0
	Status_CODE_STARTED           Status_Code = 1
	Status_CODE_STOPPED           Status_Code = 2
	Status_CODE_TYPING            Status_Code = 3
	Status_CODE_USER_DISCONNECTED Status_Code = 4
	Status_CODE_USER_CONNECTED    Status_Code = 5
)

// Enum value maps for Status_Code.
var (
	Status_Code_name = map[int32]string{
		0: "CODE_UNKNOWN",
		1: "CODE_STARTED",
		2: "CODE_STOPPED",
		3: "CODE_TYPING",
		4: "CODE_USER_DISCONNECTED",
		5: "CODE_USER_CONNECTED",
	}
	Status_Code_value = map[string]int32{
		"CODE_UNKNOWN":           0,
		"CODE_STARTED":           1,
		"CODE_STOPPED":           2,
		"CODE_TYPING":            3,
		"CODE_USER_DISCONNECTED": 4,
		"CODE_USER_CONNECTED":    5,
	}
)

func (x Status_Code) Enum() *Status_Code {
	p := new(Status_Code)
	*p = x
	return p
}

func (x Status_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_text_chat_proto_enumTypes[0].Descriptor()
}

func (Status_Code) Type() protoreflect.EnumType {
	return &file_text_chat_proto_enumTypes[0]
}

func (x Status_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_Code.Descriptor instead.
func (Status_Code) EnumDescriptor() ([]byte, []int) {
	return file_text_chat_proto_rawDescGZIP(), []int{0, 0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Code          Status_Code            `protobuf:"varint,4,opt,name=code,proto3,enum=proto.text_chat.Status_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_text_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_text_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_text_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Status) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Status) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Status) GetCode() Status_Code {
	if x != nil {
		return x.Code
	}
	return Status_CODE_UNKNOWN
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_text_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_text_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_text_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Message) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatStatus    *Status                `protobuf:"bytes,1,opt,name=chat_status,json=chatStatus,proto3" json:"chat_status,omitempty"`
	ChatMessage   *Message               `protobuf:"bytes,2,opt,name=chat_message,json=chatMessage,proto3" json:"chat_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChat) Reset() {
	*x = TextChat{}
	mi := &file_text_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChat) ProtoMessage() {}

func (x *TextChat) ProtoReflect() protoreflect.Message {
	mi := &file_text_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChat.ProtoReflect.Descriptor instead.
func (*TextChat) Descriptor() ([]byte, []int) {
	return file_text_chat_proto_rawDescGZIP(), []int{2}
}

func (x *TextChat) GetChatStatus() *Status {
	if x != nil {
		return x.ChatStatus
	}
	return nil
}

func (x *TextChat) GetChatMessage() *Message {
	if x != nil {
		return x.ChatMessage
	}
	return nil
}

var File_text_chat_proto protoreflect.FileDescriptor

const file_text_chat_proto_rawDesc = "" +
	"\n" +
	"\x0ftext_chat.proto\x12\x0fproto.text_chat\"\x8d\x02\n" +
	"\x06Status\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x120\n" +
	"\x04code\x18\x04 \x01(\x0e2\x1c.proto.text_chat.Status.CodeR\x04code\"\x82\x01\n" +
	"\x04Code\x12\x10\n" +
	"\fCODE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fCODE_STARTED\x10\x01\x12\x10\n" +
	"\fCODE_STOPPED\x10\x02\x12\x0f\n" +
	"\vCODE_TYPING\x10\x03\x12\x1a\n" +
	"\x16CODE_USER_DISCONNECTED\x10\x04\x12\x17\n" +
	"\x13CODE_USER_CONNECTED\x10\x05\"k\n" +
	"\aMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\x81\x01\n" +
	"\bTextChat\x128\n" +
	"\vchat_status\x18\x01 \x01(\v2\x17.proto.text_chat.StatusR\n" +
	"chatStatus\x12;\n" +
	"\fchat_message\x18\x02 \x01(\v2\x18.proto.text_chat.MessageR\vchatMessageB\"H\x03Z\x1easpia_rest_api/proto/text_chatb\x06proto3"

var (
	file_text_chat_proto_rawDescOnce sync.Once
	file_text_chat_proto_rawDescData []byte
)

func file_text_chat_proto_rawDescGZIP() []byte {
	file_text_chat_proto_rawDescOnce.Do(func() {
		file_text_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_text_chat_proto_rawDesc), len(file_text_chat_proto_rawDesc)))
	})
	return file_text_chat_proto_rawDescData
}

var file_text_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_text_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_text_chat_proto_goTypes = []any{
	(Status_Code)(0), // 0: proto.text_chat.Status.Code
	(*Status)(nil),   // 1: proto.text_chat.Status
	(*Message)(nil),  // 2: proto.text_chat.Message
	(*TextChat)(nil), // 3: proto.text_chat.TextChat
}
var file_text_chat_proto_depIdxs = []int32{
	0, // 0: proto.text_chat.Status.code:type_name -> proto.text_chat.Status.Code
	1, // 1: proto.text_chat.TextChat.chat_status:type_name -> proto.text_chat.Status
	2, // 2: proto.text_chat.TextChat.chat_message:type_name -> proto.text_chat.Message
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_text_chat_proto_init() }
func file_text_chat_proto_init() {
	if File_text_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_text_chat_proto_rawDesc), len(file_text_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_text_chat_proto_goTypes,
		DependencyIndexes: file_text_chat_proto_depIdxs,
		EnumInfos:         file_text_chat_proto_enumTypes,
		MessageInfos:      file_text_chat_proto_msgTypes,
	}.Build()
	File_text_chat_proto = out.File
	file_text_chat_proto_goTypes = nil
	file_text_chat_proto_depIdxs = nil
}
