//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: address_book.proto

package address_book

import (
	desktop "aspia_rest_api/proto/desktop"
	peer "aspia_rest_api/proto/peer"
	port_forwarding "aspia_rest_api/proto/port_forwarding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptionType int32

const (
	EncryptionType_ENCRYPTION_TYPE_UNKNOWN            EncryptionType = 0
	EncryptionType_ENCRYPTION_TYPE_NONE               EncryptionType = 1
	EncryptionType_ENCRYPTION_TYPE_XCHACHA20_POLY1305 EncryptionType = 2
	EncryptionType_ENCRYPTION_TYPE_CHACHA20_POLY1305  EncryptionType = 3
)

// Enum value maps for EncryptionType.
var (
	EncryptionType_name = map[int32]string{
		0: "ENCRYPTION_TYPE_UNKNOWN",
		1: "ENCRYPTION_TYPE_NONE",
		2: "ENCRYPTION_TYPE_XCHACHA20_POLY1305",
		3: "ENCRYPTION_TYPE_CHACHA20_POLY1305",
	}
	EncryptionType_value = map[string]int32{
		"ENCRYPTION_TYPE_UNKNOWN":            0,
		"ENCRYPTION_TYPE_NONE":               1,
		"ENCRYPTION_TYPE_XCHACHA20_POLY1305": 2,
		"ENCRYPTION_TYPE_CHACHA20_POLY1305":  3,
	}
)

func (x EncryptionType) Enum() *EncryptionType {
	p := new(EncryptionType)
	*p = x
	return p
}

func (x EncryptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_address_book_proto_enumTypes[0].Descriptor()
}

func (EncryptionType) Type() protoreflect.EnumType {
	return &file_address_book_proto_enumTypes[0]
}

func (x EncryptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionType.Descriptor instead.
func (EncryptionType) EnumDescriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{0}
}

type SessionConfig struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	DesktopManage  *desktop.Config         `protobuf:"bytes,1,opt,name=desktop_manage,json=desktopManage,proto3" json:"desktop_manage,omitempty"`
	DesktopView    *desktop.Config         `protobuf:"bytes,2,opt,name=desktop_view,json=desktopView,proto3" json:"desktop_view,omitempty"`
	PortForwarding *port_forwarding.Config `protobuf:"bytes,3,opt,name=port_forwarding,json=portForwarding,proto3" json:"port_forwarding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_address_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_address_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{0}
}

func (x *SessionConfig) GetDesktopManage() *desktop.Config {
	if x != nil {
		return x.DesktopManage
	}
	return nil
}

func (x *SessionConfig) GetDesktopView() *desktop.Config {
	if x != nil {
		return x.DesktopView
	}
	return nil
}

func (x *SessionConfig) GetPortForwarding() *port_forwarding.Config {
	if x != nil {
		return x.PortForwarding
	}
	return nil
}

type InheritConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credentials    bool                   `protobuf:"varint,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	DesktopManage  bool                   `protobuf:"varint,2,opt,name=desktop_manage,json=desktopManage,proto3" json:"desktop_manage,omitempty"`
	DesktopView    bool                   `protobuf:"varint,3,opt,name=desktop_view,json=desktopView,proto3" json:"desktop_view,omitempty"`
	PortForwarding bool                   `protobuf:"varint,4,opt,name=port_forwarding,json=portForwarding,proto3" json:"port_forwarding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InheritConfig) Reset() {
	*x = InheritConfig{}
	mi := &file_address_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InheritConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InheritConfig) ProtoMessage() {}

func (x *InheritConfig) ProtoReflect() protoreflect.Message {
	mi := &file_address_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InheritConfig.ProtoReflect.Descriptor instead.
func (*InheritConfig) Descriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{1}
}

func (x *InheritConfig) GetCredentials() bool {
	if x != nil {
		return x.Credentials
	}
	return false
}

func (x *InheritConfig) GetDesktopManage() bool {
	if x != nil {
		return x.DesktopManage
	}
	return false
}

func (x *InheritConfig) GetDesktopView() bool {
	if x != nil {
		return x.DesktopView
	}
	return false
}

func (x *InheritConfig) GetPortForwarding() bool {
	if x != nil {
		return x.PortForwarding
	}
	return false
}

type Computer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CreateTime int64                  `protobuf:"varint,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModifyTime int64                  `protobuf:"varint,2,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"` // Field 3 not used (deprecated).
	Name       string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Comment    string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Address    string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Port       uint32                 `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	Username   string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Password   string                 `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	Inherit    *InheritConfig         `protobuf:"bytes,12,opt,name=inherit,proto3" json:"inherit,omitempty"`
	// Session configurations.
	SessionType   peer.SessionType `protobuf:"varint,16,opt,name=session_type,json=sessionType,proto3,enum=proto.peer.SessionType" json:"session_type,omitempty"`
	SessionConfig *SessionConfig   `protobuf:"bytes,17,opt,name=session_config,json=sessionConfig,proto3" json:"session_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Computer) Reset() {
	*x = Computer{}
	mi := &file_address_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Computer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Computer) ProtoMessage() {}

func (x *Computer) ProtoReflect() protoreflect.Message {
	mi := &file_address_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Computer.ProtoReflect.Descriptor instead.
func (*Computer) Descriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{2}
}

func (x *Computer) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Computer) GetModifyTime() int64 {
	if x != nil {
		return x.ModifyTime
	}
	return 0
}

func (x *Computer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Computer) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Computer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Computer) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Computer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Computer) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Computer) GetInherit() *InheritConfig {
	if x != nil {
		return x.Inherit
	}
	return nil
}

func (x *Computer) GetSessionType() peer.SessionType {
	if x != nil {
		return x.SessionType
	}
	return peer.SessionType(0)
}

func (x *Computer) GetSessionConfig() *SessionConfig {
	if x != nil {
		return x.SessionConfig
	}
	return nil
}

type ComputerGroupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inherit       *InheritConfig         `protobuf:"bytes,1,opt,name=inherit,proto3" json:"inherit,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	SessionConfig *SessionConfig         `protobuf:"bytes,21,opt,name=session_config,json=sessionConfig,proto3" json:"session_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerGroupConfig) Reset() {
	*x = ComputerGroupConfig{}
	mi := &file_address_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerGroupConfig) ProtoMessage() {}

func (x *ComputerGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_address_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerGroupConfig.ProtoReflect.Descriptor instead.
func (*ComputerGroupConfig) Descriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{3}
}

func (x *ComputerGroupConfig) GetInherit() *InheritConfig {
	if x != nil {
		return x.Inherit
	}
	return nil
}

func (x *ComputerGroupConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ComputerGroupConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ComputerGroupConfig) GetSessionConfig() *SessionConfig {
	if x != nil {
		return x.SessionConfig
	}
	return nil
}

type ComputerGroup struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CreateTime int64                  `protobuf:"varint,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModifyTime int64                  `protobuf:"varint,2,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	// List of child computers.
	Computer []*Computer `protobuf:"bytes,3,rep,name=computer,proto3" json:"computer,omitempty"`
	// List of child computer groups.
	ComputerGroup []*ComputerGroup     `protobuf:"bytes,4,rep,name=computer_group,json=computerGroup,proto3" json:"computer_group,omitempty"`
	Name          string               `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string               `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Expanded      bool                 `protobuf:"varint,7,opt,name=expanded,proto3" json:"expanded,omitempty"`
	Config        *ComputerGroupConfig `protobuf:"bytes,21,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerGroup) Reset() {
	*x = ComputerGroup{}
	mi := &file_address_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerGroup) ProtoMessage() {}

func (x *ComputerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_address_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerGroup.ProtoReflect.Descriptor instead.
func (*ComputerGroup) Descriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{4}
}

func (x *ComputerGroup) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ComputerGroup) GetModifyTime() int64 {
	if x != nil {
		return x.ModifyTime
	}
	return 0
}

func (x *ComputerGroup) GetComputer() []*Computer {
	if x != nil {
		return x.Computer
	}
	return nil
}

func (x *ComputerGroup) GetComputerGroup() []*ComputerGroup {
	if x != nil {
		return x.ComputerGroup
	}
	return nil
}

func (x *ComputerGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComputerGroup) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ComputerGroup) GetExpanded() bool {
	if x != nil {
		return x.Expanded
	}
	return false
}

func (x *ComputerGroup) GetConfig() *ComputerGroupConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type Router struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Router) Reset() {
	*x = Router{}
	mi := &file_address_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Router) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Router) ProtoMessage() {}

func (x *Router) ProtoReflect() protoreflect.Message {
	mi := &file_address_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Router.ProtoReflect.Descriptor instead.
func (*Router) Descriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{5}
}

func (x *Router) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Router) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Router) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Router) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field 1 - Deprecated.
	RootGroup *ComputerGroup `protobuf:"bytes,2,opt,name=root_group,json=rootGroup,proto3" json:"root_group,omitempty"` // Field 3 - Deprecated.
	// Enable or disable router.
	EnableRouter bool `protobuf:"varint,4,opt,name=enable_router,json=enableRouter,proto3" json:"enable_router,omitempty"`
	// Connection parameters for the router.
	Router *Router `protobuf:"bytes,5,opt,name=router,proto3" json:"router,omitempty"`
	// Unique GUID for address book.
	Guid string `protobuf:"bytes,6,opt,name=guid,proto3" json:"guid,omitempty"`
	// Display name when connected.
	DisplayName   string `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_address_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_address_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{6}
}

func (x *Data) GetRootGroup() *ComputerGroup {
	if x != nil {
		return x.RootGroup
	}
	return nil
}

func (x *Data) GetEnableRouter() bool {
	if x != nil {
		return x.EnableRouter
	}
	return false
}

func (x *Data) GetRouter() *Router {
	if x != nil {
		return x.Router
	}
	return nil
}

func (x *Data) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *Data) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encryption type.
	EncryptionType EncryptionType `protobuf:"varint,1,opt,name=encryption_type,json=encryptionType,proto3,enum=proto.address_book.EncryptionType" json:"encryption_type,omitempty"`
	// If encryption is enabled, contains salt (random data), which are added at each iteration
	// of the hashing to create the key.
	// When the encryption is disabled, the field is not used.
	HashingSalt []byte `protobuf:"bytes,3,opt,name=hashing_salt,json=hashingSalt,proto3" json:"hashing_salt,omitempty"`
	// If the encryption is enabled, it contains serialized and encrypted |Data|.
	// If the encryption is disabled, it contains a serialized |Data|.
	Data          []byte `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_address_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_address_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_address_book_proto_rawDescGZIP(), []int{7}
}

func (x *File) GetEncryptionType() EncryptionType {
	if x != nil {
		return x.EncryptionType
	}
	return EncryptionType_ENCRYPTION_TYPE_UNKNOWN
}

func (x *File) GetHashingSalt() []byte {
	if x != nil {
		return x.HashingSalt
	}
	return nil
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_address_book_proto protoreflect.FileDescriptor

const file_address_book_proto_rawDesc = "" +
	"\n" +
	"\x12address_book.proto\x12\x12proto.address_book\x1a\rdesktop.proto\x1a\n" +
	"peer.proto\x1a\x15port_forwarding.proto\"\xcf\x01\n" +
	"\rSessionConfig\x12<\n" +
	"\x0edesktop_manage\x18\x01 \x01(\v2\x15.proto.desktop.ConfigR\rdesktopManage\x128\n" +
	"\fdesktop_view\x18\x02 \x01(\v2\x15.proto.desktop.ConfigR\vdesktopView\x12F\n" +
	"\x0fport_forwarding\x18\x03 \x01(\v2\x1d.proto.port_forwarding.ConfigR\x0eportForwarding\"\xa4\x01\n" +
	"\rInheritConfig\x12 \n" +
	"\vcredentials\x18\x01 \x01(\bR\vcredentials\x12%\n" +
	"\x0edesktop_manage\x18\x02 \x01(\bR\rdesktopManage\x12!\n" +
	"\fdesktop_view\x18\x03 \x01(\bR\vdesktopView\x12'\n" +
	"\x0fport_forwarding\x18\x04 \x01(\bR\x0eportForwarding\"\xa3\x03\n" +
	"\bComputer\x12\x1f\n" +
	"\vcreate_time\x18\x01 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vmodify_time\x18\x02 \x01(\x03R\n" +
	"modifyTime\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\a \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\t \x01(\tR\bpassword\x12;\n" +
	"\ainherit\x18\f \x01(\v2!.proto.address_book.InheritConfigR\ainherit\x12:\n" +
	"\fsession_type\x18\x10 \x01(\x0e2\x17.proto.peer.SessionTypeR\vsessionType\x12H\n" +
	"\x0esession_config\x18\x11 \x01(\v2!.proto.address_book.SessionConfigR\rsessionConfig\"\xd4\x01\n" +
	"\x13ComputerGroupConfig\x12;\n" +
	"\ainherit\x18\x01 \x01(\v2!.proto.address_book.InheritConfigR\ainherit\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12H\n" +
	"\x0esession_config\x18\x15 \x01(\v2!.proto.address_book.SessionConfigR\rsessionConfig\"\xe0\x02\n" +
	"\rComputerGroup\x12\x1f\n" +
	"\vcreate_time\x18\x01 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vmodify_time\x18\x02 \x01(\x03R\n" +
	"modifyTime\x128\n" +
	"\bcomputer\x18\x03 \x03(\v2\x1c.proto.address_book.ComputerR\bcomputer\x12H\n" +
	"\x0ecomputer_group\x18\x04 \x03(\v2!.proto.address_book.ComputerGroupR\rcomputerGroup\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x1a\n" +
	"\bexpanded\x18\a \x01(\bR\bexpanded\x12?\n" +
	"\x06config\x18\x15 \x01(\v2'.proto.address_book.ComputerGroupConfigR\x06config\"n\n" +
	"\x06Router\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\xd8\x01\n" +
	"\x04Data\x12@\n" +
	"\n" +
	"root_group\x18\x02 \x01(\v2!.proto.address_book.ComputerGroupR\trootGroup\x12#\n" +
	"\renable_router\x18\x04 \x01(\bR\fenableRouter\x122\n" +
	"\x06router\x18\x05 \x01(\v2\x1a.proto.address_book.RouterR\x06router\x12\x12\n" +
	"\x04guid\x18\x06 \x01(\tR\x04guid\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\"\x8a\x01\n" +
	"\x04File\x12K\n" +
	"\x0fencryption_type\x18\x01 \x01(\x0e2\".proto.address_book.EncryptionTypeR\x0eencryptionType\x12!\n" +
	"\fhashing_salt\x18\x03 \x01(\fR\vhashingSalt\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data*\x96\x01\n" +
	"\x0eEncryptionType\x12\x1b\n" +
	"\x17ENCRYPTION_TYPE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14ENCRYPTION_TYPE_NONE\x10\x01\x12&\n" +
	"\"ENCRYPTION_TYPE_XCHACHA20_POLY1305\x10\x02\x12%\n" +
	"!ENCRYPTION_TYPE_CHACHA20_POLY1305\x10\x03B%H\x03Z!aspia_rest_api/proto/address_bookb\x06proto3"

var (
	file_address_book_proto_rawDescOnce sync.Once
	file_address_book_proto_rawDescData []byte
)

func file_address_book_proto_rawDescGZIP() []byte {
	file_address_book_proto_rawDescOnce.Do(func() {
		file_address_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_address_book_proto_rawDesc), len(file_address_book_proto_rawDesc)))
	})
	return file_address_book_proto_rawDescData
}

var file_address_book_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_address_book_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_address_book_proto_goTypes = []any{
	(EncryptionType)(0),            // 0: proto.address_book.EncryptionType
	(*SessionConfig)(nil),          // 1: proto.address_book.SessionConfig
	(*InheritConfig)(nil),          // 2: proto.address_book.InheritConfig
	(*Computer)(nil),               // 3: proto.address_book.Computer
	(*ComputerGroupConfig)(nil),    // 4: proto.address_book.ComputerGroupConfig
	(*ComputerGroup)(nil),          // 5: proto.address_book.ComputerGroup
	(*Router)(nil),                 // 6: proto.address_book.Router
	(*Data)(nil),                   // 7: proto.address_book.Data
	(*File)(nil),                   // 8: proto.address_book.File
	(*desktop.Config)(nil),         // 9: proto.desktop.Config
	(*port_forwarding.Config)(nil), // 10: proto.port_forwarding.Config
	(peer.SessionType)(0),          // 11: proto.peer.SessionType
}
var file_address_book_proto_depIdxs = []int32{
	9,  // 0: proto.address_book.SessionConfig.desktop_manage:type_name -> proto.desktop.Config
	9,  // 1: proto.address_book.SessionConfig.desktop_view:type_name -> proto.desktop.Config
	10, // 2: proto.address_book.SessionConfig.port_forwarding:type_name -> proto.port_forwarding.Config
	2,  // 3: proto.address_book.Computer.inherit:type_name -> proto.address_book.InheritConfig
	11, // 4: proto.address_book.Computer.session_type:type_name -> proto.peer.SessionType
	1,  // 5: proto.address_book.Computer.session_config:type_name -> proto.address_book.SessionConfig
	2,  // 6: proto.address_book.ComputerGroupConfig.inherit:type_name -> proto.address_book.InheritConfig
	1,  // 7: proto.address_book.ComputerGroupConfig.session_config:type_name -> proto.address_book.SessionConfig
	3,  // 8: proto.address_book.ComputerGroup.computer:type_name -> proto.address_book.Computer
	5,  // 9: proto.address_book.ComputerGroup.computer_group:type_name -> proto.address_book.ComputerGroup
	4,  // 10: proto.address_book.ComputerGroup.config:type_name -> proto.address_book.ComputerGroupConfig
	5,  // 11: proto.address_book.Data.root_group:type_name -> proto.address_book.ComputerGroup
	6,  // 12: proto.address_book.Data.router:type_name -> proto.address_book.Router
	0,  // 13: proto.address_book.File.encryption_type:type_name -> proto.address_book.EncryptionType
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_address_book_proto_init() }
func file_address_book_proto_init() {
	if File_address_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_address_book_proto_rawDesc), len(file_address_book_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_address_book_proto_goTypes,
		DependencyIndexes: file_address_book_proto_depIdxs,
		EnumInfos:         file_address_book_proto_enumTypes,
		MessageInfos:      file_address_book_proto_msgTypes,
	}.Build()
	File_address_book_proto = out.File
	file_address_book_proto_goTypes = nil
	file_address_book_proto_depIdxs = nil
}
