//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// WARNING! For internal use only, on the host side. Messages in this file are not intended for
// transmission over the network.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: host_internal.proto

package host_internal

import (
	peer "aspia_rest_api/proto/peer"
	text_chat "aspia_rest_api/proto/text_chat"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialsRequest_Type int32

const (
	CredentialsRequest_UNKNOWN_TYPE CredentialsRequest_Type = 0
	CredentialsRequest_REFRESH      CredentialsRequest_Type = 1
	CredentialsRequest_NEW_PASSWORD CredentialsRequest_Type = 2
)

// Enum value maps for CredentialsRequest_Type.
var (
	CredentialsRequest_Type_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "REFRESH",
		2: "NEW_PASSWORD",
	}
	CredentialsRequest_Type_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"REFRESH":      1,
		"NEW_PASSWORD": 2,
	}
)

func (x CredentialsRequest_Type) Enum() *CredentialsRequest_Type {
	p := new(CredentialsRequest_Type)
	*p = x
	return p
}

func (x CredentialsRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialsRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_host_internal_proto_enumTypes[0].Descriptor()
}

func (CredentialsRequest_Type) Type() protoreflect.EnumType {
	return &file_host_internal_proto_enumTypes[0]
}

func (x CredentialsRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialsRequest_Type.Descriptor instead.
func (CredentialsRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{0, 0}
}

type RouterState_State int32

const (
	RouterState_UNKNOWN    RouterState_State = 0
	RouterState_DISABLED   RouterState_State = 1
	RouterState_CONNECTING RouterState_State = 2
	RouterState_CONNECTED  RouterState_State = 3
	RouterState_FAILED     RouterState_State = 4
)

// Enum value maps for RouterState_State.
var (
	RouterState_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "DISABLED",
		2: "CONNECTING",
		3: "CONNECTED",
		4: "FAILED",
	}
	RouterState_State_value = map[string]int32{
		"UNKNOWN":    0,
		"DISABLED":   1,
		"CONNECTING": 2,
		"CONNECTED":  3,
		"FAILED":     4,
	}
)

func (x RouterState_State) Enum() *RouterState_State {
	p := new(RouterState_State)
	*p = x
	return p
}

func (x RouterState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouterState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_host_internal_proto_enumTypes[1].Descriptor()
}

func (RouterState_State) Type() protoreflect.EnumType {
	return &file_host_internal_proto_enumTypes[1]
}

func (x RouterState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouterState_State.Descriptor instead.
func (RouterState_State) EnumDescriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{5, 0}
}

type ServiceControl_Code int32

const (
	ServiceControl_CODE_UNKNOWN       ServiceControl_Code = 0
	ServiceControl_CODE_KILL          ServiceControl_Code = 1
	ServiceControl_CODE_PAUSE         ServiceControl_Code = 2
	ServiceControl_CODE_LOCK_MOUSE    ServiceControl_Code = 3
	ServiceControl_CODE_LOCK_KEYBOARD ServiceControl_Code = 4
	ServiceControl_CODE_VOICE_CHAT    ServiceControl_Code = 5
)

// Enum value maps for ServiceControl_Code.
var (
	ServiceControl_Code_name = map[int32]string{
		0: "CODE_UNKNOWN",
		1: "CODE_KILL",
		2: "CODE_PAUSE",
		3: "CODE_LOCK_MOUSE",
		4: "CODE_LOCK_KEYBOARD",
		5: "CODE_VOICE_CHAT",
	}
	ServiceControl_Code_value = map[string]int32{
		"CODE_UNKNOWN":       0,
		"CODE_KILL":          1,
		"CODE_PAUSE":         2,
		"CODE_LOCK_MOUSE":    3,
		"CODE_LOCK_KEYBOARD": 4,
		"CODE_VOICE_CHAT":    5,
	}
)

func (x ServiceControl_Code) Enum() *ServiceControl_Code {
	p := new(ServiceControl_Code)
	*p = x
	return p
}

func (x ServiceControl_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceControl_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_host_internal_proto_enumTypes[2].Descriptor()
}

func (ServiceControl_Code) Type() protoreflect.EnumType {
	return &file_host_internal_proto_enumTypes[2]
}

func (x ServiceControl_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceControl_Code.Descriptor instead.
func (ServiceControl_Code) EnumDescriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{8, 0}
}

type CredentialsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          CredentialsRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.internal.CredentialsRequest_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRequest) Reset() {
	*x = CredentialsRequest{}
	mi := &file_host_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRequest) ProtoMessage() {}

func (x *CredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRequest) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialsRequest) GetType() CredentialsRequest_Type {
	if x != nil {
		return x.Type
	}
	return CredentialsRequest_UNKNOWN_TYPE
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        uint64                 `protobuf:"fixed64,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_host_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OneTimeSessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      uint32                 `protobuf:"varint,1,opt,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneTimeSessions) Reset() {
	*x = OneTimeSessions{}
	mi := &file_host_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneTimeSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneTimeSessions) ProtoMessage() {}

func (x *OneTimeSessions) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneTimeSessions.ProtoReflect.Descriptor instead.
func (*OneTimeSessions) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{2}
}

func (x *OneTimeSessions) GetSessions() uint32 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

type ConnectEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ComputerName  string                 `protobuf:"bytes,2,opt,name=computer_name,json=computerName,proto3" json:"computer_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SessionType   peer.SessionType       `protobuf:"varint,4,opt,name=session_type,json=sessionType,proto3,enum=proto.peer.SessionType" json:"session_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectEvent) Reset() {
	*x = ConnectEvent{}
	mi := &file_host_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectEvent) ProtoMessage() {}

func (x *ConnectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectEvent.ProtoReflect.Descriptor instead.
func (*ConnectEvent) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectEvent) GetComputerName() string {
	if x != nil {
		return x.ComputerName
	}
	return ""
}

func (x *ConnectEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ConnectEvent) GetSessionType() peer.SessionType {
	if x != nil {
		return x.SessionType
	}
	return peer.SessionType(0)
}

type DisconnectEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectEvent) Reset() {
	*x = DisconnectEvent{}
	mi := &file_host_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectEvent) ProtoMessage() {}

func (x *DisconnectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectEvent.ProtoReflect.Descriptor instead.
func (*DisconnectEvent) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RouterState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	HostPort      uint32                 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	State         RouterState_State      `protobuf:"varint,3,opt,name=state,proto3,enum=proto.internal.RouterState_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterState) Reset() {
	*x = RouterState{}
	mi := &file_host_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterState) ProtoMessage() {}

func (x *RouterState) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterState.ProtoReflect.Descriptor instead.
func (*RouterState) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{5}
}

func (x *RouterState) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RouterState) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *RouterState) GetState() RouterState_State {
	if x != nil {
		return x.State
	}
	return RouterState_UNKNOWN
}

type ConnectConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timeout       uint32                 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ComputerName  string                 `protobuf:"bytes,4,opt,name=computer_name,json=computerName,proto3" json:"computer_name,omitempty"`
	SessionType   peer.SessionType       `protobuf:"varint,5,opt,name=session_type,json=sessionType,proto3,enum=proto.peer.SessionType" json:"session_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectConfirmationRequest) Reset() {
	*x = ConnectConfirmationRequest{}
	mi := &file_host_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectConfirmationRequest) ProtoMessage() {}

func (x *ConnectConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectConfirmationRequest.ProtoReflect.Descriptor instead.
func (*ConnectConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectConfirmationRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectConfirmationRequest) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ConnectConfirmationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ConnectConfirmationRequest) GetComputerName() string {
	if x != nil {
		return x.ComputerName
	}
	return ""
}

func (x *ConnectConfirmationRequest) GetSessionType() peer.SessionType {
	if x != nil {
		return x.SessionType
	}
	return peer.SessionType(0)
}

type ConnectConfirmation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AcceptConnection bool                   `protobuf:"varint,2,opt,name=accept_connection,json=acceptConnection,proto3" json:"accept_connection,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectConfirmation) Reset() {
	*x = ConnectConfirmation{}
	mi := &file_host_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectConfirmation) ProtoMessage() {}

func (x *ConnectConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectConfirmation.ProtoReflect.Descriptor instead.
func (*ConnectConfirmation) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectConfirmation) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectConfirmation) GetAcceptConnection() bool {
	if x != nil {
		return x.AcceptConnection
	}
	return false
}

type ServiceControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ServiceControl_Code    `protobuf:"varint,1,opt,name=code,proto3,enum=proto.internal.ServiceControl_Code" json:"code,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*ServiceControl_SignedInteger
	//	*ServiceControl_UnsignedInteger
	//	*ServiceControl_Boolean
	//	*ServiceControl_Utf8String
	Value         isServiceControl_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceControl) Reset() {
	*x = ServiceControl{}
	mi := &file_host_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceControl) ProtoMessage() {}

func (x *ServiceControl) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceControl.ProtoReflect.Descriptor instead.
func (*ServiceControl) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceControl) GetCode() ServiceControl_Code {
	if x != nil {
		return x.Code
	}
	return ServiceControl_CODE_UNKNOWN
}

func (x *ServiceControl) GetValue() isServiceControl_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ServiceControl) GetSignedInteger() int64 {
	if x != nil {
		if x, ok := x.Value.(*ServiceControl_SignedInteger); ok {
			return x.SignedInteger
		}
	}
	return 0
}

func (x *ServiceControl) GetUnsignedInteger() uint64 {
	if x != nil {
		if x, ok := x.Value.(*ServiceControl_UnsignedInteger); ok {
			return x.UnsignedInteger
		}
	}
	return 0
}

func (x *ServiceControl) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Value.(*ServiceControl_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *ServiceControl) GetUtf8String() string {
	if x != nil {
		if x, ok := x.Value.(*ServiceControl_Utf8String); ok {
			return x.Utf8String
		}
	}
	return ""
}

type isServiceControl_Value interface {
	isServiceControl_Value()
}

type ServiceControl_SignedInteger struct {
	SignedInteger int64 `protobuf:"varint,2,opt,name=signed_integer,json=signedInteger,proto3,oneof"`
}

type ServiceControl_UnsignedInteger struct {
	UnsignedInteger uint64 `protobuf:"varint,3,opt,name=unsigned_integer,json=unsignedInteger,proto3,oneof"`
}

type ServiceControl_Boolean struct {
	Boolean bool `protobuf:"varint,4,opt,name=boolean,proto3,oneof"`
}

type ServiceControl_Utf8String struct {
	Utf8String string `protobuf:"bytes,5,opt,name=utf8_string,json=utf8String,proto3,oneof"`
}

func (*ServiceControl_SignedInteger) isServiceControl_Value() {}

func (*ServiceControl_UnsignedInteger) isServiceControl_Value() {}

func (*ServiceControl_Boolean) isServiceControl_Value() {}

func (*ServiceControl_Utf8String) isServiceControl_Value() {}

type VideoRecordingState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComputerName  string                 `protobuf:"bytes,1,opt,name=computer_name,json=computerName,proto3" json:"computer_name,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Started       bool                   `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRecordingState) Reset() {
	*x = VideoRecordingState{}
	mi := &file_host_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRecordingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRecordingState) ProtoMessage() {}

func (x *VideoRecordingState) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRecordingState.ProtoReflect.Descriptor instead.
func (*VideoRecordingState) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{9}
}

func (x *VideoRecordingState) GetComputerName() string {
	if x != nil {
		return x.ComputerName
	}
	return ""
}

func (x *VideoRecordingState) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *VideoRecordingState) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

type UiToService struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CredentialsRequest  *CredentialsRequest    `protobuf:"bytes,1,opt,name=credentials_request,json=credentialsRequest,proto3" json:"credentials_request,omitempty"`
	OneTimeSessions     *OneTimeSessions       `protobuf:"bytes,2,opt,name=one_time_sessions,json=oneTimeSessions,proto3" json:"one_time_sessions,omitempty"`
	ConnectConfirmation *ConnectConfirmation   `protobuf:"bytes,3,opt,name=connect_confirmation,json=connectConfirmation,proto3" json:"connect_confirmation,omitempty"`
	Control             *ServiceControl        `protobuf:"bytes,4,opt,name=control,proto3" json:"control,omitempty"`
	TextChat            *text_chat.TextChat    `protobuf:"bytes,5,opt,name=text_chat,json=textChat,proto3" json:"text_chat,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UiToService) Reset() {
	*x = UiToService{}
	mi := &file_host_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiToService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiToService) ProtoMessage() {}

func (x *UiToService) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiToService.ProtoReflect.Descriptor instead.
func (*UiToService) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{10}
}

func (x *UiToService) GetCredentialsRequest() *CredentialsRequest {
	if x != nil {
		return x.CredentialsRequest
	}
	return nil
}

func (x *UiToService) GetOneTimeSessions() *OneTimeSessions {
	if x != nil {
		return x.OneTimeSessions
	}
	return nil
}

func (x *UiToService) GetConnectConfirmation() *ConnectConfirmation {
	if x != nil {
		return x.ConnectConfirmation
	}
	return nil
}

func (x *UiToService) GetControl() *ServiceControl {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *UiToService) GetTextChat() *text_chat.TextChat {
	if x != nil {
		return x.TextChat
	}
	return nil
}

type ServiceToUi struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	RouterState                *RouterState                `protobuf:"bytes,1,opt,name=router_state,json=routerState,proto3" json:"router_state,omitempty"`
	Credentials                *Credentials                `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	ConnectEvent               *ConnectEvent               `protobuf:"bytes,3,opt,name=connect_event,json=connectEvent,proto3" json:"connect_event,omitempty"`
	DisconnectEvent            *DisconnectEvent            `protobuf:"bytes,4,opt,name=disconnect_event,json=disconnectEvent,proto3" json:"disconnect_event,omitempty"`
	ConnectConfirmationRequest *ConnectConfirmationRequest `protobuf:"bytes,5,opt,name=connect_confirmation_request,json=connectConfirmationRequest,proto3" json:"connect_confirmation_request,omitempty"`
	VideoRecordingState        *VideoRecordingState        `protobuf:"bytes,6,opt,name=video_recording_state,json=videoRecordingState,proto3" json:"video_recording_state,omitempty"`
	TextChat                   *text_chat.TextChat         `protobuf:"bytes,7,opt,name=text_chat,json=textChat,proto3" json:"text_chat,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ServiceToUi) Reset() {
	*x = ServiceToUi{}
	mi := &file_host_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceToUi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceToUi) ProtoMessage() {}

func (x *ServiceToUi) ProtoReflect() protoreflect.Message {
	mi := &file_host_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceToUi.ProtoReflect.Descriptor instead.
func (*ServiceToUi) Descriptor() ([]byte, []int) {
	return file_host_internal_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceToUi) GetRouterState() *RouterState {
	if x != nil {
		return x.RouterState
	}
	return nil
}

func (x *ServiceToUi) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ServiceToUi) GetConnectEvent() *ConnectEvent {
	if x != nil {
		return x.ConnectEvent
	}
	return nil
}

func (x *ServiceToUi) GetDisconnectEvent() *DisconnectEvent {
	if x != nil {
		return x.DisconnectEvent
	}
	return nil
}

func (x *ServiceToUi) GetConnectConfirmationRequest() *ConnectConfirmationRequest {
	if x != nil {
		return x.ConnectConfirmationRequest
	}
	return nil
}

func (x *ServiceToUi) GetVideoRecordingState() *VideoRecordingState {
	if x != nil {
		return x.VideoRecordingState
	}
	return nil
}

func (x *ServiceToUi) GetTextChat() *text_chat.TextChat {
	if x != nil {
		return x.TextChat
	}
	return nil
}

var File_host_internal_proto protoreflect.FileDescriptor

const file_host_internal_proto_rawDesc = "" +
	"\n" +
	"\x13host_internal.proto\x12\x0eproto.internal\x1a\n" +
	"peer.proto\x1a\x0ftext_chat.proto\"\x8a\x01\n" +
	"\x12CredentialsRequest\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.proto.internal.CredentialsRequest.TypeR\x04type\"7\n" +
	"\x04Type\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\v\n" +
	"\aREFRESH\x10\x01\x12\x10\n" +
	"\fNEW_PASSWORD\x10\x02\"B\n" +
	"\vCredentials\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\x06R\x06hostId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"-\n" +
	"\x0fOneTimeSessions\x12\x1a\n" +
	"\bsessions\x18\x01 \x01(\rR\bsessions\"\xa2\x01\n" +
	"\fConnectEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12#\n" +
	"\rcomputer_name\x18\x02 \x01(\tR\fcomputerName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12:\n" +
	"\fsession_type\x18\x04 \x01(\x0e2\x17.proto.peer.SessionTypeR\vsessionType\"!\n" +
	"\x0fDisconnectEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xcf\x01\n" +
	"\vRouterState\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\x127\n" +
	"\x05state\x18\x03 \x01(\x0e2!.proto.internal.RouterState.StateR\x05state\"M\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bDISABLED\x10\x01\x12\x0e\n" +
	"\n" +
	"CONNECTING\x10\x02\x12\r\n" +
	"\tCONNECTED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\"\xc4\x01\n" +
	"\x1aConnectConfirmationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\rR\atimeout\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12#\n" +
	"\rcomputer_name\x18\x04 \x01(\tR\fcomputerName\x12:\n" +
	"\fsession_type\x18\x05 \x01(\x0e2\x17.proto.peer.SessionTypeR\vsessionType\"R\n" +
	"\x13ConnectConfirmation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12+\n" +
	"\x11accept_connection\x18\x02 \x01(\bR\x10acceptConnection\"\xe2\x02\n" +
	"\x0eServiceControl\x127\n" +
	"\x04code\x18\x01 \x01(\x0e2#.proto.internal.ServiceControl.CodeR\x04code\x12'\n" +
	"\x0esigned_integer\x18\x02 \x01(\x03H\x00R\rsignedInteger\x12+\n" +
	"\x10unsigned_integer\x18\x03 \x01(\x04H\x00R\x0funsignedInteger\x12\x1a\n" +
	"\aboolean\x18\x04 \x01(\bH\x00R\aboolean\x12!\n" +
	"\vutf8_string\x18\x05 \x01(\tH\x00R\n" +
	"utf8String\"y\n" +
	"\x04Code\x12\x10\n" +
	"\fCODE_UNKNOWN\x10\x00\x12\r\n" +
	"\tCODE_KILL\x10\x01\x12\x0e\n" +
	"\n" +
	"CODE_PAUSE\x10\x02\x12\x13\n" +
	"\x0fCODE_LOCK_MOUSE\x10\x03\x12\x16\n" +
	"\x12CODE_LOCK_KEYBOARD\x10\x04\x12\x13\n" +
	"\x0fCODE_VOICE_CHAT\x10\x05B\a\n" +
	"\x05value\"q\n" +
	"\x13VideoRecordingState\x12#\n" +
	"\rcomputer_name\x18\x01 \x01(\tR\fcomputerName\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x18\n" +
	"\astarted\x18\x03 \x01(\bR\astarted\"\xf9\x02\n" +
	"\vUiToService\x12S\n" +
	"\x13credentials_request\x18\x01 \x01(\v2\".proto.internal.CredentialsRequestR\x12credentialsRequest\x12K\n" +
	"\x11one_time_sessions\x18\x02 \x01(\v2\x1f.proto.internal.OneTimeSessionsR\x0foneTimeSessions\x12V\n" +
	"\x14connect_confirmation\x18\x03 \x01(\v2#.proto.internal.ConnectConfirmationR\x13connectConfirmation\x128\n" +
	"\acontrol\x18\x04 \x01(\v2\x1e.proto.internal.ServiceControlR\acontrol\x126\n" +
	"\ttext_chat\x18\x05 \x01(\v2\x19.proto.text_chat.TextChatR\btextChat\"\x9a\x04\n" +
	"\vServiceToUi\x12>\n" +
	"\frouter_state\x18\x01 \x01(\v2\x1b.proto.internal.RouterStateR\vrouterState\x12=\n" +
	"\vcredentials\x18\x02 \x01(\v2\x1b.proto.internal.CredentialsR\vcredentials\x12A\n" +
	"\rconnect_event\x18\x03 \x01(\v2\x1c.proto.internal.ConnectEventR\fconnectEvent\x12J\n" +
	"\x10disconnect_event\x18\x04 \x01(\v2\x1f.proto.internal.DisconnectEventR\x0fdisconnectEvent\x12l\n" +
	"\x1cconnect_confirmation_request\x18\x05 \x01(\v2*.proto.internal.ConnectConfirmationRequestR\x1aconnectConfirmationRequest\x12W\n" +
	"\x15video_recording_state\x18\x06 \x01(\v2#.proto.internal.VideoRecordingStateR\x13videoRecordingState\x126\n" +
	"\ttext_chat\x18\a \x01(\v2\x19.proto.text_chat.TextChatR\btextChatB&H\x03Z\"aspia_rest_api/proto/host_internalb\x06proto3"

var (
	file_host_internal_proto_rawDescOnce sync.Once
	file_host_internal_proto_rawDescData []byte
)

func file_host_internal_proto_rawDescGZIP() []byte {
	file_host_internal_proto_rawDescOnce.Do(func() {
		file_host_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_host_internal_proto_rawDesc), len(file_host_internal_proto_rawDesc)))
	})
	return file_host_internal_proto_rawDescData
}

var file_host_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_host_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_host_internal_proto_goTypes = []any{
	(CredentialsRequest_Type)(0),       // 0: proto.internal.CredentialsRequest.Type
	(RouterState_State)(0),             // 1: proto.internal.RouterState.State
	(ServiceControl_Code)(0),           // 2: proto.internal.ServiceControl.Code
	(*CredentialsRequest)(nil),         // 3: proto.internal.CredentialsRequest
	(*Credentials)(nil),                // 4: proto.internal.Credentials
	(*OneTimeSessions)(nil),            // 5: proto.internal.OneTimeSessions
	(*ConnectEvent)(nil),               // 6: proto.internal.ConnectEvent
	(*DisconnectEvent)(nil),            // 7: proto.internal.DisconnectEvent
	(*RouterState)(nil),                // 8: proto.internal.RouterState
	(*ConnectConfirmationRequest)(nil), // 9: proto.internal.ConnectConfirmationRequest
	(*ConnectConfirmation)(nil),        // 10: proto.internal.ConnectConfirmation
	(*ServiceControl)(nil),             // 11: proto.internal.ServiceControl
	(*VideoRecordingState)(nil),        // 12: proto.internal.VideoRecordingState
	(*UiToService)(nil),                // 13: proto.internal.UiToService
	(*ServiceToUi)(nil),                // 14: proto.internal.ServiceToUi
	(peer.SessionType)(0),              // 15: proto.peer.SessionType
	(*text_chat.TextChat)(nil),         // 16: proto.text_chat.TextChat
}
var file_host_internal_proto_depIdxs = []int32{
	0,  // 0: proto.internal.CredentialsRequest.type:type_name -> proto.internal.CredentialsRequest.Type
	15, // 1: proto.internal.ConnectEvent.session_type:type_name -> proto.peer.SessionType
	1,  // 2: proto.internal.RouterState.state:type_name -> proto.internal.RouterState.State
	15, // 3: proto.internal.ConnectConfirmationRequest.session_type:type_name -> proto.peer.SessionType
	2,  // 4: proto.internal.ServiceControl.code:type_name -> proto.internal.ServiceControl.Code
	3,  // 5: proto.internal.UiToService.credentials_request:type_name -> proto.internal.CredentialsRequest
	5,  // 6: proto.internal.UiToService.one_time_sessions:type_name -> proto.internal.OneTimeSessions
	10, // 7: proto.internal.UiToService.connect_confirmation:type_name -> proto.internal.ConnectConfirmation
	11, // 8: proto.internal.UiToService.control:type_name -> proto.internal.ServiceControl
	16, // 9: proto.internal.UiToService.text_chat:type_name -> proto.text_chat.TextChat
	8,  // 10: proto.internal.ServiceToUi.router_state:type_name -> proto.internal.RouterState
	4,  // 11: proto.internal.ServiceToUi.credentials:type_name -> proto.internal.Credentials
	6,  // 12: proto.internal.ServiceToUi.connect_event:type_name -> proto.internal.ConnectEvent
	7,  // 13: proto.internal.ServiceToUi.disconnect_event:type_name -> proto.internal.DisconnectEvent
	9,  // 14: proto.internal.ServiceToUi.connect_confirmation_request:type_name -> proto.internal.ConnectConfirmationRequest
	12, // 15: proto.internal.ServiceToUi.video_recording_state:type_name -> proto.internal.VideoRecordingState
	16, // 16: proto.internal.ServiceToUi.text_chat:type_name -> proto.text_chat.TextChat
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_host_internal_proto_init() }
func file_host_internal_proto_init() {
	if File_host_internal_proto != nil {
		return
	}
	file_host_internal_proto_msgTypes[8].OneofWrappers = []any{
		(*ServiceControl_SignedInteger)(nil),
		(*ServiceControl_UnsignedInteger)(nil),
		(*ServiceControl_Boolean)(nil),
		(*ServiceControl_Utf8String)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_host_internal_proto_rawDesc), len(file_host_internal_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_host_internal_proto_goTypes,
		DependencyIndexes: file_host_internal_proto_depIdxs,
		EnumInfos:         file_host_internal_proto_enumTypes,
		MessageInfos:      file_host_internal_proto_msgTypes,
	}.Build()
	File_host_internal_proto = out.File
	file_host_internal_proto_goTypes = nil
	file_host_internal_proto_depIdxs = nil
}
