//
// Aspia Project
// Copyright (C) 2016-2025 Dmitry Chapyshev <dmitry@aspia.ru>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: port_forwarding.proto

package port_forwarding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result_ErrorCode int32

const (
	Result_UNKNOWN Result_ErrorCode = 0
	Result_SUCCESS Result_ErrorCode = 1
	Result_TIMEOUT Result_ErrorCode = 2
)

// Enum value maps for Result_ErrorCode.
var (
	Result_ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "TIMEOUT",
	}
	Result_ErrorCode_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"TIMEOUT": 2,
	}
)

func (x Result_ErrorCode) Enum() *Result_ErrorCode {
	p := new(Result_ErrorCode)
	*p = x
	return p
}

func (x Result_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_port_forwarding_proto_enumTypes[0].Descriptor()
}

func (Result_ErrorCode) Type() protoreflect.EnumType {
	return &file_port_forwarding_proto_enumTypes[0]
}

func (x Result_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result_ErrorCode.Descriptor instead.
func (Result_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_port_forwarding_proto_rawDescGZIP(), []int{2, 0}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteHost    string                 `protobuf:"bytes,1,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"`
	RemotePort    uint32                 `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	LocalPort     uint32                 `protobuf:"varint,3,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	CommandLine   string                 `protobuf:"bytes,4,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_port_forwarding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_port_forwarding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_port_forwarding_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *Config) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *Config) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *Config) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteHost    string                 `protobuf:"bytes,1,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"`
	RemotePort    uint32                 `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_port_forwarding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_port_forwarding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_port_forwarding_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *Request) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     Result_ErrorCode       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=proto.port_forwarding.Result_ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_port_forwarding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_port_forwarding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_port_forwarding_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetErrorCode() Result_ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return Result_UNKNOWN
}

type Start struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dummy         uint32                 `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_port_forwarding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_port_forwarding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_port_forwarding_proto_rawDescGZIP(), []int{3}
}

func (x *Start) GetDummy() uint32 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_port_forwarding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_port_forwarding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_port_forwarding_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClientToHost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Start         *Start                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToHost) Reset() {
	*x = ClientToHost{}
	mi := &file_port_forwarding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToHost) ProtoMessage() {}

func (x *ClientToHost) ProtoReflect() protoreflect.Message {
	mi := &file_port_forwarding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToHost.ProtoReflect.Descriptor instead.
func (*ClientToHost) Descriptor() ([]byte, []int) {
	return file_port_forwarding_proto_rawDescGZIP(), []int{5}
}

func (x *ClientToHost) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ClientToHost) GetStart() *Start {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ClientToHost) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type HostToClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostToClient) Reset() {
	*x = HostToClient{}
	mi := &file_port_forwarding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostToClient) ProtoMessage() {}

func (x *HostToClient) ProtoReflect() protoreflect.Message {
	mi := &file_port_forwarding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostToClient.ProtoReflect.Descriptor instead.
func (*HostToClient) Descriptor() ([]byte, []int) {
	return file_port_forwarding_proto_rawDescGZIP(), []int{6}
}

func (x *HostToClient) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HostToClient) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_port_forwarding_proto protoreflect.FileDescriptor

const file_port_forwarding_proto_rawDesc = "" +
	"\n" +
	"\x15port_forwarding.proto\x12\x15proto.port_forwarding\"\x8c\x01\n" +
	"\x06Config\x12\x1f\n" +
	"\vremote_host\x18\x01 \x01(\tR\n" +
	"remoteHost\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\rR\n" +
	"remotePort\x12\x1d\n" +
	"\n" +
	"local_port\x18\x03 \x01(\rR\tlocalPort\x12!\n" +
	"\fcommand_line\x18\x04 \x01(\tR\vcommandLine\"K\n" +
	"\aRequest\x12\x1f\n" +
	"\vremote_host\x18\x01 \x01(\tR\n" +
	"remoteHost\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\rR\n" +
	"remotePort\"\x84\x01\n" +
	"\x06Result\x12F\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2'.proto.port_forwarding.Result.ErrorCodeR\terrorCode\"2\n" +
	"\tErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aTIMEOUT\x10\x02\"\x1d\n" +
	"\x05Start\x12\x14\n" +
	"\x05dummy\x18\x01 \x01(\rR\x05dummy\"\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xad\x01\n" +
	"\fClientToHost\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1e.proto.port_forwarding.RequestR\arequest\x122\n" +
	"\x05start\x18\x02 \x01(\v2\x1c.proto.port_forwarding.StartR\x05start\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.proto.port_forwarding.DataR\x04data\"v\n" +
	"\fHostToClient\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.proto.port_forwarding.ResultR\x06result\x12/\n" +
	"\x04data\x18\x02 \x01(\v2\x1b.proto.port_forwarding.DataR\x04dataB(H\x03Z$aspia_rest_api/proto/port_forwardingb\x06proto3"

var (
	file_port_forwarding_proto_rawDescOnce sync.Once
	file_port_forwarding_proto_rawDescData []byte
)

func file_port_forwarding_proto_rawDescGZIP() []byte {
	file_port_forwarding_proto_rawDescOnce.Do(func() {
		file_port_forwarding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_port_forwarding_proto_rawDesc), len(file_port_forwarding_proto_rawDesc)))
	})
	return file_port_forwarding_proto_rawDescData
}

var file_port_forwarding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_port_forwarding_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_port_forwarding_proto_goTypes = []any{
	(Result_ErrorCode)(0), // 0: proto.port_forwarding.Result.ErrorCode
	(*Config)(nil),        // 1: proto.port_forwarding.Config
	(*Request)(nil),       // 2: proto.port_forwarding.Request
	(*Result)(nil),        // 3: proto.port_forwarding.Result
	(*Start)(nil),         // 4: proto.port_forwarding.Start
	(*Data)(nil),          // 5: proto.port_forwarding.Data
	(*ClientToHost)(nil),  // 6: proto.port_forwarding.ClientToHost
	(*HostToClient)(nil),  // 7: proto.port_forwarding.HostToClient
}
var file_port_forwarding_proto_depIdxs = []int32{
	0, // 0: proto.port_forwarding.Result.error_code:type_name -> proto.port_forwarding.Result.ErrorCode
	2, // 1: proto.port_forwarding.ClientToHost.request:type_name -> proto.port_forwarding.Request
	4, // 2: proto.port_forwarding.ClientToHost.start:type_name -> proto.port_forwarding.Start
	5, // 3: proto.port_forwarding.ClientToHost.data:type_name -> proto.port_forwarding.Data
	3, // 4: proto.port_forwarding.HostToClient.result:type_name -> proto.port_forwarding.Result
	5, // 5: proto.port_forwarding.HostToClient.data:type_name -> proto.port_forwarding.Data
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_port_forwarding_proto_init() }
func file_port_forwarding_proto_init() {
	if File_port_forwarding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_port_forwarding_proto_rawDesc), len(file_port_forwarding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_port_forwarding_proto_goTypes,
		DependencyIndexes: file_port_forwarding_proto_depIdxs,
		EnumInfos:         file_port_forwarding_proto_enumTypes,
		MessageInfos:      file_port_forwarding_proto_msgTypes,
	}.Build()
	File_port_forwarding_proto = out.File
	file_port_forwarding_proto_goTypes = nil
	file_port_forwarding_proto_depIdxs = nil
}
